// Code generated by MockGen. DO NOT EDIT.
// Source: session.go

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nebula_ng_go "github.com/vesoft-inc/nebula-ng-tools/golang"
)

// MockNebulaSession is a mock of NebulaSession interface.
type MockNebulaSession struct {
	ctrl     *gomock.Controller
	recorder *MockNebulaSessionMockRecorder
}

// MockNebulaSessionMockRecorder is the mock recorder for MockNebulaSession.
type MockNebulaSessionMockRecorder struct {
	mock *MockNebulaSession
}

// NewMockNebulaSession creates a new mock instance.
func NewMockNebulaSession(ctrl *gomock.Controller) *MockNebulaSession {
	mock := &MockNebulaSession{ctrl: ctrl}
	mock.recorder = &MockNebulaSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNebulaSession) EXPECT() *MockNebulaSessionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNebulaSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockNebulaSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNebulaSession)(nil).Close))
}

// Execute mocks base method.
func (m *MockNebulaSession) Execute(statement string) (*nebula_ng_go.ResultSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", statement)
	ret0, _ := ret[0].(*nebula_ng_go.ResultSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockNebulaSessionMockRecorder) Execute(statement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockNebulaSession)(nil).Execute), statement)
}

// Open mocks base method.
func (m *MockNebulaSession) Open() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockNebulaSessionMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockNebulaSession)(nil).Open))
}
