nebulaCluster:
  console:
    image: reg.vesoft-inc.com/vesoft-ng/ngql
    version: latest
  replicaFactor: 3
  zones:
    - az1
    - az2
    - az3
  metadRef:
    name: metad-sample
  credentialSecret: "nebula"

  graphd:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    replicas: 1
    image: reg.vesoft-inc.com/vesoft-ng/nebula-graphd
    version: nightly
    serviceType: NodePort
    logVolume:
      enable: true
      storage: "500Mi"
    storageClassName: local-path
    env: []
    config: {}
    nodeSelector: {}
    affinity: {}
    podLabels: {}
    podAnnotations: {}
    tolerations: []
    readinessProbe: {}
    livenessProbe: {}
    initContainers: []
    sidecarContainers: []
    volumes: []
    volumeMounts: []

  storaged:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
    replicas: 3
    image: reg.vesoft-inc.com/vesoft-ng/nebula-storaged
    version: nightly
    dataVolumes:
    - storage: "10Gi"
    logVolume:
      enable: true
      storage: "1Gi"
    storageClassName: local-path
    env: []
    config: {}
    nodeSelector: {}
    affinity: {}
    enableAutoBalance: false
    podLabels: {}
    podAnnotations: {}
    tolerations: []
    readinessProbe: {}
    livenessProbe: {}
    initContainers: []
    sidecarContainers: []
    volumes: []
    volumeMounts: []

  exporter:
    image: vesoft/nebula-stats-exporter
    version: latest
    replicas: 1
    env: []
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    podLabels: {}
    podAnnotations: {}
    securityContext: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    livenessProbe: {}
    initContainers: []
    sidecarContainers: []
    volumes: []
    volumeMounts: []
    maxRequests: 20

  enablePVReclaim: false
  schedulerName: default-scheduler # nebula-scheduler
  imagePullPolicy: Always
  imagePullSecrets: []
  topologySpreadConstraints:
  - topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: "ScheduleAnyway"

nameOverride: ""
fullnameOverride: ""