// Code generated by goctl. DO NOT EDIT.
package storage

import (
	"net/http"

	"github.com/vesoft-inc/go-pkg/validator"
	"github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/pkg/ecode"

	"github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/logic/storage"
	"github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/svc"
	"github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/types"
	"github.com/zeromicro/go-zero/rest/httpx"
)

func HdfsUploadHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.HDFSUploadReq
		if err := httpx.Parse(r, &req); err != nil {
			err = ecode.WithCode(ecode.ErrParam, err)
			svcCtx.ResponseHandler.Handle(w, r, nil, err)
			return
		}
		if err := validator.Struct(&req); err != nil {
			svcCtx.ResponseHandler.Handle(w, r, nil, err)
			return
		}

		l := storage.NewHdfsUploadLogic(r.Context(), svcCtx)
		data, err := l.HdfsUpload(&req)
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
