// Q4. New topics
/*
:param [{ personId, startDate, endDate }] => { RETURN
  4398046511333 AS personId,
  1275350400000 AS startDate,
  1277856000000 AS endDate
}
*/
USE $graphName
MATCH
  (person:Person {id : $personId})<-[:KNOWS]->(friend:Person)<-[:HAS_CREATOR]-(post:Post)-[:HAS_TAG]->(tag:Tag)
RETURN DISTINCT tag, post
NEXT
USE $graphName
LET valid = CASE
        WHEN local_datetime($endDate, "%Y-%m-%dT%H:%M:%S") > post.creationDate AND post.creationDate >= local_datetime($startDate, "%Y-%m-%dT%H:%M:%S") THEN 1
        ELSE 0
    END,
    invalid = CASE
        WHEN local_datetime($startDate, "%Y-%m-%dT%H:%M:%S") > post.creationDate THEN 1
        ELSE 0
    END
RETURN sum(valid) AS postCount, sum(invalid) AS inValidPostCount, tag GROUP BY tag
NEXT USE $graphName
FILTER WHERE postCount>0 AND inValidPostCount=0
ORDER BY postCount DESC, tag.name ASC
LIMIT 10
RETURN tag.name AS tagName, postCount
