// Q9. Recent messages by friends or friends of friends
/*
:param [{ personId, maxDate }] => { RETURN
  4398046511268 AS personId,
  1289908800000 AS maxDate
}
*/
USE $graphName
MATCH (root:Person {id: $personId })<-[:KNOWS]->{1,2}(friend:Person)
WHERE friend <> root
RETURN DISTINCT friend
NEXT
USE $graphName
    MATCH (friend:Person)<-[:HAS_CREATOR]-(message:Message WHERE message.creationDate < local_datetime($maxDate, "%Y-%m-%dT%H:%M:%S"))
ORDER BY
  message.creationDate DESC,
  message.id ASC
LIMIT 20
RETURN
  friend.id AS personId,
  friend.firstName AS personFirstName,
  friend.lastName AS personLastName,
  message.id AS commentOrPostId,
  COALESCE(message.content, message.imageFile) AS commentOrPostContent,
  cast(message.creationDate as local datetime) AS commentOrPostCreationDate
