USE $graphName
INSERT NODE Person ({id: $personId,
                     firstName: $personFirstName,
                     lastName: $personLastName,
                     gender: $gender,
                     birthday: date($birthday),
                     creationDate: localdatetime($creationDate),
                     locationIP: $locationIP,
                     browserUsed: $browserUsed,
                     email: $emails,
                     speaks: $languages})