// Q13. Single shortest path
/*
:param [{ person1Id, person2Id }] => { RETURN
  8796093022390 AS person1Id,
  8796093022357 AS person2Id
}
*/
USE $graphName
MATCH
  path1 = ANY SHORTEST PATH (person1:Person{id: $person1Id})<-[:KNOWS]->{1,10}(person2:Person{id: $person2Id})
RETURN
  CASE
      WHEN path1 IS NULL THEN -1
      ELSE length(path1)
  END AS shortestPathLength
