// Q11. Job referral
/*
:param [{ personId, countryName, workFromYear }] => { RETURN
  10995116277918 AS personId,
  "Hungary" AS countryName,
  2011 AS workFromYear
}
*/
USE $graphName
MATCH (person:Person {id: $personId })<-[:KNOWS]->{1,2}(friend:Person)
WHERE person <> friend
RETURN DISTINCT friend
NEXT
USE $graphName
MATCH (friend:Person)-[workAt:WORK_AT WHERE workAt.workFrom < $workFromYear]->(company:Company)-[:IS_LOCATED_IN]->(:Country {name : "$countryName"})
ORDER BY
  workAt.workFrom ASC,
  friend.id ASC,
  company.name DESC
LIMIT 10
RETURN
  friend.id AS personId,
  friend.firstName AS personFirstName,
  friend.lastName AS personLastName,
  company.name AS organizationName,
  workAt.workFrom AS organizationWorkFromYear

