// Q6. Tag co-occurrence
/*
:param [{ personId, tagName }] => { RETURN
  4398046511333 AS personId,
  "Carl_Gustaf_Emil_Mannerheim" AS tagName
}
*/
USE $graphName
MATCH WALK (person:Person {id : $personId})<-[:KNOWS]->{1,2}(friend:Person)
WHERE person <> friend
RETURN distinct friend AS f
NEXT USE $graphName
MATCH (f:Person)<-[:HAS_CREATOR]-(post:Post)-[:HAS_TAG]->(t:Tag {name : "$tagName"})
MATCH (post:Post)-[:HAS_TAG]->(tag:Tag)
FILTER t <> tag
RETURN count(post) AS postCount, tag
NEXT USE $graphName
ORDER BY
  postCount DESC,
  tag.name ASC
LIMIT 10
RETURN
  tag.name AS tagName,
  postCount