// Q8. Recent replies
/*
:param personId: 143
*/
USE $graphName
MATCH (startPerson:Person {id: $personId})<-[:HAS_CREATOR]-(:Message)<-[:REPLY_OF]-(comment:Comment)-[:HAS_CREATOR]->(person:Person)
ORDER BY
  comment.creationDate DESC,
  comment.id ASC
LIMIT 20
RETURN
  person.id AS personId,
  person.firstName AS personFirstName,
  person.lastName AS personLastName,
  cast(comment.creationDate as local datetime) AS commentCreationDate,
  comment.id AS commentId,
  comment.content AS commentContent
