// Q13. Single shortest path
/*
:param [{ person1Id, person2Id }] => { RETURN
  8796093022390 AS person1Id,
  8796093022357 AS person2Id
}
*/

USE $graphName
OPTIONAL MATCH ANY SHORTEST (person1:Person{id: $person1Id})<-[e:KNOWS]->*(person2:Person{id: $person2Id})
RETURN CASE WHEN e IS NULL THEN -1 ELSE size(e) END AS shortestPathLength
