// Q1. Transitive friends with certain name
/*
:param [{ personId, firstName }] => { RETURN
  4398046511333 AS personId,
  "Jose" AS firstName
}
*/
USE $graphName
MATCH (p:Person{id:$personId})<-[e:KNOWS]->{1,3}(friend:Person{firstName : "$firstName"}) WHERE p<>friend
RETURN min(length(e)) AS distance, friend GROUP BY friend
NEXT USE $graphName
ORDER BY
  distance ASC,
  friend.lastName ASC,
  friend.id ASC
LIMIT 20
MATCH (friend:Person)-[:IS_LOCATED_IN]->(friendCity:City)
OPTIONAL MATCH (friend:Person)-[studyAt:STUDY_AT]->(uni:University)-[:IS_LOCATED_IN]->(uniCity:City)
RETURN collect(
  CASE 
    WHEN NOT uni.name IS NULL THEN RECORD {uniName:uni.name, studyAtClassYear:studyAt.classYear, uniCityName:uniCity.name}
  END
  ) AS unis,friend, friendCity, distance GROUP BY friend, friendCity, distance
NEXT USE $graphName
OPTIONAL MATCH (friend:Person)-[workAt:WORK_AT]->(company:Company)-[:IS_LOCATED_IN]->(companyCountry:Country)
RETURN collect(
  CASE
    WHEN NOT company.name is null THEN RECORD {companyName:company.name, workAtWorkFrom:workAt.workFrom, companyCountryName:companyCountry.name}
  END 
  ) AS companies, friend, unis, friendCity, distance GROUP BY friend, unis, friendCity, distance
ORDER BY
  distance ASC,
  friend.lastName ASC,
  friend.id ASC
LIMIT 20
NEXT USE $graphName
RETURN
  friend.id AS friendId,
  friend.lastName AS friendLastName,
  distance AS distanceFromPerson,
  friend.birthday AS friendBirthday,
  friend.creationDate AS friendCreationDate,
  friend.gender AS friendGender,
  friend.browserUsed AS friendBrowserUsed,
  friend.locationIP AS friendLocationIp,
  friend.email AS friendEmails,
  friend.speaks AS friendLanguages,
  friendCity.name AS friendCityName,
  unis AS friendUniversities,
  companies AS friendCompanies
