// Q9. Recent messages by friends or friends of friends
/*
:param [{ personId, maxDate }] => { RETURN
  4398046511268 AS personId,
  1289908800000 AS maxDate
}
*/
USE $graphName
MATCH WALK (root:Person {id: $personId })<-[:KNOWS]->{1,2}(friend:Person)
WHERE friend <> root
RETURN DISTINCT friend
NEXT
USE $graphName
    MATCH (friend:Person)<-[:HAS_CREATOR]-(message:Message WHERE message.creationDate < localdatetime($maxDate))
ORDER BY
  message.creationDate DESC,
  message.id ASC
LIMIT 20
RETURN
  friend.id AS personId,
  friend.firstName AS personFirstName,
  friend.lastName AS personLastName,
  message.id AS commentOrPostId,
  CASE WHEN message.content <> ""
       THEN message.content
       ELSE message.imageFile
  END AS commentOrPostContent,
  message.creationDate AS commentOrPostCreationDate