USE $graphName
INSERT NODE Comment ({id: $commentId,
                      creationDate: localdatetime($creationDate),
                      locationIP: $locationIP,
                      browserUsed: $browserUsed,
                      content: $content,
                      extent: $length})
