// Q4. New topics
/*
:param [{ personId, startDate, endDate }] => { RETURN
  4398046511333 AS personId,
  1275350400000 AS startDate,
  1277856000000 AS endDate
}
*/
USE $graphName
MATCH
  (person:Person {id : $personId})<-[:KNOWS]->(friend:Person),
  (friend:Person)<-[:HAS_CREATOR]-(post:Post)-[:HAS_TAG]->(tag:Tag)
RETURN DISTINCT tag, post
NEXT
USE $graphName
LET valid = CASE
        WHEN $endDate > post.creationDate AND post.creationDate >= $startDate THEN 1
        ELSE 0
    END,
    invalid = CASE
        WHEN $startDate > post.creationDate THEN 1
        ELSE 0
    END
AGGREGATE postCount=sum(valid), inValidPostCount=sum(inValid) GROUP BY tag
FILTER WHERE postCount>0 AND inValidPostCount=0
ORDER BY postCount DESC, tag.name ASC
LIMIT 10
RETURN tag.name AS tagName, postCount