// Q12. Expert search
/*
:param [{ personId, tagClassName }] => { RETURN
  10995116278009 AS personId,
  "Monarch" AS tagClassName
}
*/
USE $graphName
MATCH WALK (tag:Tag)-[:HAS_TYPE|IS_SUBCLASS_OF]->{0,3}(baseTagClass:TagClass)
WHERE tag.name = "$tagClassName" OR baseTagClass.name = "$tagClassName"
AGGREGATE tags=collect(tag.id)
MATCH (:Person {id: $personId })<-[:KNOWS]->(friend:Person)<-[:HAS_CREATOR]-(comment:Comment)-[:REPLY_OF]->(:Post)-[:HAS_TAG]->(tag:Tag)
FILTER WHERE tag.id IN tags
AGGREGATE tagNames=collect(DISTINCT tag.name),replyCount=count(DISTINCT comment) GROUP BY friend
ORDER BY replyCount DESC, friend.id ASC
LIMIT 20
RETURN friend.id AS personId,
       friend.firstName AS personFirstName,
       friend.lastName AS personLastName,
       tagNames,
       replyCount

