// Q2. Recent messages by your friends
/*
:param [{ personId, maxDate }] => { RETURN
  10995116278009 AS personId,
  1287230400000 AS maxDate
}
*/
USE $graphName
MATCH (person:Person {id: $personId})<-[:KNOWS]->(friend:Person)<-[:HAS_CREATOR]-(message:Message WHERE message.creationDate < local_datetime($maxDate, "%Y-%m-%dT%H:%M:%S"))
ORDER BY message.creationDate DESC, message.id ASC
LIMIT 20
RETURN
    friend.id AS personId,
    friend.firstName AS personFirstName,
    friend.lastName AS personLastName,
    message.id AS postOrCommentId,
    COALESCE(message.content, message.imageFile) AS messageContent,
    message.creationDate AS postOrCommentCreationDate
