USE $graphName
INSERT NODE Post({id: $postId,
                  creationDate: localdatetime($creationDate),
                  locationIP: $locationIP,
                  browserUsed: $browserUsed,
                  language: $language,
                  content: $content,
                  imageFile: $imageFile,
                  extent: $length})