// IS6. Forum of a message
/*
:param messageId: 206158431836
 */
USE $graphName
MATCH (m:Message WHERE m.id = $messageId)-[:REPLY_OF]->{0,5}(p:Post)<-[:CONTAINER_OF]-(f:Forum)-[:HAS_MODERATOR]->(moderator:Person)
RETURN
  f.id AS forumId,
  f.title AS forumTitle,
  moderator.id AS moderatorId,
  moderator.firstName AS moderatorFirstName,
  moderator.lastName AS moderatorLastName
