// IS4. Content of a message
/*
:param messageId: 206158431836
 */
USE $graphName
MATCH (m:Message WHERE m.id = $messageId)
RETURN
   m.creationDate as messageCreationDate,
   CASE WHEN m.content <> ""
        THEN m.content
        ELSE m.imageFile
   END AS messageContent
