// Q13. Single shortest path
/*
:param [{ person1Id, person2Id }] => { RETURN
  8796093022390 AS person1Id,
  8796093022357 AS person2Id
}
*/
USE $graphName
MATCH (s:Person)
OPTIONAL MATCH (s:Person)-[e:KNOWS]->(t:Person)
RETURN toGraph(s, toUndirected(e), t) AS g GROUP BY ()
NEXT
MATCH (person1:Person{id: $person1Id}), (person2:Person{id: $person2Id})
RETURN g, element_id(person1) AS src_id, element_id(person2) AS dst_id
NEXT
CALL algo.bfs(g, src_id)
FILTER node_id = dst_id
RETURN distance as shortestPathLength
