// IS3. Friends of a person
/*
:param personId: 10995116277794
 */
USE $graphName
MATCH (n:Person WHERE n.id = $personId)<-[r:KNOWS]->(friend:Person)
ORDER BY
  r.creationDate DESC,
  friend.id ASC
RETURN
  friend.id AS personId,
  friend.firstName AS firstName,
  friend.lastName AS lastName,
  r.creationDate AS friendshipCreationDate