// Q9. Recent messages by friends or friends of friends
/*
:param [{ personId, maxDate }] => { RETURN
  4398046511268 AS personId,
  1289908800000 AS maxDate
}
*/
USE $graphName
MATCH (root:Person {id: $personId })<-[:KNOWS]->{1,2}(friend:Person)
WHERE friend <> root
RETURN DISTINCT friend
NEXT
USE $graphName
    MATCH (message:Message WHERE message.creationDate < localdatetime($maxDate))-[:HAS_CREATOR]->(friend:Person)
ORDER BY
  message.creationDate DESC,
  message.id ASC
LIMIT 20
RETURN
  friend.id AS personId,
  friend.firstName AS personFirstName,
  friend.lastName AS personLastName,
  message.id AS commentOrPostId,
  coalesce(message.content,message.imageFile) AS commentOrPostContent,
  message.creationDate AS commentOrPostCreationDate

