// Q5. New groups
/*
:param [{ personId, minDate }] => { RETURN
  6597069766734 AS personId,
  1288612800000 AS minDate
}
*/
CONFIGS optimizer_rules = "enhanced_column_pruner=on"
USE $graphName
MATCH (person:Person {id : $personId})<-[:KNOWS]->{1,2}(otherPerson:Person)
    WHERE person <> otherPerson
RETURN DISTINCT otherPerson
NEXT USE $graphName
MATCH (otherPerson:Person)<-[membership:HAS_MEMBER WHERE membership.joinDate > local_datetime($minDate, "%Y-%m-%dT%H:%M:%S")]-(forum:Forum)
OPTIONAL MATCH (otherPerson:Person)<-[:HAS_CREATOR]-(post:Post)<-[:CONTAINER_OF]-(forum:Forum)
RETURN count(post) AS postCount, forum GROUP BY forum
NEXT USE $graphName
ORDER BY postCount DESC, forum.id ASC
LIMIT 20
RETURN
  forum.title AS forumName,
  postCount
