USE $graphName
INSERT NODE Post({id: $postId,
                  creationDate: local_datetime($creationDate, "%Y-%m-%dT%H:%M:%S"),
                  locationIP: $locationIP,
                  browserUsed: $browserUsed,
                  language: $language,
                  content: $content,
                  imageFile: $imageFile,
                  extent: $length})