// Q7. Recent likers
/*
:param personId: 4398046511268
*/
USE $graphName
MATCH (person:Person {id: $personId})<-[:HAS_CREATOR]-(message:Message)<-[likes:LIKES]-(liker:Person)
  LET likeTime=likes.creationDate
  ORDER BY likeTime DESC, message.id ASC
  AGGREGATE latestLikeMsgs=collect(message), latestLikeTimes=collect(likeTime) GROUP BY liker, person
  let latestLikeMsg=head(latestLikeMsgs), latestLikeTime=head(latestLikeTimes)
ORDER BY
  latestLikeTime DESC,
  liker.id ASC
LIMIT 20
RETURN
  liker.id AS personId,
  liker.firstName AS personFirstName,
  liker.lastName AS personLastName,
  latestLikeTime AS likeCreationDate,
  latestLikeMsg.id AS messageId,
  CASE WHEN latestLikeMsg.content <>"" THEN latestLikeMsg.content  ELSE latestLikeMsg.imageFile END AS messageContent,
  latestLikeMsg.creationDate AS minutesLatency,
  NOT EXISTS ((liker:Person)<-[:KNOWS]->(person:Person{id: $personId}))  AS isNew
