// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	common "github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/handler/common"
	config "github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/handler/config"
	health "github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/handler/health"
	storage "github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/handler/storage"
	"github.com/vesoft-inc/nebula-ng-tools/agent/api/agent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/common/download",
				Handler: common.DownloadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/common/execute",
				Handler: common.CmdExecuteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/common/execute-async",
				Handler: common.CmdExecuteAsyncHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/common/execute-async/:cmdId",
				Handler: common.GetCmdExecuteAsyncStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/common/upload",
				Handler: common.UploadFileHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/component-config",
				Handler: config.GetComponentConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/component-config",
				Handler: config.SetComponentConfigHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.GetHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage/hdfs/download",
				Handler: storage.HdfsDownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage/hdfs/upload",
				Handler: storage.HdfsUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage/s3/download",
				Handler: storage.S3DownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage/s3/upload",
				Handler: storage.S3UploadHandler(serverCtx),
			},
		},
	)
}
