endpoint=172.31.34.92:9669,172.31.36.112:9669
user=root
password=Yueshu123

graphName=sf10
requestTimeout=0
# (CONFIG) size of the session pool
maxSessionSize=10
# (CONFIG) unit/second. if the session cannot be obtained after maxSessionWaitTime, an error will be reported
maxSessionWaitTime=20
intervalTimeBetweenRetrys=1
retryTimes=10
queryDir=/home/ubuntu/audit/ldbc_snb_interactive_implementations/nebula/queries
printQueryNames=false
printQueryStrings=false
printQueryResults=false

status=1
thread_count=1
name=LDBC-SNB
results_log=false
time_unit=MILLISECONDS
time_compression_ratio=0.2
peer_identifiers=
workload_statistics=false
spinner_wait_duration=1
help=false
ignore_scheduled_start_times=true
max_conn_size=500

workload=org.ldbcouncil.snb.driver.workloads.interactive.LdbcSnbInteractiveWorkload
db=org.ldbcouncil.snb.impls.workloads.nebula.interactive.NebulaInteractiveDb
operation_count=1000

mode=validate_database

#validate_workload=true
validate_database=/home/ubuntu/audit/ldbc_snb_interactive_implementations/nebula/conf/validation_params.csv
ldbc.snb.interactive.parameters_dir=/home/ubuntu/data-sets-surf-repository/substitution_parameters-sf10
ldbc.snb.interactive.short_read_dissipation=0.2

# Supported scale factors are 0.1, 0.3, 1, 3, 10, 30, 100, 300, 1000
ldbc.snb.interactive.scale_factor=10

#create_validation_parameters=validation_params.csv|10

ldbc.snb.interactive.LdbcQuery1_freq=1
ldbc.snb.interactive.LdbcQuery2_freq=1
ldbc.snb.interactive.LdbcQuery3_freq=1
ldbc.snb.interactive.LdbcQuery4_freq=1
ldbc.snb.interactive.LdbcQuery5_freq=1
ldbc.snb.interactive.LdbcQuery6_freq=1
ldbc.snb.interactive.LdbcQuery7_freq=1
ldbc.snb.interactive.LdbcQuery8_freq=1
ldbc.snb.interactive.LdbcQuery9_freq=1
ldbc.snb.interactive.LdbcQuery10_freq=1
ldbc.snb.interactive.LdbcQuery11_freq=1
ldbc.snb.interactive.LdbcQuery12_freq=1
ldbc.snb.interactive.LdbcQuery13_freq=1
ldbc.snb.interactive.LdbcQuery14_freq=1


ldbc.snb.interactive.LdbcQuery1_enable=true
ldbc.snb.interactive.LdbcQuery2_enable=true
ldbc.snb.interactive.LdbcQuery3_enable=true
ldbc.snb.interactive.LdbcQuery4_enable=true
ldbc.snb.interactive.LdbcQuery5_enable=true
ldbc.snb.interactive.LdbcQuery6_enable=true
ldbc.snb.interactive.LdbcQuery7_enable=true
ldbc.snb.interactive.LdbcQuery8_enable=true
ldbc.snb.interactive.LdbcQuery9_enable=true
ldbc.snb.interactive.LdbcQuery10_enable=true
ldbc.snb.interactive.LdbcQuery11_enable=true
ldbc.snb.interactive.LdbcQuery12_enable=true
ldbc.snb.interactive.LdbcQuery13_enable=false
ldbc.snb.interactive.LdbcQuery14_enable=false

ldbc.snb.interactive.LdbcShortQuery1PersonProfile_enable=true
ldbc.snb.interactive.LdbcShortQuery2PersonPosts_enable=true
ldbc.snb.interactive.LdbcShortQuery3PersonFriends_enable=true
ldbc.snb.interactive.LdbcShortQuery4MessageContent_enable=true
ldbc.snb.interactive.LdbcShortQuery5MessageCreator_enable=true
ldbc.snb.interactive.LdbcShortQuery6MessageForum_enable=true
ldbc.snb.interactive.LdbcShortQuery7MessageReplies_enable=true

ldbc.snb.interactive.LdbcUpdate1AddPerson_enable=true
ldbc.snb.interactive.LdbcUpdate2AddPostLike_enable=true
ldbc.snb.interactive.LdbcUpdate3AddCommentLike_enable=true
ldbc.snb.interactive.LdbcUpdate4AddForum_enable=true
ldbc.snb.interactive.LdbcUpdate5AddForumMembership_enable=true
ldbc.snb.interactive.LdbcUpdate6AddPost_enable=true
ldbc.snb.interactive.LdbcUpdate7AddComment_enable=true
ldbc.snb.interactive.LdbcUpdate8AddFriendship_enable=true