nebulaMetad:
  credentialSecret: "nebula"
  replicas: 3
  image: reg.vesoft-inc.com/vesoft-ng/nebula-metad
  version: nightly
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  dataVolume:
    storage: "5Gi"
  logVolume:
    enable: true
    storage: "1Gi"
  storageClassName: local-path
  env: []
  config: {}
  nodeSelector: {}
  affinity: {}
  enableAutoBalance: false
  podLabels: {}
  podAnnotations: {}
  tolerations: []
  readinessProbe: {}
  livenessProbe: {}
  initContainers: []
  sidecarContainers: []
  volumes: []
  volumeMounts: []

  enablePVReclaim: false
  imagePullPolicy: Always
  imagePullSecrets: []
  schedulerName: default-scheduler # nebula-scheduler
  topologySpreadConstraints:
  - topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: "ScheduleAnyway"
  nameOverride: ""
  fullnameOverride: ""

  
  
  
  
  