// Autogenerated by Thrift Compiler (facebook)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// @generated

package graph

import (
	"bytes"
	"context"
	"sync"
	"fmt"
	thrift "github.com/facebook/fbthrift/thrift/lib/go/thrift"
  nebula0 "github.com/vesoft-inc/nebula-ng-tools/golang/pkg/generated_code/v5.0.0/nebula"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = sync.Mutex{}
var _ = bytes.Equal
var _ = context.Background

var _ = nebula0.GoUnusedProtection__
var GoUnusedProtection__ int;

type ProfilingStats = *XProfilingStats_

func ProfilingStatsPtr(v ProfilingStats) *ProfilingStats { return &v }

func NewProfilingStats() ProfilingStats { return NewXProfilingStats_() }

type Pair = *XPair_

func PairPtr(v Pair) *Pair { return &v }

func NewPair() Pair { return NewXPair_() }

type PlanNodeDescription = *XPlanNodeDescription_

func PlanNodeDescriptionPtr(v PlanNodeDescription) *PlanNodeDescription { return &v }

func NewPlanNodeDescription() PlanNodeDescription { return NewXPlanNodeDescription_() }

type PlanDescription = *XPlanDescription_

func PlanDescriptionPtr(v PlanDescription) *PlanDescription { return &v }

func NewPlanDescription() PlanDescription { return NewXPlanDescription_() }

type GQLStatus = *XGQLStatus_

func GQLStatusPtr(v GQLStatus) *GQLStatus { return &v }

func NewGQLStatus() GQLStatus { return NewXGQLStatus_() }

type ExecutionOutcome = *XExecutionOutcome_

func ExecutionOutcomePtr(v ExecutionOutcome) *ExecutionOutcome { return &v }

func NewExecutionOutcome() ExecutionOutcome { return NewXExecutionOutcome_() }

type ExecutionResponse = *XExecutionResponse_

func ExecutionResponsePtr(v ExecutionResponse) *ExecutionResponse { return &v }

func NewExecutionResponse() ExecutionResponse { return NewXExecutionResponse_() }

type AuthResponse = *XAuthResponse_

func AuthResponsePtr(v AuthResponse) *AuthResponse { return &v }

func NewAuthResponse() AuthResponse { return NewXAuthResponse_() }

// Attributes:
//  - Rows
//  - ExecDurationInUs
//  - TotalDurationInUs
//  - OtherStats
type XProfilingStats_ struct {
  Rows int64 `thrift:"rows,1" db:"rows" json:"rows"`
  ExecDurationInUs int64 `thrift:"exec_duration_in_us,2" db:"exec_duration_in_us" json:"exec_duration_in_us"`
  TotalDurationInUs int64 `thrift:"total_duration_in_us,3" db:"total_duration_in_us" json:"total_duration_in_us"`
  OtherStats map[string][]byte `thrift:"other_stats,4,optional" db:"other_stats" json:"other_stats,omitempty"`
}

func NewXProfilingStats_() *XProfilingStats_ {
  return &XProfilingStats_{}
}


func (p *XProfilingStats_) GetRows() int64 {
  return p.Rows
}

func (p *XProfilingStats_) GetExecDurationInUs() int64 {
  return p.ExecDurationInUs
}

func (p *XProfilingStats_) GetTotalDurationInUs() int64 {
  return p.TotalDurationInUs
}
var XProfilingStats__OtherStats_DEFAULT map[string][]byte

func (p *XProfilingStats_) GetOtherStats() map[string][]byte {
  return p.OtherStats
}
func (p *XProfilingStats_) IsSetOtherStats() bool {
  return p != nil && p.OtherStats != nil
}

type XProfilingStats_Builder struct {
  obj *XProfilingStats_
}

func NewXProfilingStats_Builder() *XProfilingStats_Builder{
  return &XProfilingStats_Builder{
    obj: NewXProfilingStats_(),
  }
}

func (p XProfilingStats_Builder) Emit() *XProfilingStats_{
  return &XProfilingStats_{
    Rows: p.obj.Rows,
    ExecDurationInUs: p.obj.ExecDurationInUs,
    TotalDurationInUs: p.obj.TotalDurationInUs,
    OtherStats: p.obj.OtherStats,
  }
}

func (x *XProfilingStats_Builder) Rows(rows int64) *XProfilingStats_Builder {
  x.obj.Rows = rows
  return x
}

func (x *XProfilingStats_Builder) ExecDurationInUs(execDurationInUs int64) *XProfilingStats_Builder {
  x.obj.ExecDurationInUs = execDurationInUs
  return x
}

func (x *XProfilingStats_Builder) TotalDurationInUs(totalDurationInUs int64) *XProfilingStats_Builder {
  x.obj.TotalDurationInUs = totalDurationInUs
  return x
}

func (x *XProfilingStats_Builder) OtherStats(otherStats map[string][]byte) *XProfilingStats_Builder {
  x.obj.OtherStats = otherStats
  return x
}

func (x *XProfilingStats_) SetRows(rows int64) *XProfilingStats_ {
  x.Rows = rows
  return x
}

func (x *XProfilingStats_) SetExecDurationInUs(execDurationInUs int64) *XProfilingStats_ {
  x.ExecDurationInUs = execDurationInUs
  return x
}

func (x *XProfilingStats_) SetTotalDurationInUs(totalDurationInUs int64) *XProfilingStats_ {
  x.TotalDurationInUs = totalDurationInUs
  return x
}

func (x *XProfilingStats_) SetOtherStats(otherStats map[string][]byte) *XProfilingStats_ {
  x.OtherStats = otherStats
  return x
}

func (p *XProfilingStats_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XProfilingStats_)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Rows = v
  }
  return nil
}

func (p *XProfilingStats_)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.ExecDurationInUs = v
  }
  return nil
}

func (p *XProfilingStats_)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.TotalDurationInUs = v
  }
  return nil
}

func (p *XProfilingStats_)  ReadField4(iprot thrift.Protocol) error {
  _, _, size, err := iprot.ReadMapBegin()
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[string][]byte, size)
  p.OtherStats =  tMap
  for i := 0; i < size; i ++ {
    var _key1 string
    if v, err := iprot.ReadString(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _key1 = v
    }
    var _val2 []byte
    if v, err := iprot.ReadBinary(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _val2 = v
    }
    p.OtherStats[_key1] = _val2
  }
  if err := iprot.ReadMapEnd(); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *XProfilingStats_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_ProfilingStats_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XProfilingStats_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("rows", thrift.I64, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:rows: ", p), err) }
  if err := oprot.WriteI64(int64(p.Rows)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.rows (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:rows: ", p), err) }
  return err
}

func (p *XProfilingStats_) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("exec_duration_in_us", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:exec_duration_in_us: ", p), err) }
  if err := oprot.WriteI64(int64(p.ExecDurationInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.exec_duration_in_us (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:exec_duration_in_us: ", p), err) }
  return err
}

func (p *XProfilingStats_) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("total_duration_in_us", thrift.I64, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:total_duration_in_us: ", p), err) }
  if err := oprot.WriteI64(int64(p.TotalDurationInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.total_duration_in_us (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:total_duration_in_us: ", p), err) }
  return err
}

func (p *XProfilingStats_) writeField4(oprot thrift.Protocol) (err error) {
  if p.IsSetOtherStats() {
    if err := oprot.WriteFieldBegin("other_stats", thrift.MAP, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:other_stats: ", p), err) }
    if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.OtherStats)); err != nil {
      return thrift.PrependError("error writing map begin: ", err)
    }
    for k, v := range p.OtherStats {
      if err := oprot.WriteString(string(k)); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
      if err := oprot.WriteBinary(v); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    }
    if err := oprot.WriteMapEnd(); err != nil {
      return thrift.PrependError("error writing map end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:other_stats: ", p), err) }
  }
  return err
}

func (p *XProfilingStats_) String() string {
  if p == nil {
    return "<nil>"
  }

  rowsVal := fmt.Sprintf("%v", p.Rows)
  execDurationInUsVal := fmt.Sprintf("%v", p.ExecDurationInUs)
  totalDurationInUsVal := fmt.Sprintf("%v", p.TotalDurationInUs)
  otherStatsVal := fmt.Sprintf("%v", p.OtherStats)
  return fmt.Sprintf("XProfilingStats_({Rows:%s ExecDurationInUs:%s TotalDurationInUs:%s OtherStats:%s})", rowsVal, execDurationInUsVal, totalDurationInUsVal, otherStatsVal)
}

// Attributes:
//  - Key
//  - Value
type XPair_ struct {
  Key []byte `thrift:"key,1" db:"key" json:"key"`
  Value []byte `thrift:"value,2" db:"value" json:"value"`
}

func NewXPair_() *XPair_ {
  return &XPair_{}
}


func (p *XPair_) GetKey() []byte {
  return p.Key
}

func (p *XPair_) GetValue() []byte {
  return p.Value
}
type XPair_Builder struct {
  obj *XPair_
}

func NewXPair_Builder() *XPair_Builder{
  return &XPair_Builder{
    obj: NewXPair_(),
  }
}

func (p XPair_Builder) Emit() *XPair_{
  return &XPair_{
    Key: p.obj.Key,
    Value: p.obj.Value,
  }
}

func (x *XPair_Builder) Key(key []byte) *XPair_Builder {
  x.obj.Key = key
  return x
}

func (x *XPair_Builder) Value(value []byte) *XPair_Builder {
  x.obj.Value = value
  return x
}

func (x *XPair_) SetKey(key []byte) *XPair_ {
  x.Key = key
  return x
}

func (x *XPair_) SetValue(value []byte) *XPair_ {
  x.Value = value
  return x
}

func (p *XPair_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XPair_)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Key = v
  }
  return nil
}

func (p *XPair_)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Value = v
  }
  return nil
}

func (p *XPair_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_Pair_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XPair_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("key", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:key: ", p), err) }
  if err := oprot.WriteBinary(p.Key); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.key (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:key: ", p), err) }
  return err
}

func (p *XPair_) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("value", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:value: ", p), err) }
  if err := oprot.WriteBinary(p.Value); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.value (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:value: ", p), err) }
  return err
}

func (p *XPair_) String() string {
  if p == nil {
    return "<nil>"
  }

  keyVal := fmt.Sprintf("%v", p.Key)
  valueVal := fmt.Sprintf("%v", p.Value)
  return fmt.Sprintf("XPair_({Key:%s Value:%s})", keyVal, valueVal)
}

// Attributes:
//  - Name
//  - Id
//  - OutputVar
//  - Description
//  - Profiles
//  - Dependencies
type XPlanNodeDescription_ struct {
  Name []byte `thrift:"name,1" db:"name" json:"name"`
  Id int64 `thrift:"id,2" db:"id" json:"id"`
  OutputVar []byte `thrift:"output_var,3" db:"output_var" json:"output_var"`
  Description []Pair `thrift:"description,4,optional" db:"description" json:"description,omitempty"`
  Profiles []ProfilingStats `thrift:"profiles,5,optional" db:"profiles" json:"profiles,omitempty"`
  Dependencies []int64 `thrift:"dependencies,6,optional" db:"dependencies" json:"dependencies,omitempty"`
}

func NewXPlanNodeDescription_() *XPlanNodeDescription_ {
  return &XPlanNodeDescription_{}
}


func (p *XPlanNodeDescription_) GetName() []byte {
  return p.Name
}

func (p *XPlanNodeDescription_) GetId() int64 {
  return p.Id
}

func (p *XPlanNodeDescription_) GetOutputVar() []byte {
  return p.OutputVar
}
var XPlanNodeDescription__Description_DEFAULT []*Pair

func (p *XPlanNodeDescription_) GetDescription() []Pair {
  return p.Description
}
var XPlanNodeDescription__Profiles_DEFAULT []*ProfilingStats

func (p *XPlanNodeDescription_) GetProfiles() []ProfilingStats {
  return p.Profiles
}
var XPlanNodeDescription__Dependencies_DEFAULT []int64

func (p *XPlanNodeDescription_) GetDependencies() []int64 {
  return p.Dependencies
}
func (p *XPlanNodeDescription_) IsSetDescription() bool {
  return p != nil && p.Description != nil
}

func (p *XPlanNodeDescription_) IsSetProfiles() bool {
  return p != nil && p.Profiles != nil
}

func (p *XPlanNodeDescription_) IsSetDependencies() bool {
  return p != nil && p.Dependencies != nil
}

type XPlanNodeDescription_Builder struct {
  obj *XPlanNodeDescription_
}

func NewXPlanNodeDescription_Builder() *XPlanNodeDescription_Builder{
  return &XPlanNodeDescription_Builder{
    obj: NewXPlanNodeDescription_(),
  }
}

func (p XPlanNodeDescription_Builder) Emit() *XPlanNodeDescription_{
  return &XPlanNodeDescription_{
    Name: p.obj.Name,
    Id: p.obj.Id,
    OutputVar: p.obj.OutputVar,
    Description: p.obj.Description,
    Profiles: p.obj.Profiles,
    Dependencies: p.obj.Dependencies,
  }
}

func (x *XPlanNodeDescription_Builder) Name(name []byte) *XPlanNodeDescription_Builder {
  x.obj.Name = name
  return x
}

func (x *XPlanNodeDescription_Builder) Id(id int64) *XPlanNodeDescription_Builder {
  x.obj.Id = id
  return x
}

func (x *XPlanNodeDescription_Builder) OutputVar(outputVar []byte) *XPlanNodeDescription_Builder {
  x.obj.OutputVar = outputVar
  return x
}

func (x *XPlanNodeDescription_Builder) Description(description []Pair) *XPlanNodeDescription_Builder {
  x.obj.Description = description
  return x
}

func (x *XPlanNodeDescription_Builder) Profiles(profiles []ProfilingStats) *XPlanNodeDescription_Builder {
  x.obj.Profiles = profiles
  return x
}

func (x *XPlanNodeDescription_Builder) Dependencies(dependencies []int64) *XPlanNodeDescription_Builder {
  x.obj.Dependencies = dependencies
  return x
}

func (x *XPlanNodeDescription_) SetName(name []byte) *XPlanNodeDescription_ {
  x.Name = name
  return x
}

func (x *XPlanNodeDescription_) SetId(id int64) *XPlanNodeDescription_ {
  x.Id = id
  return x
}

func (x *XPlanNodeDescription_) SetOutputVar(outputVar []byte) *XPlanNodeDescription_ {
  x.OutputVar = outputVar
  return x
}

func (x *XPlanNodeDescription_) SetDescription(description []Pair) *XPlanNodeDescription_ {
  x.Description = description
  return x
}

func (x *XPlanNodeDescription_) SetProfiles(profiles []ProfilingStats) *XPlanNodeDescription_ {
  x.Profiles = profiles
  return x
}

func (x *XPlanNodeDescription_) SetDependencies(dependencies []int64) *XPlanNodeDescription_ {
  x.Dependencies = dependencies
  return x
}

func (p *XPlanNodeDescription_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    case 5:
      if err := p.ReadField5(iprot); err != nil {
        return err
      }
    case 6:
      if err := p.ReadField6(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XPlanNodeDescription_)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Name = v
  }
  return nil
}

func (p *XPlanNodeDescription_)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Id = v
  }
  return nil
}

func (p *XPlanNodeDescription_)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.OutputVar = v
  }
  return nil
}

func (p *XPlanNodeDescription_)  ReadField4(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]Pair, 0, size)
  p.Description =  tSlice
  for i := 0; i < size; i ++ {
    _elem3 := NewPair()
    if err := _elem3.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem3), err)
    }
    p.Description = append(p.Description, _elem3)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *XPlanNodeDescription_)  ReadField5(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]ProfilingStats, 0, size)
  p.Profiles =  tSlice
  for i := 0; i < size; i ++ {
    _elem4 := NewProfilingStats()
    if err := _elem4.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem4), err)
    }
    p.Profiles = append(p.Profiles, _elem4)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *XPlanNodeDescription_)  ReadField6(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]int64, 0, size)
  p.Dependencies =  tSlice
  for i := 0; i < size; i ++ {
    var _elem5 int64
    if v, err := iprot.ReadI64(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _elem5 = v
    }
    p.Dependencies = append(p.Dependencies, _elem5)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *XPlanNodeDescription_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_PlanNodeDescription_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := p.writeField5(oprot); err != nil { return err }
  if err := p.writeField6(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XPlanNodeDescription_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("name", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:name: ", p), err) }
  if err := oprot.WriteBinary(p.Name); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.name (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:name: ", p), err) }
  return err
}

func (p *XPlanNodeDescription_) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("id", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:id: ", p), err) }
  if err := oprot.WriteI64(int64(p.Id)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.id (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:id: ", p), err) }
  return err
}

func (p *XPlanNodeDescription_) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("output_var", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:output_var: ", p), err) }
  if err := oprot.WriteBinary(p.OutputVar); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.output_var (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:output_var: ", p), err) }
  return err
}

func (p *XPlanNodeDescription_) writeField4(oprot thrift.Protocol) (err error) {
  if p.IsSetDescription() {
    if err := oprot.WriteFieldBegin("description", thrift.LIST, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:description: ", p), err) }
    if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Description)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Description {
      if err := v.Write(oprot); err != nil {
        return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
      }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:description: ", p), err) }
  }
  return err
}

func (p *XPlanNodeDescription_) writeField5(oprot thrift.Protocol) (err error) {
  if p.IsSetProfiles() {
    if err := oprot.WriteFieldBegin("profiles", thrift.LIST, 5); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:profiles: ", p), err) }
    if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Profiles)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Profiles {
      if err := v.Write(oprot); err != nil {
        return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
      }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 5:profiles: ", p), err) }
  }
  return err
}

func (p *XPlanNodeDescription_) writeField6(oprot thrift.Protocol) (err error) {
  if p.IsSetDependencies() {
    if err := oprot.WriteFieldBegin("dependencies", thrift.LIST, 6); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:dependencies: ", p), err) }
    if err := oprot.WriteListBegin(thrift.I64, len(p.Dependencies)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Dependencies {
      if err := oprot.WriteI64(int64(v)); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 6:dependencies: ", p), err) }
  }
  return err
}

func (p *XPlanNodeDescription_) String() string {
  if p == nil {
    return "<nil>"
  }

  nameVal := fmt.Sprintf("%v", p.Name)
  idVal := fmt.Sprintf("%v", p.Id)
  outputVarVal := fmt.Sprintf("%v", p.OutputVar)
  descriptionVal := fmt.Sprintf("%v", p.Description)
  profilesVal := fmt.Sprintf("%v", p.Profiles)
  dependenciesVal := fmt.Sprintf("%v", p.Dependencies)
  return fmt.Sprintf("XPlanNodeDescription_({Name:%s Id:%s OutputVar:%s Description:%s Profiles:%s Dependencies:%s})", nameVal, idVal, outputVarVal, descriptionVal, profilesVal, dependenciesVal)
}

// Attributes:
//  - PlanNodeDescs
//  - NodeIndexMap
//  - Format
//  - OptimizeTimeInUs
type XPlanDescription_ struct {
  PlanNodeDescs []PlanNodeDescription `thrift:"plan_node_descs,1" db:"plan_node_descs" json:"plan_node_descs"`
  NodeIndexMap map[int64]int64 `thrift:"node_index_map,2" db:"node_index_map" json:"node_index_map"`
  Format []byte `thrift:"format,3" db:"format" json:"format"`
  OptimizeTimeInUs int32 `thrift:"optimize_time_in_us,4" db:"optimize_time_in_us" json:"optimize_time_in_us"`
}

func NewXPlanDescription_() *XPlanDescription_ {
  return &XPlanDescription_{}
}


func (p *XPlanDescription_) GetPlanNodeDescs() []PlanNodeDescription {
  return p.PlanNodeDescs
}

func (p *XPlanDescription_) GetNodeIndexMap() map[int64]int64 {
  return p.NodeIndexMap
}

func (p *XPlanDescription_) GetFormat() []byte {
  return p.Format
}

func (p *XPlanDescription_) GetOptimizeTimeInUs() int32 {
  return p.OptimizeTimeInUs
}
type XPlanDescription_Builder struct {
  obj *XPlanDescription_
}

func NewXPlanDescription_Builder() *XPlanDescription_Builder{
  return &XPlanDescription_Builder{
    obj: NewXPlanDescription_(),
  }
}

func (p XPlanDescription_Builder) Emit() *XPlanDescription_{
  return &XPlanDescription_{
    PlanNodeDescs: p.obj.PlanNodeDescs,
    NodeIndexMap: p.obj.NodeIndexMap,
    Format: p.obj.Format,
    OptimizeTimeInUs: p.obj.OptimizeTimeInUs,
  }
}

func (x *XPlanDescription_Builder) PlanNodeDescs(planNodeDescs []PlanNodeDescription) *XPlanDescription_Builder {
  x.obj.PlanNodeDescs = planNodeDescs
  return x
}

func (x *XPlanDescription_Builder) NodeIndexMap(nodeIndexMap map[int64]int64) *XPlanDescription_Builder {
  x.obj.NodeIndexMap = nodeIndexMap
  return x
}

func (x *XPlanDescription_Builder) Format(format []byte) *XPlanDescription_Builder {
  x.obj.Format = format
  return x
}

func (x *XPlanDescription_Builder) OptimizeTimeInUs(optimizeTimeInUs int32) *XPlanDescription_Builder {
  x.obj.OptimizeTimeInUs = optimizeTimeInUs
  return x
}

func (x *XPlanDescription_) SetPlanNodeDescs(planNodeDescs []PlanNodeDescription) *XPlanDescription_ {
  x.PlanNodeDescs = planNodeDescs
  return x
}

func (x *XPlanDescription_) SetNodeIndexMap(nodeIndexMap map[int64]int64) *XPlanDescription_ {
  x.NodeIndexMap = nodeIndexMap
  return x
}

func (x *XPlanDescription_) SetFormat(format []byte) *XPlanDescription_ {
  x.Format = format
  return x
}

func (x *XPlanDescription_) SetOptimizeTimeInUs(optimizeTimeInUs int32) *XPlanDescription_ {
  x.OptimizeTimeInUs = optimizeTimeInUs
  return x
}

func (p *XPlanDescription_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XPlanDescription_)  ReadField1(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]PlanNodeDescription, 0, size)
  p.PlanNodeDescs =  tSlice
  for i := 0; i < size; i ++ {
    _elem6 := NewPlanNodeDescription()
    if err := _elem6.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem6), err)
    }
    p.PlanNodeDescs = append(p.PlanNodeDescs, _elem6)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *XPlanDescription_)  ReadField2(iprot thrift.Protocol) error {
  _, _, size, err := iprot.ReadMapBegin()
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[int64]int64, size)
  p.NodeIndexMap =  tMap
  for i := 0; i < size; i ++ {
    var _key7 int64
    if v, err := iprot.ReadI64(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _key7 = v
    }
    var _val8 int64
    if v, err := iprot.ReadI64(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _val8 = v
    }
    p.NodeIndexMap[_key7] = _val8
  }
  if err := iprot.ReadMapEnd(); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *XPlanDescription_)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.Format = v
  }
  return nil
}

func (p *XPlanDescription_)  ReadField4(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI32(); err != nil {
    return thrift.PrependError("error reading field 4: ", err)
  } else {
    p.OptimizeTimeInUs = v
  }
  return nil
}

func (p *XPlanDescription_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_PlanDescription_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XPlanDescription_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("plan_node_descs", thrift.LIST, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:plan_node_descs: ", p), err) }
  if err := oprot.WriteListBegin(thrift.STRUCT, len(p.PlanNodeDescs)); err != nil {
    return thrift.PrependError("error writing list begin: ", err)
  }
  for _, v := range p.PlanNodeDescs {
    if err := v.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
    }
  }
  if err := oprot.WriteListEnd(); err != nil {
    return thrift.PrependError("error writing list end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:plan_node_descs: ", p), err) }
  return err
}

func (p *XPlanDescription_) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("node_index_map", thrift.MAP, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:node_index_map: ", p), err) }
  if err := oprot.WriteMapBegin(thrift.I64, thrift.I64, len(p.NodeIndexMap)); err != nil {
    return thrift.PrependError("error writing map begin: ", err)
  }
  for k, v := range p.NodeIndexMap {
    if err := oprot.WriteI64(int64(k)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    if err := oprot.WriteI64(int64(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteMapEnd(); err != nil {
    return thrift.PrependError("error writing map end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:node_index_map: ", p), err) }
  return err
}

func (p *XPlanDescription_) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("format", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:format: ", p), err) }
  if err := oprot.WriteBinary(p.Format); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.format (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:format: ", p), err) }
  return err
}

func (p *XPlanDescription_) writeField4(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("optimize_time_in_us", thrift.I32, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:optimize_time_in_us: ", p), err) }
  if err := oprot.WriteI32(int32(p.OptimizeTimeInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.optimize_time_in_us (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:optimize_time_in_us: ", p), err) }
  return err
}

func (p *XPlanDescription_) String() string {
  if p == nil {
    return "<nil>"
  }

  planNodeDescsVal := fmt.Sprintf("%v", p.PlanNodeDescs)
  nodeIndexMapVal := fmt.Sprintf("%v", p.NodeIndexMap)
  formatVal := fmt.Sprintf("%v", p.Format)
  optimizeTimeInUsVal := fmt.Sprintf("%v", p.OptimizeTimeInUs)
  return fmt.Sprintf("XPlanDescription_({PlanNodeDescs:%s NodeIndexMap:%s Format:%s OptimizeTimeInUs:%s})", planNodeDescsVal, nodeIndexMapVal, formatVal, optimizeTimeInUsVal)
}

// Attributes:
//  - Status
type XGQLStatus_ struct {
  Status []byte `thrift:"status,1" db:"status" json:"status"`
}

func NewXGQLStatus_() *XGQLStatus_ {
  return &XGQLStatus_{}
}


func (p *XGQLStatus_) GetStatus() []byte {
  return p.Status
}
type XGQLStatus_Builder struct {
  obj *XGQLStatus_
}

func NewXGQLStatus_Builder() *XGQLStatus_Builder{
  return &XGQLStatus_Builder{
    obj: NewXGQLStatus_(),
  }
}

func (p XGQLStatus_Builder) Emit() *XGQLStatus_{
  return &XGQLStatus_{
    Status: p.obj.Status,
  }
}

func (x *XGQLStatus_Builder) Status(status []byte) *XGQLStatus_Builder {
  x.obj.Status = status
  return x
}

func (x *XGQLStatus_) SetStatus(status []byte) *XGQLStatus_ {
  x.Status = status
  return x
}

func (p *XGQLStatus_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XGQLStatus_)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Status = v
  }
  return nil
}

func (p *XGQLStatus_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_GQLStatus_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XGQLStatus_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("status", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:status: ", p), err) }
  if err := oprot.WriteBinary(p.Status); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.status (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:status: ", p), err) }
  return err
}

func (p *XGQLStatus_) String() string {
  if p == nil {
    return "<nil>"
  }

  statusVal := fmt.Sprintf("%v", p.Status)
  return fmt.Sprintf("XGQLStatus_({Status:%s})", statusVal)
}

// Attributes:
//  - GqlStatus
//  - Result_
//  - PlanDesc
type XExecutionOutcome_ struct {
  GqlStatus GQLStatus `thrift:"gqlStatus,1" db:"gqlStatus" json:"gqlStatus"`
  Result_ nebula0.BindingTable `thrift:"result,2,optional" db:"result" json:"result,omitempty"`
  PlanDesc PlanDescription `thrift:"plan_desc,3,optional" db:"plan_desc" json:"plan_desc,omitempty"`
}

func NewXExecutionOutcome_() *XExecutionOutcome_ {
  return &XExecutionOutcome_{
    GqlStatus: NewGQLStatus(),
  }
}

var XExecutionOutcome__GqlStatus_DEFAULT GQLStatus
func (p *XExecutionOutcome_) GetGqlStatus() GQLStatus {
  if !p.IsSetGqlStatus() {
    return XExecutionOutcome__GqlStatus_DEFAULT
  }
  return p.GqlStatus
}
var XExecutionOutcome__Result__DEFAULT nebula0.BindingTable
func (p *XExecutionOutcome_) GetResult_() nebula0.BindingTable {
  if !p.IsSetResult_() {
    return XExecutionOutcome__Result__DEFAULT
  }
  return p.Result_
}
var XExecutionOutcome__PlanDesc_DEFAULT PlanDescription
func (p *XExecutionOutcome_) GetPlanDesc() PlanDescription {
  if !p.IsSetPlanDesc() {
    return XExecutionOutcome__PlanDesc_DEFAULT
  }
  return p.PlanDesc
}
func (p *XExecutionOutcome_) IsSetGqlStatus() bool {
  return p != nil && p.GqlStatus != nil
}

func (p *XExecutionOutcome_) IsSetResult_() bool {
  return p != nil && p.Result_ != nil
}

func (p *XExecutionOutcome_) IsSetPlanDesc() bool {
  return p != nil && p.PlanDesc != nil
}

type XExecutionOutcome_Builder struct {
  obj *XExecutionOutcome_
}

func NewXExecutionOutcome_Builder() *XExecutionOutcome_Builder{
  return &XExecutionOutcome_Builder{
    obj: NewXExecutionOutcome_(),
  }
}

func (p XExecutionOutcome_Builder) Emit() *XExecutionOutcome_{
  return &XExecutionOutcome_{
    GqlStatus: p.obj.GqlStatus,
    Result_: p.obj.Result_,
    PlanDesc: p.obj.PlanDesc,
  }
}

func (x *XExecutionOutcome_Builder) GqlStatus(gqlStatus GQLStatus) *XExecutionOutcome_Builder {
  x.obj.GqlStatus = gqlStatus
  return x
}

func (x *XExecutionOutcome_Builder) Result_(result nebula0.BindingTable) *XExecutionOutcome_Builder {
  x.obj.Result_ = result
  return x
}

func (x *XExecutionOutcome_Builder) PlanDesc(planDesc PlanDescription) *XExecutionOutcome_Builder {
  x.obj.PlanDesc = planDesc
  return x
}

func (x *XExecutionOutcome_) SetGqlStatus(gqlStatus GQLStatus) *XExecutionOutcome_ {
  x.GqlStatus = gqlStatus
  return x
}

func (x *XExecutionOutcome_) SetResult_(result nebula0.BindingTable) *XExecutionOutcome_ {
  x.Result_ = result
  return x
}

func (x *XExecutionOutcome_) SetPlanDesc(planDesc PlanDescription) *XExecutionOutcome_ {
  x.PlanDesc = planDesc
  return x
}

func (p *XExecutionOutcome_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XExecutionOutcome_)  ReadField1(iprot thrift.Protocol) error {
  p.GqlStatus = NewGQLStatus()
  if err := p.GqlStatus.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.GqlStatus), err)
  }
  return nil
}

func (p *XExecutionOutcome_)  ReadField2(iprot thrift.Protocol) error {
  p.Result_ = nebula0.NewBindingTable()
  if err := p.Result_.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Result_), err)
  }
  return nil
}

func (p *XExecutionOutcome_)  ReadField3(iprot thrift.Protocol) error {
  p.PlanDesc = NewPlanDescription()
  if err := p.PlanDesc.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.PlanDesc), err)
  }
  return nil
}

func (p *XExecutionOutcome_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_ExecutionOutcome_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XExecutionOutcome_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("gqlStatus", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:gqlStatus: ", p), err) }
  if err := p.GqlStatus.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.GqlStatus), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:gqlStatus: ", p), err) }
  return err
}

func (p *XExecutionOutcome_) writeField2(oprot thrift.Protocol) (err error) {
  if p.IsSetResult_() {
    if err := oprot.WriteFieldBegin("result", thrift.STRUCT, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:result: ", p), err) }
    if err := p.Result_.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Result_), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:result: ", p), err) }
  }
  return err
}

func (p *XExecutionOutcome_) writeField3(oprot thrift.Protocol) (err error) {
  if p.IsSetPlanDesc() {
    if err := oprot.WriteFieldBegin("plan_desc", thrift.STRUCT, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:plan_desc: ", p), err) }
    if err := p.PlanDesc.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.PlanDesc), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:plan_desc: ", p), err) }
  }
  return err
}

func (p *XExecutionOutcome_) String() string {
  if p == nil {
    return "<nil>"
  }

  var gqlStatusVal string
  if p.GqlStatus == nil {
    gqlStatusVal = "<nil>"
  } else {
    gqlStatusVal = fmt.Sprintf("%v", p.GqlStatus)
  }
  var resultVal string
  if p.Result_ == nil {
    resultVal = "<nil>"
  } else {
    resultVal = fmt.Sprintf("%v", p.Result_)
  }
  var planDescVal string
  if p.PlanDesc == nil {
    planDescVal = "<nil>"
  } else {
    planDescVal = fmt.Sprintf("%v", p.PlanDesc)
  }
  return fmt.Sprintf("XExecutionOutcome_({GqlStatus:%s Result_:%s PlanDesc:%s})", gqlStatusVal, resultVal, planDescVal)
}

// Attributes:
//  - ExecutionOutcome
//  - LatencyInUs
type XExecutionResponse_ struct {
  ExecutionOutcome ExecutionOutcome `thrift:"executionOutcome,1" db:"executionOutcome" json:"executionOutcome"`
  LatencyInUs int64 `thrift:"latencyInUs,2" db:"latencyInUs" json:"latencyInUs"`
}

func NewXExecutionResponse_() *XExecutionResponse_ {
  return &XExecutionResponse_{
    ExecutionOutcome: NewExecutionOutcome(),
  }
}

var XExecutionResponse__ExecutionOutcome_DEFAULT ExecutionOutcome
func (p *XExecutionResponse_) GetExecutionOutcome() ExecutionOutcome {
  if !p.IsSetExecutionOutcome() {
    return XExecutionResponse__ExecutionOutcome_DEFAULT
  }
  return p.ExecutionOutcome
}

func (p *XExecutionResponse_) GetLatencyInUs() int64 {
  return p.LatencyInUs
}
func (p *XExecutionResponse_) IsSetExecutionOutcome() bool {
  return p != nil && p.ExecutionOutcome != nil
}

type XExecutionResponse_Builder struct {
  obj *XExecutionResponse_
}

func NewXExecutionResponse_Builder() *XExecutionResponse_Builder{
  return &XExecutionResponse_Builder{
    obj: NewXExecutionResponse_(),
  }
}

func (p XExecutionResponse_Builder) Emit() *XExecutionResponse_{
  return &XExecutionResponse_{
    ExecutionOutcome: p.obj.ExecutionOutcome,
    LatencyInUs: p.obj.LatencyInUs,
  }
}

func (x *XExecutionResponse_Builder) ExecutionOutcome(executionOutcome ExecutionOutcome) *XExecutionResponse_Builder {
  x.obj.ExecutionOutcome = executionOutcome
  return x
}

func (x *XExecutionResponse_Builder) LatencyInUs(latencyInUs int64) *XExecutionResponse_Builder {
  x.obj.LatencyInUs = latencyInUs
  return x
}

func (x *XExecutionResponse_) SetExecutionOutcome(executionOutcome ExecutionOutcome) *XExecutionResponse_ {
  x.ExecutionOutcome = executionOutcome
  return x
}

func (x *XExecutionResponse_) SetLatencyInUs(latencyInUs int64) *XExecutionResponse_ {
  x.LatencyInUs = latencyInUs
  return x
}

func (p *XExecutionResponse_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XExecutionResponse_)  ReadField1(iprot thrift.Protocol) error {
  p.ExecutionOutcome = NewExecutionOutcome()
  if err := p.ExecutionOutcome.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ExecutionOutcome), err)
  }
  return nil
}

func (p *XExecutionResponse_)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.LatencyInUs = v
  }
  return nil
}

func (p *XExecutionResponse_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_ExecutionResponse_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XExecutionResponse_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("executionOutcome", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:executionOutcome: ", p), err) }
  if err := p.ExecutionOutcome.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ExecutionOutcome), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:executionOutcome: ", p), err) }
  return err
}

func (p *XExecutionResponse_) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("latencyInUs", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:latencyInUs: ", p), err) }
  if err := oprot.WriteI64(int64(p.LatencyInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.latencyInUs (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:latencyInUs: ", p), err) }
  return err
}

func (p *XExecutionResponse_) String() string {
  if p == nil {
    return "<nil>"
  }

  var executionOutcomeVal string
  if p.ExecutionOutcome == nil {
    executionOutcomeVal = "<nil>"
  } else {
    executionOutcomeVal = fmt.Sprintf("%v", p.ExecutionOutcome)
  }
  latencyInUsVal := fmt.Sprintf("%v", p.LatencyInUs)
  return fmt.Sprintf("XExecutionResponse_({ExecutionOutcome:%s LatencyInUs:%s})", executionOutcomeVal, latencyInUsVal)
}

// Attributes:
//  - Username
//  - Password
//  - ClientType
//  - ClientVersion
type AuthReq struct {
  Username []byte `thrift:"username,1" db:"username" json:"username"`
  Password []byte `thrift:"password,2" db:"password" json:"password"`
  ClientType []byte `thrift:"client_type,3" db:"client_type" json:"client_type"`
  ClientVersion []byte `thrift:"client_version,4" db:"client_version" json:"client_version"`
}

func NewAuthReq() *AuthReq {
  return &AuthReq{}
}


func (p *AuthReq) GetUsername() []byte {
  return p.Username
}

func (p *AuthReq) GetPassword() []byte {
  return p.Password
}

func (p *AuthReq) GetClientType() []byte {
  return p.ClientType
}

func (p *AuthReq) GetClientVersion() []byte {
  return p.ClientVersion
}
type AuthReqBuilder struct {
  obj *AuthReq
}

func NewAuthReqBuilder() *AuthReqBuilder{
  return &AuthReqBuilder{
    obj: NewAuthReq(),
  }
}

func (p AuthReqBuilder) Emit() *AuthReq{
  return &AuthReq{
    Username: p.obj.Username,
    Password: p.obj.Password,
    ClientType: p.obj.ClientType,
    ClientVersion: p.obj.ClientVersion,
  }
}

func (a *AuthReqBuilder) Username(username []byte) *AuthReqBuilder {
  a.obj.Username = username
  return a
}

func (a *AuthReqBuilder) Password(password []byte) *AuthReqBuilder {
  a.obj.Password = password
  return a
}

func (a *AuthReqBuilder) ClientType(clientType []byte) *AuthReqBuilder {
  a.obj.ClientType = clientType
  return a
}

func (a *AuthReqBuilder) ClientVersion(clientVersion []byte) *AuthReqBuilder {
  a.obj.ClientVersion = clientVersion
  return a
}

func (a *AuthReq) SetUsername(username []byte) *AuthReq {
  a.Username = username
  return a
}

func (a *AuthReq) SetPassword(password []byte) *AuthReq {
  a.Password = password
  return a
}

func (a *AuthReq) SetClientType(clientType []byte) *AuthReq {
  a.ClientType = clientType
  return a
}

func (a *AuthReq) SetClientVersion(clientVersion []byte) *AuthReq {
  a.ClientVersion = clientVersion
  return a
}

func (p *AuthReq) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *AuthReq)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Username = v
  }
  return nil
}

func (p *AuthReq)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Password = v
  }
  return nil
}

func (p *AuthReq)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.ClientType = v
  }
  return nil
}

func (p *AuthReq)  ReadField4(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 4: ", err)
  } else {
    p.ClientVersion = v
  }
  return nil
}

func (p *AuthReq) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("AuthReq"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *AuthReq) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("username", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:username: ", p), err) }
  if err := oprot.WriteBinary(p.Username); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.username (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:username: ", p), err) }
  return err
}

func (p *AuthReq) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("password", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:password: ", p), err) }
  if err := oprot.WriteBinary(p.Password); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.password (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:password: ", p), err) }
  return err
}

func (p *AuthReq) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("client_type", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:client_type: ", p), err) }
  if err := oprot.WriteBinary(p.ClientType); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.client_type (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:client_type: ", p), err) }
  return err
}

func (p *AuthReq) writeField4(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("client_version", thrift.STRING, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:client_version: ", p), err) }
  if err := oprot.WriteBinary(p.ClientVersion); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.client_version (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:client_version: ", p), err) }
  return err
}

func (p *AuthReq) String() string {
  if p == nil {
    return "<nil>"
  }

  usernameVal := fmt.Sprintf("%v", p.Username)
  passwordVal := fmt.Sprintf("%v", p.Password)
  clientTypeVal := fmt.Sprintf("%v", p.ClientType)
  clientVersionVal := fmt.Sprintf("%v", p.ClientVersion)
  return fmt.Sprintf("AuthReq({Username:%s Password:%s ClientType:%s ClientVersion:%s})", usernameVal, passwordVal, clientTypeVal, clientVersionVal)
}

// Attributes:
//  - GqlStatus
//  - Identifier
type XAuthResponse_ struct {
  GqlStatus GQLStatus `thrift:"gqlStatus,1" db:"gqlStatus" json:"gqlStatus"`
  Identifier *int64 `thrift:"identifier,2,optional" db:"identifier" json:"identifier,omitempty"`
}

func NewXAuthResponse_() *XAuthResponse_ {
  return &XAuthResponse_{
    GqlStatus: NewGQLStatus(),
  }
}

var XAuthResponse__GqlStatus_DEFAULT GQLStatus
func (p *XAuthResponse_) GetGqlStatus() GQLStatus {
  if !p.IsSetGqlStatus() {
    return XAuthResponse__GqlStatus_DEFAULT
  }
  return p.GqlStatus
}
var XAuthResponse__Identifier_DEFAULT int64
func (p *XAuthResponse_) GetIdentifier() int64 {
  if !p.IsSetIdentifier() {
    return XAuthResponse__Identifier_DEFAULT
  }
  return *p.Identifier
}
func (p *XAuthResponse_) IsSetGqlStatus() bool {
  return p != nil && p.GqlStatus != nil
}

func (p *XAuthResponse_) IsSetIdentifier() bool {
  return p != nil && p.Identifier != nil
}

type XAuthResponse_Builder struct {
  obj *XAuthResponse_
}

func NewXAuthResponse_Builder() *XAuthResponse_Builder{
  return &XAuthResponse_Builder{
    obj: NewXAuthResponse_(),
  }
}

func (p XAuthResponse_Builder) Emit() *XAuthResponse_{
  return &XAuthResponse_{
    GqlStatus: p.obj.GqlStatus,
    Identifier: p.obj.Identifier,
  }
}

func (x *XAuthResponse_Builder) GqlStatus(gqlStatus GQLStatus) *XAuthResponse_Builder {
  x.obj.GqlStatus = gqlStatus
  return x
}

func (x *XAuthResponse_Builder) Identifier(identifier *int64) *XAuthResponse_Builder {
  x.obj.Identifier = identifier
  return x
}

func (x *XAuthResponse_) SetGqlStatus(gqlStatus GQLStatus) *XAuthResponse_ {
  x.GqlStatus = gqlStatus
  return x
}

func (x *XAuthResponse_) SetIdentifier(identifier *int64) *XAuthResponse_ {
  x.Identifier = identifier
  return x
}

func (p *XAuthResponse_) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *XAuthResponse_)  ReadField1(iprot thrift.Protocol) error {
  p.GqlStatus = NewGQLStatus()
  if err := p.GqlStatus.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.GqlStatus), err)
  }
  return nil
}

func (p *XAuthResponse_)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Identifier = &v
  }
  return nil
}

func (p *XAuthResponse_) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("_AuthResponse_"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *XAuthResponse_) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("gqlStatus", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:gqlStatus: ", p), err) }
  if err := p.GqlStatus.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.GqlStatus), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:gqlStatus: ", p), err) }
  return err
}

func (p *XAuthResponse_) writeField2(oprot thrift.Protocol) (err error) {
  if p.IsSetIdentifier() {
    if err := oprot.WriteFieldBegin("identifier", thrift.I64, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:identifier: ", p), err) }
    if err := oprot.WriteI64(int64(*p.Identifier)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.identifier (2) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:identifier: ", p), err) }
  }
  return err
}

func (p *XAuthResponse_) String() string {
  if p == nil {
    return "<nil>"
  }

  var gqlStatusVal string
  if p.GqlStatus == nil {
    gqlStatusVal = "<nil>"
  } else {
    gqlStatusVal = fmt.Sprintf("%v", p.GqlStatus)
  }
  var identifierVal string
  if p.Identifier == nil {
    identifierVal = "<nil>"
  } else {
    identifierVal = fmt.Sprintf("%v", *p.Identifier)
  }
  return fmt.Sprintf("XAuthResponse_({GqlStatus:%s Identifier:%s})", gqlStatusVal, identifierVal)
}

