// Autogenerated by Thrift Compiler (facebook)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// @generated

package graph

import (
	"bytes"
	"context"
	"sync"
	"fmt"
	thrift "github.com/facebook/fbthrift/thrift/lib/go/thrift"
	nebula0 "github.com/vesoft-inc/nebula-ng-tools/golang/pkg/generated_code/v5.0.0/nebula"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = sync.Mutex{}
var _ = bytes.Equal
var _ = context.Background

var _ = nebula0.GoUnusedProtection__
var GoUnusedProtection__ int;

// Attributes:
//  - Rows
//  - ExecDurationInUs
//  - TotalDurationInUs
//  - OtherStats
type ProfilingStats struct {
  Rows int64 `thrift:"rows,1,required" db:"rows" json:"rows"`
  ExecDurationInUs int64 `thrift:"exec_duration_in_us,2,required" db:"exec_duration_in_us" json:"exec_duration_in_us"`
  TotalDurationInUs int64 `thrift:"total_duration_in_us,3,required" db:"total_duration_in_us" json:"total_duration_in_us"`
  OtherStats map[string][]byte `thrift:"other_stats,4,optional" db:"other_stats" json:"other_stats,omitempty"`
}

func NewProfilingStats() *ProfilingStats {
  return &ProfilingStats{}
}


func (p *ProfilingStats) GetRows() int64 {
  return p.Rows
}

func (p *ProfilingStats) GetExecDurationInUs() int64 {
  return p.ExecDurationInUs
}

func (p *ProfilingStats) GetTotalDurationInUs() int64 {
  return p.TotalDurationInUs
}
var ProfilingStats_OtherStats_DEFAULT map[string][]byte

func (p *ProfilingStats) GetOtherStats() map[string][]byte {
  return p.OtherStats
}
func (p *ProfilingStats) IsSetOtherStats() bool {
  return p != nil && p.OtherStats != nil
}

type ProfilingStatsBuilder struct {
  obj *ProfilingStats
}

func NewProfilingStatsBuilder() *ProfilingStatsBuilder{
  return &ProfilingStatsBuilder{
    obj: NewProfilingStats(),
  }
}

func (p ProfilingStatsBuilder) Emit() *ProfilingStats{
  return &ProfilingStats{
    Rows: p.obj.Rows,
    ExecDurationInUs: p.obj.ExecDurationInUs,
    TotalDurationInUs: p.obj.TotalDurationInUs,
    OtherStats: p.obj.OtherStats,
  }
}

func (p *ProfilingStatsBuilder) Rows(rows int64) *ProfilingStatsBuilder {
  p.obj.Rows = rows
  return p
}

func (p *ProfilingStatsBuilder) ExecDurationInUs(execDurationInUs int64) *ProfilingStatsBuilder {
  p.obj.ExecDurationInUs = execDurationInUs
  return p
}

func (p *ProfilingStatsBuilder) TotalDurationInUs(totalDurationInUs int64) *ProfilingStatsBuilder {
  p.obj.TotalDurationInUs = totalDurationInUs
  return p
}

func (p *ProfilingStatsBuilder) OtherStats(otherStats map[string][]byte) *ProfilingStatsBuilder {
  p.obj.OtherStats = otherStats
  return p
}

func (p *ProfilingStats) SetRows(rows int64) *ProfilingStats {
  p.Rows = rows
  return p
}

func (p *ProfilingStats) SetExecDurationInUs(execDurationInUs int64) *ProfilingStats {
  p.ExecDurationInUs = execDurationInUs
  return p
}

func (p *ProfilingStats) SetTotalDurationInUs(totalDurationInUs int64) *ProfilingStats {
  p.TotalDurationInUs = totalDurationInUs
  return p
}

func (p *ProfilingStats) SetOtherStats(otherStats map[string][]byte) *ProfilingStats {
  p.OtherStats = otherStats
  return p
}

func (p *ProfilingStats) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetRows bool = false;
  var issetExecDurationInUs bool = false;
  var issetTotalDurationInUs bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetRows = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetExecDurationInUs = true
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
      issetTotalDurationInUs = true
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetRows{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Rows is not set"));
  }
  if !issetExecDurationInUs{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ExecDurationInUs is not set"));
  }
  if !issetTotalDurationInUs{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field TotalDurationInUs is not set"));
  }
  return nil
}

func (p *ProfilingStats)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Rows = v
  }
  return nil
}

func (p *ProfilingStats)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.ExecDurationInUs = v
  }
  return nil
}

func (p *ProfilingStats)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.TotalDurationInUs = v
  }
  return nil
}

func (p *ProfilingStats)  ReadField4(iprot thrift.Protocol) error {
  _, _, size, err := iprot.ReadMapBegin()
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[string][]byte, size)
  p.OtherStats =  tMap
  for i := 0; i < size; i ++ {
    var _key1 string
    if v, err := iprot.ReadString(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _key1 = v
    }
    var _val2 []byte
    if v, err := iprot.ReadBinary(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _val2 = v
    }
    p.OtherStats[_key1] = _val2
  }
  if err := iprot.ReadMapEnd(); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *ProfilingStats) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("ProfilingStats"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ProfilingStats) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("rows", thrift.I64, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:rows: ", p), err) }
  if err := oprot.WriteI64(int64(p.Rows)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.rows (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:rows: ", p), err) }
  return err
}

func (p *ProfilingStats) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("exec_duration_in_us", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:exec_duration_in_us: ", p), err) }
  if err := oprot.WriteI64(int64(p.ExecDurationInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.exec_duration_in_us (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:exec_duration_in_us: ", p), err) }
  return err
}

func (p *ProfilingStats) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("total_duration_in_us", thrift.I64, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:total_duration_in_us: ", p), err) }
  if err := oprot.WriteI64(int64(p.TotalDurationInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.total_duration_in_us (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:total_duration_in_us: ", p), err) }
  return err
}

func (p *ProfilingStats) writeField4(oprot thrift.Protocol) (err error) {
  if p.IsSetOtherStats() {
    if err := oprot.WriteFieldBegin("other_stats", thrift.MAP, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:other_stats: ", p), err) }
    if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.OtherStats)); err != nil {
      return thrift.PrependError("error writing map begin: ", err)
    }
    for k, v := range p.OtherStats {
      if err := oprot.WriteString(string(k)); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
      if err := oprot.WriteBinary(v); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    }
    if err := oprot.WriteMapEnd(); err != nil {
      return thrift.PrependError("error writing map end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:other_stats: ", p), err) }
  }
  return err
}

func (p *ProfilingStats) String() string {
  if p == nil {
    return "<nil>"
  }

  rowsVal := fmt.Sprintf("%v", p.Rows)
  execDurationInUsVal := fmt.Sprintf("%v", p.ExecDurationInUs)
  totalDurationInUsVal := fmt.Sprintf("%v", p.TotalDurationInUs)
  otherStatsVal := fmt.Sprintf("%v", p.OtherStats)
  return fmt.Sprintf("ProfilingStats({Rows:%s ExecDurationInUs:%s TotalDurationInUs:%s OtherStats:%s})", rowsVal, execDurationInUsVal, totalDurationInUsVal, otherStatsVal)
}

// Attributes:
//  - Key
//  - Value
type Pair struct {
  Key []byte `thrift:"key,1,required" db:"key" json:"key"`
  Value []byte `thrift:"value,2,required" db:"value" json:"value"`
}

func NewPair() *Pair {
  return &Pair{}
}


func (p *Pair) GetKey() []byte {
  return p.Key
}

func (p *Pair) GetValue() []byte {
  return p.Value
}
type PairBuilder struct {
  obj *Pair
}

func NewPairBuilder() *PairBuilder{
  return &PairBuilder{
    obj: NewPair(),
  }
}

func (p PairBuilder) Emit() *Pair{
  return &Pair{
    Key: p.obj.Key,
    Value: p.obj.Value,
  }
}

func (p *PairBuilder) Key(key []byte) *PairBuilder {
  p.obj.Key = key
  return p
}

func (p *PairBuilder) Value(value []byte) *PairBuilder {
  p.obj.Value = value
  return p
}

func (p *Pair) SetKey(key []byte) *Pair {
  p.Key = key
  return p
}

func (p *Pair) SetValue(value []byte) *Pair {
  p.Value = value
  return p
}

func (p *Pair) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetKey bool = false;
  var issetValue bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetKey = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetValue = true
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetKey{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Key is not set"));
  }
  if !issetValue{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Value is not set"));
  }
  return nil
}

func (p *Pair)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Key = v
  }
  return nil
}

func (p *Pair)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Value = v
  }
  return nil
}

func (p *Pair) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("Pair"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Pair) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("key", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:key: ", p), err) }
  if err := oprot.WriteBinary(p.Key); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.key (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:key: ", p), err) }
  return err
}

func (p *Pair) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("value", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:value: ", p), err) }
  if err := oprot.WriteBinary(p.Value); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.value (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:value: ", p), err) }
  return err
}

func (p *Pair) String() string {
  if p == nil {
    return "<nil>"
  }

  keyVal := fmt.Sprintf("%v", p.Key)
  valueVal := fmt.Sprintf("%v", p.Value)
  return fmt.Sprintf("Pair({Key:%s Value:%s})", keyVal, valueVal)
}

// Attributes:
//  - Name
//  - Id
//  - OutputVar
//  - Description
//  - Profiles
//  - Dependencies
type PlanNodeDescription struct {
  Name []byte `thrift:"name,1,required" db:"name" json:"name"`
  Id int64 `thrift:"id,2,required" db:"id" json:"id"`
  OutputVar []byte `thrift:"output_var,3,required" db:"output_var" json:"output_var"`
  Description []*Pair `thrift:"description,4,optional" db:"description" json:"description,omitempty"`
  Profiles []*ProfilingStats `thrift:"profiles,5,optional" db:"profiles" json:"profiles,omitempty"`
  Dependencies []int64 `thrift:"dependencies,6,optional" db:"dependencies" json:"dependencies,omitempty"`
}

func NewPlanNodeDescription() *PlanNodeDescription {
  return &PlanNodeDescription{}
}


func (p *PlanNodeDescription) GetName() []byte {
  return p.Name
}

func (p *PlanNodeDescription) GetId() int64 {
  return p.Id
}

func (p *PlanNodeDescription) GetOutputVar() []byte {
  return p.OutputVar
}
var PlanNodeDescription_Description_DEFAULT []*Pair

func (p *PlanNodeDescription) GetDescription() []*Pair {
  return p.Description
}
var PlanNodeDescription_Profiles_DEFAULT []*ProfilingStats

func (p *PlanNodeDescription) GetProfiles() []*ProfilingStats {
  return p.Profiles
}
var PlanNodeDescription_Dependencies_DEFAULT []int64

func (p *PlanNodeDescription) GetDependencies() []int64 {
  return p.Dependencies
}
func (p *PlanNodeDescription) IsSetDescription() bool {
  return p != nil && p.Description != nil
}

func (p *PlanNodeDescription) IsSetProfiles() bool {
  return p != nil && p.Profiles != nil
}

func (p *PlanNodeDescription) IsSetDependencies() bool {
  return p != nil && p.Dependencies != nil
}

type PlanNodeDescriptionBuilder struct {
  obj *PlanNodeDescription
}

func NewPlanNodeDescriptionBuilder() *PlanNodeDescriptionBuilder{
  return &PlanNodeDescriptionBuilder{
    obj: NewPlanNodeDescription(),
  }
}

func (p PlanNodeDescriptionBuilder) Emit() *PlanNodeDescription{
  return &PlanNodeDescription{
    Name: p.obj.Name,
    Id: p.obj.Id,
    OutputVar: p.obj.OutputVar,
    Description: p.obj.Description,
    Profiles: p.obj.Profiles,
    Dependencies: p.obj.Dependencies,
  }
}

func (p *PlanNodeDescriptionBuilder) Name(name []byte) *PlanNodeDescriptionBuilder {
  p.obj.Name = name
  return p
}

func (p *PlanNodeDescriptionBuilder) Id(id int64) *PlanNodeDescriptionBuilder {
  p.obj.Id = id
  return p
}

func (p *PlanNodeDescriptionBuilder) OutputVar(outputVar []byte) *PlanNodeDescriptionBuilder {
  p.obj.OutputVar = outputVar
  return p
}

func (p *PlanNodeDescriptionBuilder) Description(description []*Pair) *PlanNodeDescriptionBuilder {
  p.obj.Description = description
  return p
}

func (p *PlanNodeDescriptionBuilder) Profiles(profiles []*ProfilingStats) *PlanNodeDescriptionBuilder {
  p.obj.Profiles = profiles
  return p
}

func (p *PlanNodeDescriptionBuilder) Dependencies(dependencies []int64) *PlanNodeDescriptionBuilder {
  p.obj.Dependencies = dependencies
  return p
}

func (p *PlanNodeDescription) SetName(name []byte) *PlanNodeDescription {
  p.Name = name
  return p
}

func (p *PlanNodeDescription) SetId(id int64) *PlanNodeDescription {
  p.Id = id
  return p
}

func (p *PlanNodeDescription) SetOutputVar(outputVar []byte) *PlanNodeDescription {
  p.OutputVar = outputVar
  return p
}

func (p *PlanNodeDescription) SetDescription(description []*Pair) *PlanNodeDescription {
  p.Description = description
  return p
}

func (p *PlanNodeDescription) SetProfiles(profiles []*ProfilingStats) *PlanNodeDescription {
  p.Profiles = profiles
  return p
}

func (p *PlanNodeDescription) SetDependencies(dependencies []int64) *PlanNodeDescription {
  p.Dependencies = dependencies
  return p
}

func (p *PlanNodeDescription) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetName bool = false;
  var issetId bool = false;
  var issetOutputVar bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetName = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetId = true
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
      issetOutputVar = true
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    case 5:
      if err := p.ReadField5(iprot); err != nil {
        return err
      }
    case 6:
      if err := p.ReadField6(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetName{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Name is not set"));
  }
  if !issetId{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Id is not set"));
  }
  if !issetOutputVar{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field OutputVar is not set"));
  }
  return nil
}

func (p *PlanNodeDescription)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Name = v
  }
  return nil
}

func (p *PlanNodeDescription)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Id = v
  }
  return nil
}

func (p *PlanNodeDescription)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.OutputVar = v
  }
  return nil
}

func (p *PlanNodeDescription)  ReadField4(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]*Pair, 0, size)
  p.Description =  tSlice
  for i := 0; i < size; i ++ {
    _elem3 := NewPair()
    if err := _elem3.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem3), err)
    }
    p.Description = append(p.Description, _elem3)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *PlanNodeDescription)  ReadField5(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]*ProfilingStats, 0, size)
  p.Profiles =  tSlice
  for i := 0; i < size; i ++ {
    _elem4 := NewProfilingStats()
    if err := _elem4.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem4), err)
    }
    p.Profiles = append(p.Profiles, _elem4)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *PlanNodeDescription)  ReadField6(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]int64, 0, size)
  p.Dependencies =  tSlice
  for i := 0; i < size; i ++ {
    var _elem5 int64
    if v, err := iprot.ReadI64(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _elem5 = v
    }
    p.Dependencies = append(p.Dependencies, _elem5)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *PlanNodeDescription) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("PlanNodeDescription"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := p.writeField5(oprot); err != nil { return err }
  if err := p.writeField6(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *PlanNodeDescription) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("name", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:name: ", p), err) }
  if err := oprot.WriteBinary(p.Name); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.name (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:name: ", p), err) }
  return err
}

func (p *PlanNodeDescription) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("id", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:id: ", p), err) }
  if err := oprot.WriteI64(int64(p.Id)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.id (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:id: ", p), err) }
  return err
}

func (p *PlanNodeDescription) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("output_var", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:output_var: ", p), err) }
  if err := oprot.WriteBinary(p.OutputVar); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.output_var (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:output_var: ", p), err) }
  return err
}

func (p *PlanNodeDescription) writeField4(oprot thrift.Protocol) (err error) {
  if p.IsSetDescription() {
    if err := oprot.WriteFieldBegin("description", thrift.LIST, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:description: ", p), err) }
    if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Description)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Description {
      if err := v.Write(oprot); err != nil {
        return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
      }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:description: ", p), err) }
  }
  return err
}

func (p *PlanNodeDescription) writeField5(oprot thrift.Protocol) (err error) {
  if p.IsSetProfiles() {
    if err := oprot.WriteFieldBegin("profiles", thrift.LIST, 5); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:profiles: ", p), err) }
    if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Profiles)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Profiles {
      if err := v.Write(oprot); err != nil {
        return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
      }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 5:profiles: ", p), err) }
  }
  return err
}

func (p *PlanNodeDescription) writeField6(oprot thrift.Protocol) (err error) {
  if p.IsSetDependencies() {
    if err := oprot.WriteFieldBegin("dependencies", thrift.LIST, 6); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:dependencies: ", p), err) }
    if err := oprot.WriteListBegin(thrift.I64, len(p.Dependencies)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Dependencies {
      if err := oprot.WriteI64(int64(v)); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 6:dependencies: ", p), err) }
  }
  return err
}

func (p *PlanNodeDescription) String() string {
  if p == nil {
    return "<nil>"
  }

  nameVal := fmt.Sprintf("%v", p.Name)
  idVal := fmt.Sprintf("%v", p.Id)
  outputVarVal := fmt.Sprintf("%v", p.OutputVar)
  descriptionVal := fmt.Sprintf("%v", p.Description)
  profilesVal := fmt.Sprintf("%v", p.Profiles)
  dependenciesVal := fmt.Sprintf("%v", p.Dependencies)
  return fmt.Sprintf("PlanNodeDescription({Name:%s Id:%s OutputVar:%s Description:%s Profiles:%s Dependencies:%s})", nameVal, idVal, outputVarVal, descriptionVal, profilesVal, dependenciesVal)
}

// Attributes:
//  - PlanNodeDescs
//  - NodeIndexMap
//  - Format
//  - OptimizeTimeInUs
type PlanDescription struct {
  PlanNodeDescs []*PlanNodeDescription `thrift:"plan_node_descs,1,required" db:"plan_node_descs" json:"plan_node_descs"`
  NodeIndexMap map[int64]int64 `thrift:"node_index_map,2,required" db:"node_index_map" json:"node_index_map"`
  Format []byte `thrift:"format,3,required" db:"format" json:"format"`
  OptimizeTimeInUs int32 `thrift:"optimize_time_in_us,4,required" db:"optimize_time_in_us" json:"optimize_time_in_us"`
}

func NewPlanDescription() *PlanDescription {
  return &PlanDescription{}
}


func (p *PlanDescription) GetPlanNodeDescs() []*PlanNodeDescription {
  return p.PlanNodeDescs
}

func (p *PlanDescription) GetNodeIndexMap() map[int64]int64 {
  return p.NodeIndexMap
}

func (p *PlanDescription) GetFormat() []byte {
  return p.Format
}

func (p *PlanDescription) GetOptimizeTimeInUs() int32 {
  return p.OptimizeTimeInUs
}
type PlanDescriptionBuilder struct {
  obj *PlanDescription
}

func NewPlanDescriptionBuilder() *PlanDescriptionBuilder{
  return &PlanDescriptionBuilder{
    obj: NewPlanDescription(),
  }
}

func (p PlanDescriptionBuilder) Emit() *PlanDescription{
  return &PlanDescription{
    PlanNodeDescs: p.obj.PlanNodeDescs,
    NodeIndexMap: p.obj.NodeIndexMap,
    Format: p.obj.Format,
    OptimizeTimeInUs: p.obj.OptimizeTimeInUs,
  }
}

func (p *PlanDescriptionBuilder) PlanNodeDescs(planNodeDescs []*PlanNodeDescription) *PlanDescriptionBuilder {
  p.obj.PlanNodeDescs = planNodeDescs
  return p
}

func (p *PlanDescriptionBuilder) NodeIndexMap(nodeIndexMap map[int64]int64) *PlanDescriptionBuilder {
  p.obj.NodeIndexMap = nodeIndexMap
  return p
}

func (p *PlanDescriptionBuilder) Format(format []byte) *PlanDescriptionBuilder {
  p.obj.Format = format
  return p
}

func (p *PlanDescriptionBuilder) OptimizeTimeInUs(optimizeTimeInUs int32) *PlanDescriptionBuilder {
  p.obj.OptimizeTimeInUs = optimizeTimeInUs
  return p
}

func (p *PlanDescription) SetPlanNodeDescs(planNodeDescs []*PlanNodeDescription) *PlanDescription {
  p.PlanNodeDescs = planNodeDescs
  return p
}

func (p *PlanDescription) SetNodeIndexMap(nodeIndexMap map[int64]int64) *PlanDescription {
  p.NodeIndexMap = nodeIndexMap
  return p
}

func (p *PlanDescription) SetFormat(format []byte) *PlanDescription {
  p.Format = format
  return p
}

func (p *PlanDescription) SetOptimizeTimeInUs(optimizeTimeInUs int32) *PlanDescription {
  p.OptimizeTimeInUs = optimizeTimeInUs
  return p
}

func (p *PlanDescription) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetPlanNodeDescs bool = false;
  var issetNodeIndexMap bool = false;
  var issetFormat bool = false;
  var issetOptimizeTimeInUs bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetPlanNodeDescs = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetNodeIndexMap = true
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
      issetFormat = true
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
      issetOptimizeTimeInUs = true
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetPlanNodeDescs{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field PlanNodeDescs is not set"));
  }
  if !issetNodeIndexMap{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field NodeIndexMap is not set"));
  }
  if !issetFormat{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Format is not set"));
  }
  if !issetOptimizeTimeInUs{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field OptimizeTimeInUs is not set"));
  }
  return nil
}

func (p *PlanDescription)  ReadField1(iprot thrift.Protocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]*PlanNodeDescription, 0, size)
  p.PlanNodeDescs =  tSlice
  for i := 0; i < size; i ++ {
    _elem6 := NewPlanNodeDescription()
    if err := _elem6.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem6), err)
    }
    p.PlanNodeDescs = append(p.PlanNodeDescs, _elem6)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *PlanDescription)  ReadField2(iprot thrift.Protocol) error {
  _, _, size, err := iprot.ReadMapBegin()
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[int64]int64, size)
  p.NodeIndexMap =  tMap
  for i := 0; i < size; i ++ {
    var _key7 int64
    if v, err := iprot.ReadI64(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _key7 = v
    }
    var _val8 int64
    if v, err := iprot.ReadI64(); err != nil {
      return thrift.PrependError("error reading field 0: ", err)
    } else {
      _val8 = v
    }
    p.NodeIndexMap[_key7] = _val8
  }
  if err := iprot.ReadMapEnd(); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *PlanDescription)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.Format = v
  }
  return nil
}

func (p *PlanDescription)  ReadField4(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI32(); err != nil {
    return thrift.PrependError("error reading field 4: ", err)
  } else {
    p.OptimizeTimeInUs = v
  }
  return nil
}

func (p *PlanDescription) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("PlanDescription"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *PlanDescription) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("plan_node_descs", thrift.LIST, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:plan_node_descs: ", p), err) }
  if err := oprot.WriteListBegin(thrift.STRUCT, len(p.PlanNodeDescs)); err != nil {
    return thrift.PrependError("error writing list begin: ", err)
  }
  for _, v := range p.PlanNodeDescs {
    if err := v.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
    }
  }
  if err := oprot.WriteListEnd(); err != nil {
    return thrift.PrependError("error writing list end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:plan_node_descs: ", p), err) }
  return err
}

func (p *PlanDescription) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("node_index_map", thrift.MAP, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:node_index_map: ", p), err) }
  if err := oprot.WriteMapBegin(thrift.I64, thrift.I64, len(p.NodeIndexMap)); err != nil {
    return thrift.PrependError("error writing map begin: ", err)
  }
  for k, v := range p.NodeIndexMap {
    if err := oprot.WriteI64(int64(k)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    if err := oprot.WriteI64(int64(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteMapEnd(); err != nil {
    return thrift.PrependError("error writing map end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:node_index_map: ", p), err) }
  return err
}

func (p *PlanDescription) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("format", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:format: ", p), err) }
  if err := oprot.WriteBinary(p.Format); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.format (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:format: ", p), err) }
  return err
}

func (p *PlanDescription) writeField4(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("optimize_time_in_us", thrift.I32, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:optimize_time_in_us: ", p), err) }
  if err := oprot.WriteI32(int32(p.OptimizeTimeInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.optimize_time_in_us (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:optimize_time_in_us: ", p), err) }
  return err
}

func (p *PlanDescription) String() string {
  if p == nil {
    return "<nil>"
  }

  planNodeDescsVal := fmt.Sprintf("%v", p.PlanNodeDescs)
  nodeIndexMapVal := fmt.Sprintf("%v", p.NodeIndexMap)
  formatVal := fmt.Sprintf("%v", p.Format)
  optimizeTimeInUsVal := fmt.Sprintf("%v", p.OptimizeTimeInUs)
  return fmt.Sprintf("PlanDescription({PlanNodeDescs:%s NodeIndexMap:%s Format:%s OptimizeTimeInUs:%s})", planNodeDescsVal, nodeIndexMapVal, formatVal, optimizeTimeInUsVal)
}

// Attributes:
//  - Status
type GQLStatus struct {
  Status []byte `thrift:"status,1,required" db:"status" json:"status"`
}

func NewGQLStatus() *GQLStatus {
  return &GQLStatus{}
}


func (p *GQLStatus) GetStatus() []byte {
  return p.Status
}
type GQLStatusBuilder struct {
  obj *GQLStatus
}

func NewGQLStatusBuilder() *GQLStatusBuilder{
  return &GQLStatusBuilder{
    obj: NewGQLStatus(),
  }
}

func (p GQLStatusBuilder) Emit() *GQLStatus{
  return &GQLStatus{
    Status: p.obj.Status,
  }
}

func (g *GQLStatusBuilder) Status(status []byte) *GQLStatusBuilder {
  g.obj.Status = status
  return g
}

func (g *GQLStatus) SetStatus(status []byte) *GQLStatus {
  g.Status = status
  return g
}

func (p *GQLStatus) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetStatus bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetStatus = true
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetStatus{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Status is not set"));
  }
  return nil
}

func (p *GQLStatus)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Status = v
  }
  return nil
}

func (p *GQLStatus) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("GQLStatus"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *GQLStatus) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("status", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:status: ", p), err) }
  if err := oprot.WriteBinary(p.Status); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.status (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:status: ", p), err) }
  return err
}

func (p *GQLStatus) String() string {
  if p == nil {
    return "<nil>"
  }

  statusVal := fmt.Sprintf("%v", p.Status)
  return fmt.Sprintf("GQLStatus({Status:%s})", statusVal)
}

// Attributes:
//  - GqlStatus
//  - Result_
type ExecutionOutcome struct {
  GqlStatus *GQLStatus `thrift:"gqlStatus,1,required" db:"gqlStatus" json:"gqlStatus"`
  Result_ *nebula0.BindingTable `thrift:"result,2,optional" db:"result" json:"result,omitempty"`
}

func NewExecutionOutcome() *ExecutionOutcome {
  return &ExecutionOutcome{
    GqlStatus: NewGQLStatus(),
  }
}

var ExecutionOutcome_GqlStatus_DEFAULT *GQLStatus
func (p *ExecutionOutcome) GetGqlStatus() *GQLStatus {
  if !p.IsSetGqlStatus() {
    return ExecutionOutcome_GqlStatus_DEFAULT
  }
return p.GqlStatus
}
var ExecutionOutcome_Result__DEFAULT *nebula0.BindingTable
func (p *ExecutionOutcome) GetResult_() *nebula0.BindingTable {
  if !p.IsSetResult_() {
    return ExecutionOutcome_Result__DEFAULT
  }
return p.Result_
}
func (p *ExecutionOutcome) IsSetGqlStatus() bool {
  return p != nil && p.GqlStatus != nil
}

func (p *ExecutionOutcome) IsSetResult_() bool {
  return p != nil && p.Result_ != nil
}

type ExecutionOutcomeBuilder struct {
  obj *ExecutionOutcome
}

func NewExecutionOutcomeBuilder() *ExecutionOutcomeBuilder{
  return &ExecutionOutcomeBuilder{
    obj: NewExecutionOutcome(),
  }
}

func (p ExecutionOutcomeBuilder) Emit() *ExecutionOutcome{
  return &ExecutionOutcome{
    GqlStatus: p.obj.GqlStatus,
    Result_: p.obj.Result_,
  }
}

func (e *ExecutionOutcomeBuilder) GqlStatus(gqlStatus *GQLStatus) *ExecutionOutcomeBuilder {
  e.obj.GqlStatus = gqlStatus
  return e
}

func (e *ExecutionOutcomeBuilder) Result_(result *nebula0.BindingTable) *ExecutionOutcomeBuilder {
  e.obj.Result_ = result
  return e
}

func (e *ExecutionOutcome) SetGqlStatus(gqlStatus *GQLStatus) *ExecutionOutcome {
  e.GqlStatus = gqlStatus
  return e
}

func (e *ExecutionOutcome) SetResult_(result *nebula0.BindingTable) *ExecutionOutcome {
  e.Result_ = result
  return e
}

func (p *ExecutionOutcome) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetGqlStatus bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetGqlStatus = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetGqlStatus{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field GqlStatus is not set"));
  }
  return nil
}

func (p *ExecutionOutcome)  ReadField1(iprot thrift.Protocol) error {
  p.GqlStatus = NewGQLStatus()
  if err := p.GqlStatus.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.GqlStatus), err)
  }
  return nil
}

func (p *ExecutionOutcome)  ReadField2(iprot thrift.Protocol) error {
  p.Result_ = nebula0.NewBindingTable()
  if err := p.Result_.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Result_), err)
  }
  return nil
}

func (p *ExecutionOutcome) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("ExecutionOutcome"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ExecutionOutcome) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("gqlStatus", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:gqlStatus: ", p), err) }
  if err := p.GqlStatus.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.GqlStatus), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:gqlStatus: ", p), err) }
  return err
}

func (p *ExecutionOutcome) writeField2(oprot thrift.Protocol) (err error) {
  if p.IsSetResult_() {
    if err := oprot.WriteFieldBegin("result", thrift.STRUCT, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:result: ", p), err) }
    if err := p.Result_.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Result_), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:result: ", p), err) }
  }
  return err
}

func (p *ExecutionOutcome) String() string {
  if p == nil {
    return "<nil>"
  }

  var gqlStatusVal string
  if p.GqlStatus == nil {
    gqlStatusVal = "<nil>"
  } else {
    gqlStatusVal = fmt.Sprintf("%v", p.GqlStatus)
  }
  var resultVal string
  if p.Result_ == nil {
    resultVal = "<nil>"
  } else {
    resultVal = fmt.Sprintf("%v", p.Result_)
  }
  return fmt.Sprintf("ExecutionOutcome({GqlStatus:%s Result_:%s})", gqlStatusVal, resultVal)
}

// Attributes:
//  - ExecutionOutcome
//  - LatencyInUs
type ExecutionResponse struct {
  ExecutionOutcome *ExecutionOutcome `thrift:"executionOutcome,1,required" db:"executionOutcome" json:"executionOutcome"`
  LatencyInUs int64 `thrift:"latencyInUs,2,required" db:"latencyInUs" json:"latencyInUs"`
}

func NewExecutionResponse() *ExecutionResponse {
  return &ExecutionResponse{
    ExecutionOutcome: NewExecutionOutcome(),
  }
}

var ExecutionResponse_ExecutionOutcome_DEFAULT *ExecutionOutcome
func (p *ExecutionResponse) GetExecutionOutcome() *ExecutionOutcome {
  if !p.IsSetExecutionOutcome() {
    return ExecutionResponse_ExecutionOutcome_DEFAULT
  }
return p.ExecutionOutcome
}

func (p *ExecutionResponse) GetLatencyInUs() int64 {
  return p.LatencyInUs
}
func (p *ExecutionResponse) IsSetExecutionOutcome() bool {
  return p != nil && p.ExecutionOutcome != nil
}

type ExecutionResponseBuilder struct {
  obj *ExecutionResponse
}

func NewExecutionResponseBuilder() *ExecutionResponseBuilder{
  return &ExecutionResponseBuilder{
    obj: NewExecutionResponse(),
  }
}

func (p ExecutionResponseBuilder) Emit() *ExecutionResponse{
  return &ExecutionResponse{
    ExecutionOutcome: p.obj.ExecutionOutcome,
    LatencyInUs: p.obj.LatencyInUs,
  }
}

func (e *ExecutionResponseBuilder) ExecutionOutcome(executionOutcome *ExecutionOutcome) *ExecutionResponseBuilder {
  e.obj.ExecutionOutcome = executionOutcome
  return e
}

func (e *ExecutionResponseBuilder) LatencyInUs(latencyInUs int64) *ExecutionResponseBuilder {
  e.obj.LatencyInUs = latencyInUs
  return e
}

func (e *ExecutionResponse) SetExecutionOutcome(executionOutcome *ExecutionOutcome) *ExecutionResponse {
  e.ExecutionOutcome = executionOutcome
  return e
}

func (e *ExecutionResponse) SetLatencyInUs(latencyInUs int64) *ExecutionResponse {
  e.LatencyInUs = latencyInUs
  return e
}

func (p *ExecutionResponse) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetExecutionOutcome bool = false;
  var issetLatencyInUs bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetExecutionOutcome = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetLatencyInUs = true
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetExecutionOutcome{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ExecutionOutcome is not set"));
  }
  if !issetLatencyInUs{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field LatencyInUs is not set"));
  }
  return nil
}

func (p *ExecutionResponse)  ReadField1(iprot thrift.Protocol) error {
  p.ExecutionOutcome = NewExecutionOutcome()
  if err := p.ExecutionOutcome.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ExecutionOutcome), err)
  }
  return nil
}

func (p *ExecutionResponse)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.LatencyInUs = v
  }
  return nil
}

func (p *ExecutionResponse) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("ExecutionResponse"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ExecutionResponse) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("executionOutcome", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:executionOutcome: ", p), err) }
  if err := p.ExecutionOutcome.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ExecutionOutcome), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:executionOutcome: ", p), err) }
  return err
}

func (p *ExecutionResponse) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("latencyInUs", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:latencyInUs: ", p), err) }
  if err := oprot.WriteI64(int64(p.LatencyInUs)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.latencyInUs (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:latencyInUs: ", p), err) }
  return err
}

func (p *ExecutionResponse) String() string {
  if p == nil {
    return "<nil>"
  }

  var executionOutcomeVal string
  if p.ExecutionOutcome == nil {
    executionOutcomeVal = "<nil>"
  } else {
    executionOutcomeVal = fmt.Sprintf("%v", p.ExecutionOutcome)
  }
  latencyInUsVal := fmt.Sprintf("%v", p.LatencyInUs)
  return fmt.Sprintf("ExecutionResponse({ExecutionOutcome:%s LatencyInUs:%s})", executionOutcomeVal, latencyInUsVal)
}

// Attributes:
//  - Username
//  - Password
//  - ClientType
//  - ClientVersion
type AuthReq struct {
  Username []byte `thrift:"username,1,required" db:"username" json:"username"`
  Password []byte `thrift:"password,2,required" db:"password" json:"password"`
  ClientType []byte `thrift:"client_type,3,required" db:"client_type" json:"client_type"`
  ClientVersion []byte `thrift:"client_version,4,required" db:"client_version" json:"client_version"`
}

func NewAuthReq() *AuthReq {
  return &AuthReq{}
}


func (p *AuthReq) GetUsername() []byte {
  return p.Username
}

func (p *AuthReq) GetPassword() []byte {
  return p.Password
}

func (p *AuthReq) GetClientType() []byte {
  return p.ClientType
}

func (p *AuthReq) GetClientVersion() []byte {
  return p.ClientVersion
}
type AuthReqBuilder struct {
  obj *AuthReq
}

func NewAuthReqBuilder() *AuthReqBuilder{
  return &AuthReqBuilder{
    obj: NewAuthReq(),
  }
}

func (p AuthReqBuilder) Emit() *AuthReq{
  return &AuthReq{
    Username: p.obj.Username,
    Password: p.obj.Password,
    ClientType: p.obj.ClientType,
    ClientVersion: p.obj.ClientVersion,
  }
}

func (a *AuthReqBuilder) Username(username []byte) *AuthReqBuilder {
  a.obj.Username = username
  return a
}

func (a *AuthReqBuilder) Password(password []byte) *AuthReqBuilder {
  a.obj.Password = password
  return a
}

func (a *AuthReqBuilder) ClientType(clientType []byte) *AuthReqBuilder {
  a.obj.ClientType = clientType
  return a
}

func (a *AuthReqBuilder) ClientVersion(clientVersion []byte) *AuthReqBuilder {
  a.obj.ClientVersion = clientVersion
  return a
}

func (a *AuthReq) SetUsername(username []byte) *AuthReq {
  a.Username = username
  return a
}

func (a *AuthReq) SetPassword(password []byte) *AuthReq {
  a.Password = password
  return a
}

func (a *AuthReq) SetClientType(clientType []byte) *AuthReq {
  a.ClientType = clientType
  return a
}

func (a *AuthReq) SetClientVersion(clientVersion []byte) *AuthReq {
  a.ClientVersion = clientVersion
  return a
}

func (p *AuthReq) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetUsername bool = false;
  var issetPassword bool = false;
  var issetClientType bool = false;
  var issetClientVersion bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetUsername = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetPassword = true
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
      issetClientType = true
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
      issetClientVersion = true
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetUsername{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Username is not set"));
  }
  if !issetPassword{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Password is not set"));
  }
  if !issetClientType{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ClientType is not set"));
  }
  if !issetClientVersion{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ClientVersion is not set"));
  }
  return nil
}

func (p *AuthReq)  ReadField1(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 1: ", err)
  } else {
    p.Username = v
  }
  return nil
}

func (p *AuthReq)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Password = v
  }
  return nil
}

func (p *AuthReq)  ReadField3(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 3: ", err)
  } else {
    p.ClientType = v
  }
  return nil
}

func (p *AuthReq)  ReadField4(iprot thrift.Protocol) error {
  if v, err := iprot.ReadBinary(); err != nil {
    return thrift.PrependError("error reading field 4: ", err)
  } else {
    p.ClientVersion = v
  }
  return nil
}

func (p *AuthReq) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("AuthReq"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := p.writeField3(oprot); err != nil { return err }
  if err := p.writeField4(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *AuthReq) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("username", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:username: ", p), err) }
  if err := oprot.WriteBinary(p.Username); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.username (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:username: ", p), err) }
  return err
}

func (p *AuthReq) writeField2(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("password", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:password: ", p), err) }
  if err := oprot.WriteBinary(p.Password); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.password (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:password: ", p), err) }
  return err
}

func (p *AuthReq) writeField3(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("client_type", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:client_type: ", p), err) }
  if err := oprot.WriteBinary(p.ClientType); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.client_type (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:client_type: ", p), err) }
  return err
}

func (p *AuthReq) writeField4(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("client_version", thrift.STRING, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:client_version: ", p), err) }
  if err := oprot.WriteBinary(p.ClientVersion); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.client_version (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:client_version: ", p), err) }
  return err
}

func (p *AuthReq) String() string {
  if p == nil {
    return "<nil>"
  }

  usernameVal := fmt.Sprintf("%v", p.Username)
  passwordVal := fmt.Sprintf("%v", p.Password)
  clientTypeVal := fmt.Sprintf("%v", p.ClientType)
  clientVersionVal := fmt.Sprintf("%v", p.ClientVersion)
  return fmt.Sprintf("AuthReq({Username:%s Password:%s ClientType:%s ClientVersion:%s})", usernameVal, passwordVal, clientTypeVal, clientVersionVal)
}

// Attributes:
//  - GqlStatus
//  - Identifier
type AuthResponse struct {
  GqlStatus *GQLStatus `thrift:"gqlStatus,1,required" db:"gqlStatus" json:"gqlStatus"`
  Identifier *int64 `thrift:"identifier,2,optional" db:"identifier" json:"identifier,omitempty"`
}

func NewAuthResponse() *AuthResponse {
  return &AuthResponse{
    GqlStatus: NewGQLStatus(),
  }
}

var AuthResponse_GqlStatus_DEFAULT *GQLStatus
func (p *AuthResponse) GetGqlStatus() *GQLStatus {
  if !p.IsSetGqlStatus() {
    return AuthResponse_GqlStatus_DEFAULT
  }
return p.GqlStatus
}
var AuthResponse_Identifier_DEFAULT int64
func (p *AuthResponse) GetIdentifier() int64 {
  if !p.IsSetIdentifier() {
    return AuthResponse_Identifier_DEFAULT
  }
return *p.Identifier
}
func (p *AuthResponse) IsSetGqlStatus() bool {
  return p != nil && p.GqlStatus != nil
}

func (p *AuthResponse) IsSetIdentifier() bool {
  return p != nil && p.Identifier != nil
}

type AuthResponseBuilder struct {
  obj *AuthResponse
}

func NewAuthResponseBuilder() *AuthResponseBuilder{
  return &AuthResponseBuilder{
    obj: NewAuthResponse(),
  }
}

func (p AuthResponseBuilder) Emit() *AuthResponse{
  return &AuthResponse{
    GqlStatus: p.obj.GqlStatus,
    Identifier: p.obj.Identifier,
  }
}

func (a *AuthResponseBuilder) GqlStatus(gqlStatus *GQLStatus) *AuthResponseBuilder {
  a.obj.GqlStatus = gqlStatus
  return a
}

func (a *AuthResponseBuilder) Identifier(identifier *int64) *AuthResponseBuilder {
  a.obj.Identifier = identifier
  return a
}

func (a *AuthResponse) SetGqlStatus(gqlStatus *GQLStatus) *AuthResponse {
  a.GqlStatus = gqlStatus
  return a
}

func (a *AuthResponse) SetIdentifier(identifier *int64) *AuthResponse {
  a.Identifier = identifier
  return a
}

func (p *AuthResponse) Read(iprot thrift.Protocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetGqlStatus bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetGqlStatus = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetGqlStatus{
    return thrift.NewProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field GqlStatus is not set"));
  }
  return nil
}

func (p *AuthResponse)  ReadField1(iprot thrift.Protocol) error {
  p.GqlStatus = NewGQLStatus()
  if err := p.GqlStatus.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.GqlStatus), err)
  }
  return nil
}

func (p *AuthResponse)  ReadField2(iprot thrift.Protocol) error {
  if v, err := iprot.ReadI64(); err != nil {
    return thrift.PrependError("error reading field 2: ", err)
  } else {
    p.Identifier = &v
  }
  return nil
}

func (p *AuthResponse) Write(oprot thrift.Protocol) error {
  if err := oprot.WriteStructBegin("AuthResponse"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if err := p.writeField1(oprot); err != nil { return err }
  if err := p.writeField2(oprot); err != nil { return err }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *AuthResponse) writeField1(oprot thrift.Protocol) (err error) {
  if err := oprot.WriteFieldBegin("gqlStatus", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:gqlStatus: ", p), err) }
  if err := p.GqlStatus.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.GqlStatus), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:gqlStatus: ", p), err) }
  return err
}

func (p *AuthResponse) writeField2(oprot thrift.Protocol) (err error) {
  if p.IsSetIdentifier() {
    if err := oprot.WriteFieldBegin("identifier", thrift.I64, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:identifier: ", p), err) }
    if err := oprot.WriteI64(int64(*p.Identifier)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.identifier (2) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:identifier: ", p), err) }
  }
  return err
}

func (p *AuthResponse) String() string {
  if p == nil {
    return "<nil>"
  }

  var gqlStatusVal string
  if p.GqlStatus == nil {
    gqlStatusVal = "<nil>"
  } else {
    gqlStatusVal = fmt.Sprintf("%v", p.GqlStatus)
  }
  var identifierVal string
  if p.Identifier == nil {
    identifierVal = "<nil>"
  } else {
    identifierVal = fmt.Sprintf("%v", *p.Identifier)
  }
  return fmt.Sprintf("AuthResponse({GqlStatus:%s Identifier:%s})", gqlStatusVal, identifierVal)
}

