name=local-nebula-sink
connector.class=com.vesoft.nebula.connector.sink.NebulaSinkConnector
tasks.max=1
topics=connect-test

nebula.graph.servers=192.168.8.6:3820
nebula.user=root
nebula.passwd=nebula
nebula.graph.name=test_graph
nebula.data.type=NODE
nebula.node.type=Person
nebula.node.primaryKey=id
nebula.node.property.names=name,age,gender
kafka.node.property.names=a,b,c
nebula.sink.batchSize=1
nebula.sink.mode=insert
nebula.healthCheckTime=600000
nebula.blockWhenExhausted=true
nebula.maxWaitMills=30000
nebula.strictlyServerHealthy=true


key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
