version: '3'
services:
  metad0: &metad
    image: ${IMAGE_GROUP}/nebula-metad:${IMAGE_VERSION}
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9559
      - --data_path=/data/meta
      - --local_ip=metad0
      - --containerized=true
    # healthcheck:
    #   test: ["CMD", "curl", "-sf", "http://${NAME}:19559/status"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s
    ports:
      - 9559
      - 19559
      - 19560
    volumes:
      - ./data/metad0:/data/meta
      - ./logs/metad0:/usr/local/nebula/logs
    networks:
      - nebula-ng
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  metad1:
    <<: *metad
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9559
      - --data_path=/data/meta
      - --local_ip=metad1
      - --containerized=true
    volumes:
      - ./data/metad1:/data/meta
      - ./logs/metad1:/usr/local/nebula/logs

  metad2:
    <<: *metad
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9559
      - --data_path=/data/meta
      - --local_ip=metad2
      - --containerized=true
    volumes:
      - ./data/metad2:/data/meta
      - ./logs/metad2:/usr/local/nebula/logs

  storaged0: &storaged
    image: ${IMAGE_GROUP}/nebula-storaged:${IMAGE_VERSION}
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9779
      - --data_path=/data/storage
      - --local_ip=storaged0
      - --containerized=true
      - --dynamic_memory_reserved_gib=0
    depends_on:
      - metad0
      - metad1
      - metad2
    # healthcheck:
    #   test: ["CMD", "curl", "-sf", "http://${NAME}:19779/status"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s
    ports:
      - 9779
      - 19779
    volumes:
      - ./data/storaged0:/data/storage
      - ./logs/storaged0:/usr/local/nebula/logs
    networks:
      - nebula-ng
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G

  storaged1:
    <<: *storaged
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9779
      - --data_path=/data/storage
      - --local_ip=storaged1
      - --containerized=true
      - --dynamic_memory_reserved_gib=0
    volumes:
      - ./data/storaged1:/data/storage
      - ./logs/storaged1:/usr/local/nebula/logs

  storaged2:
    <<: *storaged
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9779
      - --data_path=/data/storage
      - --local_ip=storaged2
      - --containerized=true
      - --dynamic_memory_reserved_gib=0
    volumes:
      - ./data/storaged2:/data/storage
      - ./logs/storaged2:/usr/local/nebula/logs

  graphd0: &graphd
    image: ${IMAGE_GROUP}/nebula-graphd:${IMAGE_VERSION}
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd0
      - --containerized=true
      - --dynamic_memory_reserved_gib=0
    depends_on:
      - storaged0
      - storaged1
      - storaged2
    # healthcheck:
    #   test: ["CMD", "curl", "-sf", "http://graphd:19669/status"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s
    ports:
      - "9669:9669"
      - 19669
      - 19670
    volumes:
      - ./logs/graphd0:/usr/local/nebula/logs
    networks:
      - nebula-ng
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G

  graphd1:
    <<: *graphd
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd1
      - --containerized=true
      - --dynamic_memory_reserved_gib=0
    ports:
      - "9670:9669"
      - 19669
      - 19670
    volumes:
      - ./logs/graphd1:/usr/local/nebula/logs

  graphd2:
    <<: *graphd
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd2
      - --containerized=true
      - --dynamic_memory_reserved_gib=0
    ports:
      - "9671:9669"
      - 19669
      - 19670
    volumes:
      - ./logs/graphd2:/usr/local/nebula/logs
  
  console:
    image: ${IMAGE_GROUP}/ngctl:${IMAGE_VERSION}
    entrypoint: ""
    command: 
      - sh
      - -c
      - |
        for i in `seq 1 20`;do
          ngctl auth passwd -H metad0 -P 9559 -u root -c nebula -p NebulaGraph01 > /dev/null 2>&1
          if [[ $$? == 0 ]];then
            break;
          fi;
          sleep 1;
          echo "retry to connect metad0";
        done ;
        ngctl auth login -H metad0 -P 9559 -u root  -p NebulaGraph01
        ngctl svcgrp create my_cluster1 --replica-factor 3
        for i in `seq 0 2`;do
          ngctl svcgrp add-host my_cluster1 -H graphd$${i} 
          ngctl svcgrp add-host my_cluster1 -H storaged$${i} 
          ngctl svcgrp add-service my_cluster1 --type graphd -H graphd$${i} --port 9669
          ngctl svcgrp add-service my_cluster1 --type storaged -H storaged$${i} --port 9779
        done;
        ngctl svcgrp init my_cluster1
        tail -f /dev/null;

    depends_on:
      - metad0
      - metad1
      - metad2  
    networks:
      - nebula-ng

networks:
  nebula-ng:
