// Copyright (c) 2022 vesoft inc. All rights reserved.

#ifndef COMMON_DATATYPE_BINDINGTABLE_H_
#define COMMON_DATATYPE_BINDINGTABLE_H_

#include <cassert>
#include <deque>

#include "common/datatype/Record.h"

namespace nebula::client {

class BindingTableDescriptor final {
public:
    using allocator_type = std::pmr::polymorphic_allocator<std::byte>;
    allocator_type get_allocator() const noexcept {
        return recordType_.get_allocator();
    }

    explicit BindingTableDescriptor(const allocator_type& alloc = allocator_type())
            : recordType_(alloc) {}

    explicit BindingTableDescriptor(const RecordType& recordType,
                                    bool ordered = false,
                                    bool duplicateFree = false,
                                    const allocator_type& alloc = allocator_type())
            : recordType_(recordType, alloc),
              ordered_(ordered),
              duplicateFree_(duplicateFree) {}

    explicit BindingTableDescriptor(const std::vector<std::string>& columnNames,
                                    bool ordered = false,
                                    bool duplicateFree = false,
                                    const allocator_type& alloc = allocator_type())
            : recordType_(columnNames, alloc),
              ordered_(ordered),
              duplicateFree_(duplicateFree) {}

    BindingTableDescriptor(const BindingTableDescriptor& other, const allocator_type& alloc)
            : recordType_(other.recordType_, alloc),
              ordered_(other.ordered_),
              duplicateFree_(other.duplicateFree_) {}

    BindingTableDescriptor(BindingTableDescriptor&& other, const allocator_type& alloc)
            : recordType_(std::move(other.recordType_), alloc),
              ordered_(other.ordered_),
              duplicateFree_(other.duplicateFree_) {}


    const RecordType& getRecordType() const {
        return recordType_;
    }

    void setRecordType(const RecordType& recordType) {
        recordType_ = recordType;
    }

    bool isOrdered() const {
        return ordered_;
    }

    void setOrdered(bool ordered) {
        ordered_ = ordered;
    }

    bool isDuplicateFree() const {
        return duplicateFree_;
    }
    void setDuplicateFree(bool duplicateFree) {
        duplicateFree_ = duplicateFree;
    }

    void clear() {
        recordType_.clear();
        ordered_ = false;
        duplicateFree_ = false;
    }

private:
    // Serialization using fbthrift
    friend class apache::thrift::Cpp2Ops<BindingTableDescriptor, void>;

    // Record type of the binding table.
    // It could be explicitly defined by the user or inferred from the schema,
    // and maybe changed during the building of the binding table.
    RecordType recordType_;
    // An indication whether the binding table is declared as ordered or as unordered.
    // eg. The binding table generated by a sort executor should be declared as ordered.
    bool ordered_{false};
    // An indication whether the binding table is declared as duplicate-free or as allowing
    // duplicates. A duplicate-free binding table shall not contain duplicates of the same
    // record, that is it either contains some arbitrary record R of its declared record type
    // exactly once or it does not contain R at all.
    // eg. The binding table generated by a distinct executor should be declared as
    // duplicate-free.
    bool duplicateFree_{false};
    // An optional preferred column sequence that is a permutation of the column names of the
    // binding table.
    // std::optional<PreferredColumnSequence> preferredColumnSequence_;
};

bool operator==(const BindingTableDescriptor& lhs, const BindingTableDescriptor& rhs);
bool operator!=(const BindingTableDescriptor& lhs, const BindingTableDescriptor& rhs);

// class BindingTable
// class RpcBindingTable : public BindingTable
// class MemBindingTable : public BindingTable

// Every batch is a BindingTable.
// Binding table stores a lot of RawRecords.
class BindingTable final {
public:
    using allocator_type = std::pmr::polymorphic_allocator<std::byte>;
    allocator_type get_allocator() const noexcept {
        return desc_.get_allocator();
    }

    template <typename... Args>
    static BindingTable* make(allocator_type alloc, Args&&... args) {
        void* mem = alloc.resource()->allocate(sizeof(BindingTable), alignof(BindingTable));
        return ::new (mem) BindingTable(alloc, std::forward<Args>(args)...);
    }

    explicit BindingTable(const allocator_type& alloc = allocator_type())
            : desc_(alloc), records_(alloc) {}
    explicit BindingTable(const BindingTableDescriptor& desc,
                          const allocator_type& alloc = allocator_type())
            : desc_(desc, alloc), records_(alloc) {}

    const BindingTableDescriptor& getDescriptor() const {
        return desc_;
    }

    const std::pmr::deque<RawRecord>& getRecords() const {
        return records_;
    }

    // Get the record at the given index with bounding check.
    const RawRecord& at(size_t index) const {
        // CHECK_LT(index, records_.size());
        assert(index < records_.size());
        return records_.at(index);
    }

    // Get the record at the given index.
    const RawRecord& operator[](size_t index) const {
        return records_[index];
    }

    size_t getNumRecords() const {
        return records_.size();
    }

    // Append a new record to the end of the binding table.
    template <class... Args>
    RawRecord& emplace(Args&&... args) {
        auto& newRecord = records_.emplace_back(std::forward<Args>(args)...);
        newRecord.reserve(desc_.getRecordType().getNumFieldTypes());
        return newRecord;
    }
    void append(const RawRecord& record) {
        records_.emplace_back(record);
    }
    void append(RawRecord&& record) {
        records_.emplace_back(std::move(record));
    }

    // Merge another binding table
    void merge(const BindingTable& other) {
        records_.insert(records_.end(), other.records_.begin(), other.records_.end());
    }

    auto& records() {
        return records_;
    }

    // Reuse the binding table memory in place
    void reset() {
        // FIXME(yee)
    }

    void __clear() {
        records_.clear();
    }

    void clear() {
        records_.clear();
    }

private:
    // Serialization using fbthrift
    friend class apache::thrift::Cpp2Ops<BindingTable, void>;

    BindingTableDescriptor desc_;
    std::pmr::deque<RawRecord> records_;
};

bool operator==(const BindingTable& lhs, const BindingTable& rhs);
bool operator!=(const BindingTable& lhs, const BindingTable& rhs);

}  // namespace nebula::client

#endif  // COMMON_DATATYPE_BINDINGTABLE_H_
