<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vesoft</groupId>
    <artifactId>nebula</artifactId>
    <version>5.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>client</module>
        <module>examples</module>
    </modules>

    <!-- More Project Information -->
    <name>nebula-java</name>
    <description>Nebula Java Client 5.0</description>
    <url>https://github.com/vesoft-inc/nebula-ng-tools</url>
    <scm>
        <connection>scm:git:https://github.com/vesoft-inc/nebula-ng-tools</connection>
        <url>https://github.com/vesoft-inc/nebula-ng-tools</url>
        <developerConnection>scm:git:https://github.com/vesoft-inc/nebula-ng-tools</developerConnection>
    </scm>


    <developers>
        <developer>
            <id>nebula</id>
            <name>Nebula Graph</name>
            <email>nebula-java@vesoft-inc.com</email>
            <organization>vesoft</organization>
            <roles>
                <role>architect</role>
                <role>developer</role>
            </roles>
        </developer>
    </developers>

    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.7</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
