<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vesoft</groupId>
    <artifactId>nebula</artifactId>
    <version>5.0.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>client</module>
        <module>examples</module>
    </modules>

    <!-- More Project Information -->
    <name>nebula-java</name>
    <description>Nebula Java Client 5.0</description>
    <url>https://github.com/vesoft-inc/nebula-java</url>
    <scm>
        <connection>scm:git:https://github.com/vesoft-inc/nebula-java</connection>
        <url>https://github.com/vesoft-inc/nebula-java</url>
        <developerConnection>scm:git:https://github.com/vesoft-inc/nebula-java</developerConnection>
    </scm>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>license</comments>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>nebula</id>
            <name>Nebula Graph</name>
            <email>nebula-java@vesoft-inc.com</email>
            <organization>vesoft</organization>
            <roles>
                <role>architect</role>
                <role>developer</role>
            </roles>
        </developer>
    </developers>

</project>
