# permissions for end users to edit nebulametads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nebulametad-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: nebulametad-editor-role
rules:
- apiGroups:
  - apps.nebula-graph-ng.io
  resources:
  - nebulametads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nebula-graph-ng.io
  resources:
  - nebulametads/status
  verbs:
  - get
