version: 1.0
kind: NebulaCluster
rollback: true
installPath: /home/xuntao.cheng/demo/vesoft
certFile: certs/client.crt
keyFile: certs/client.key
caFile: certs/ca.crt
spec:
  metad:
    packagePath: /home/xuntao.cheng/demo/nebula-graph-5.0.0-x86_64-glibc-2.31.sh
    hosts:
      - host:
        ip: "127.0.0.1"
        port: 49559
        agentPort: 6688
        agents:
          host: "127.0.0.1:6688"
    srvgrps:
      - zoneList: [zone1]
        name: testsrvgrp
        replica: 1
        graphd:
          hosts:
            - host:
              ip: "127.0.0.1"
              port: 49669
              agentPort: 6688
              agents:
                host: "127.0.0.1:6688"
        storaged:
          hosts:
            - host:
              ip: "127.0.0.1"
              port: 49779
              agentPort: 6688
              agents:
                host: "127.0.0.1:6688"
