name=local-nebula-sink
connector.class=com.vesoft.nebula.connector.sink.NebulaSinkConnector
tasks.max=1
topics=connect-test

nebula.graph.servers=192.168.8.6:3820
nebula.user=root
nebula.passwd=Nebula123
nebula.authOptions={password:Nebula123}
nebula.graph.name=nba
nebula.data.type=NODE
nebula.node.typeName=node_type_player
nebula.node.primaryKeys=id
kafka.node.primaryKeys=id
nebula.node.property.names=id,name,score,gender,rate
kafka.node.property.names=id,name,score,gender,rate
nebula.batchSize=1
nebula.sink.mode=INSERT

nebula.request.timeout=5000
nebula.sin.partitions=10
nebula.healthCheckTime=600000
nebula.blockWhenExhausted=true
nebula.maxWaitMills=30000
nebula.strictlyServerHealthy=true

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
