/*
Copyright 2023 Vesoft Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v2alpha1

import (
	corev1 "k8s.io/api/core/v1"
)

// ComponentPhase is the current state of component
type ComponentPhase string

const (
	// RunningPhase represents running state of nebula cluster.
	RunningPhase ComponentPhase = "Running"
	// ScaleInPhase represents the scaling state of nebula cluster.
	ScaleInPhase ComponentPhase = "ScaleIn"
	// ScaleOutPhase represents the scaling state of nebula cluster.
	ScaleOutPhase ComponentPhase = "ScaleOut"
	// UpdatePhase represents update state of nebula cluster.
	UpdatePhase ComponentPhase = "Update"
	// SuspendPhase represents the suspend state of nebula cluster.
	SuspendPhase ComponentPhase = "Suspend"
)

// ComponentSpec is a common set of k8s resource configs for nebula components.
type ComponentSpec struct {
	// K8S deployment replicas setting.
	// +kubebuilder:validation:Minimum=1
	Replicas *int32 `json:"replicas,omitempty"`

	// K8S resources settings.
	// +optional
	Resources *corev1.ResourceRequirements `json:"resources,omitempty"`

	// Container environment variables.
	// +optional
	EnvVars []corev1.EnvVar `json:"env,omitempty"`

	// Container image.
	Image string `json:"image"`

	// Version is tag for container image.
	// +kubebuilder:default=latest
	// +optional
	Version string `json:"version,omitempty"`

	// K8S pod annotations.
	// +optional
	Annotations map[string]string `json:"annotations,omitempty"`

	// +optional
	Labels map[string]string `json:"labels,omitempty"`

	// +optional
	SchedulerName *string `json:"schedulerName,omitempty"`

	// K8S nodeSelector.
	// +optional
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`

	// +optional
	Affinity *corev1.Affinity `json:"affinity,omitempty"`

	// +optional
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`

	// +optional
	TopologySpreadConstraints []TopologySpreadConstraint `json:"topologySpreadConstraints,omitempty"`

	// +optional
	SecurityContext *corev1.SecurityContext `json:"securityContext,omitempty"`

	// +optional
	InitContainers []corev1.Container `json:"initContainers,omitempty"`

	// +optional
	SidecarContainers []corev1.Container `json:"sidecarContainers,omitempty"`

	// +optional
	Volumes []corev1.Volume `json:"volumes,omitempty"`

	// +optional
	VolumeMounts []corev1.VolumeMount `json:"volumeMounts,omitempty"`

	// +optional
	ReadinessProbe *corev1.Probe `json:"readinessProbe,omitempty"`

	// +optional
	LivenessProbe *corev1.Probe `json:"livenessProbe,omitempty"`
}

type TopologySpreadConstraint struct {
	// TopologyKey is the key of node labels. Nodes that have a label with this key
	// and identical values are considered to be in the same topology.
	// We consider each <key, value> as a "bucket", and try to put balanced number
	// of pods into each bucket.
	// MaxSkew is default set to 1
	// LabelSelector is generated by component type
	TopologyKey string `json:"topologyKey"`

	WhenUnsatisfiable corev1.UnsatisfiableConstraintAction `json:"whenUnsatisfiable"`
}

// ServiceSpec is a common set of k8s service configs.
type ServiceSpec struct {
	Type corev1.ServiceType `json:"type,omitempty"`

	// +optional
	Annotations map[string]string `json:"annotations,omitempty"`

	// +optional
	Selector map[string]string `json:"selector,omitempty"`

	// ClusterIP is the clusterIP of service
	// +optional
	ClusterIP *string `json:"clusterIP,omitempty"`

	// +optional
	PublishNotReadyAddresses bool `json:"publishNotReadyAddresses,omitempty"`
}

// WorkloadStatus describes the status of a specified workload.
type WorkloadStatus struct {
	// ObservedGeneration is the most recent generation observed for this Workload. It corresponds to the
	// Workload's generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// ReadyReplicas is the number of pods with a Ready Condition.
	// +optional
	ReadyReplicas int32 `json:"readyReplicas,omitempty"`

	// Replicas is the number of pods created by the Workload controller.
	Replicas int32 `json:"replicas"`

	// The number of pods in updatedRevision.
	UpdatedReplicas int32 `json:"updatedReplicas"`

	// The number of pods in currentRevision.
	CurrentReplicas int32 `json:"currentReplicas,omitempty"`

	// Count of hash collisions for the Workload.
	// +optional
	CollisionCount *int32 `json:"collisionCount,omitempty"`

	// CurrentRevision, if not empty, indicates the current version of the Workload.
	CurrentRevision string `json:"currentRevision"`

	// UpdateRevision, if not empty, indicates the version of the Workload used to generate Pods in the sequence
	UpdateRevision string `json:"updateRevision,omitempty"`

	// Total number of available pods.
	// +optional
	AvailableReplicas int32 `json:"availableReplicas"`
}

// NamespacedObjectReference contains enough information to let you locate
// the referenced object in any namespace
type NamespacedObjectReference struct {
	// Name of the referent
	// +required
	Name string `json:"name"`

	// Namespace of the referent
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// VolumeStatus describes the observed state of volumes.
type VolumeStatus struct {
	ProvisionedVolumes map[string]ProvisionedVolume `json:"provisionedVolumes,omitempty"`

	// All volumes have been provisioned with the desired resources.
	ProvisionedDone bool `json:"provisionedDone"`
}

// ProvisionedVolume describes the status of a specified PVC.
type ProvisionedVolume struct {
	VolumeName string `json:"volumeName"`

	StorageClass string `json:"storageClass"`

	Capacity string `json:"capacity"`
}

type SSLCertsSpec struct {
	// Name of the server cert secret
	ServerSecret string `json:"serverSecret,omitempty"`
	// The key to server PEM encoded public key certificate
	// +optional
	ServerCert string `json:"serverCert,omitempty"`
	// The key to server private key associated with given certificate
	// +optional
	ServerKey string `json:"serverKey,omitempty"`

	// Name of the client cert secret
	ClientSecret string `json:"clientSecret,omitempty"`
	// The key to client PEM encoded public key certificate
	// +optional
	ClientCert string `json:"clientCert,omitempty"`
	// The key to client private key associated with given certificate
	// +optional
	ClientKey string `json:"clientKey,omitempty"`

	// Name of the CA cert secret
	CASecret string `json:"caSecret,omitempty"`
	// The key to CA PEM encoded public key certificate
	// +optional
	CACert string `json:"caCert,omitempty"`

	// Name of the client CA cert secret
	ClientCASecret string `json:"clientCASecret,omitempty"`
	// The key to Client CA PEM encoded public key certificate
	// +optional
	ClientCACert string `json:"clientCACert,omitempty"`

	// InsecureSkipVerify controls whether a client verifies the server's
	// certificate chain and host name.
	// +optional
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`

	// ServerName is used to verify the hostname on the returned
	// certificates unless InsecureSkipVerify is given. It is also included
	// in the client's handshake to support virtual hosting unless it is
	// an IP address.
	// +optional
	ServerName string `json:"serverName,omitempty"`

	// AutoMountServerCerts controls whether operator mounts server's
	// certificate from secret.
	// +optional
	AutoMountServerCerts *bool `json:"autoMountServerCerts,omitempty"`
}
