
name=local-nebula-sink
connector.class=com.vesoft.nebula.connector.sink.NebulaSinkConnector
tasks.max=1
topics=connect-test

nebula.graph.servers=127.0.0.1:9669
nebula.user=root
nebula.passwd=Nebula123
nebula.authOptions={password:Nebula123}
nebula.graph.name=test
nebula.data.type=NODE
nebula.node.typeName=person
nebula.node.primaryKey=id
nebula.node.property.names=id,name,age
kafka.node.property.names=id,name,age
nebula.batchSize=1
nebula.sink.mode=INSERT

nebula.request.timeout=5000
nebula.sin.partitions=10

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
