// Copyright (c) 2022 vesoft inc. All rights reserved.

package nebula_ng_go

import (
	"crypto/tls"
	"fmt"
	"math"
	"time"

	"github.com/facebook/fbthrift/thrift/lib/go/thrift"
	"github.com/vesoft-inc/nebula-ng/go/pkg/generated_code/v5.0.0/nebula/graph"
)

// TODO(Aiee) add scheduler to release idle connection periodically
// connection represents a connection to a graph server
type connection struct {
	severAddress HostAddress // graph server address
	timeout      time.Duration
	returnedAt   time.Time // the connection was created or returned.
	sslConfig    *tls.Config
	graphService *graph.GraphServiceClient // raw connection provided by thrift
	// service version that used to support backward compatibility
}

// TODO(Aiee) make this method exported for demo only
func NewConnection(severAddress HostAddress) *connection {
	return &connection{
		severAddress: severAddress,
		timeout:      0 * time.Millisecond,
		returnedAt:   time.Now(),
		sslConfig:    nil,
		graphService: nil,
	}
}

// open opens a transport for the connection
// if sslConfig is not nil, an SSL transport will be created
func (cn *connection) Open(hostAddress HostAddress, timeout time.Duration, sslConfig *tls.Config) error {
	ip := hostAddress.Host
	port := hostAddress.Port
	newAdd := fmt.Sprintf("%s:%d", ip, port)
	cn.timeout = timeout
	bufferSize := 128 << 10
	// TODO(Aiee) delete when change to compact protocol
	frameMaxLength := uint32(math.MaxUint32)

	var err error
	var sock thrift.Transport
	if sslConfig != nil {
		sock, err = thrift.NewSSLSocketTimeout(newAdd, sslConfig, timeout)
	} else {
		sock, err = thrift.NewSocket(thrift.SocketAddr(newAdd), thrift.SocketTimeout(timeout))
	}
	if err != nil {
		return fmt.Errorf("failed to create a net.Conn-backed Transport,: %s", err.Error())
	}

	// Set transport buffer
	bufferedTranFactory := thrift.NewBufferedTransportFactory(bufferSize)
	transport := thrift.NewFramedTransportMaxLength(bufferedTranFactory.GetTransport(sock), frameMaxLength)
	pf := thrift.NewBinaryProtocolFactoryDefault()
	cn.graphService = graph.NewGraphServiceClientFactory(transport, pf)
	if err = cn.graphService.Open(); err != nil {
		return fmt.Errorf("failed to open transport, error: %s", err.Error())
	}
	if !cn.graphService.IsOpen() {
		return fmt.Errorf("transport is off")
	}
	return nil
}

// reopen reopens the current connection.
// Because the code generated by fbthrift does not handle the seqID,
// the message will be dislocated when the timeout occurs, resulting in unexpected response.
// When the timeout occurs, the connection will be reopened to avoid the impact of the message.
func (cn *connection) reopen() error {
	cn.close()
	return cn.Open(cn.severAddress, cn.timeout, cn.sslConfig)
}

// authenticate authenticates a user with a password
func (cn *connection) Authenticate(username, password string) (*graph.AuthResponse, error) {
	// Prepare the request
	authReq := &graph.AuthReq{
		Username:      []byte(username),
		Password:      []byte(password),
		ClientType:    []byte("golang"), // Add a enum in the server side
		ClientVersion: []byte("v5.0.0"),
	}

	// Send the request
	resp, err := cn.graphService.Authenticate(authReq)
	if err != nil {
		err = fmt.Errorf("authentication fails, %s", err.Error())
		if e := cn.graphService.Close(); e != nil {
			err = fmt.Errorf("fail to close transport, error: %s", e.Error())
		}
		return nil, err
	}
	if string(resp.GetGqlStatus().Status) != "SUCCESS" {
		return nil, fmt.Errorf("authentication failed, error: %s", string(resp.GetGqlStatus().Status))
	}
	return resp, err
}

// execute executes a gql query
func (cn *connection) execute(Identifier int64, stmt string) (*graph.ExecutionResponse, error) {
	resp, err := cn.graphService.Execute(Identifier, []byte(stmt))
	if err != nil {
		// reopen the connection if timeout
		if _, ok := err.(thrift.TransportException); ok {
			if err.(thrift.TransportException).TypeID() == thrift.TIMED_OUT {
				reopenErr := cn.reopen()
				if reopenErr != nil {
					return nil, reopenErr
				}
				return cn.graphService.Execute(Identifier, []byte(stmt))
			}
		}
	}

	return resp, err
}

// Check connection to host address
func (cn *connection) ping() bool {
	_, err := cn.execute(0, "YIELD 1")
	return err == nil
}

// Sign out and release session ID
func (cn *connection) signOut(sessionID int64) error {
	// Release session ID to graphd
	return cn.graphService.Signout(sessionID)
}

// Update returnedAt for cleaner
func (cn *connection) release() {
	cn.returnedAt = time.Now()
}

// Close transport
func (cn *connection) close() {
	cn.graphService.Close()
}
