apiVersion: apps.nebula-graph.io/v2alpha1
kind: NebulaMetad
metadata:
  labels:
    app.kubernetes.io/name: nebulametad
    app.kubernetes.io/instance: nebulametad-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: nebulametad-sample
spec:
  # TODO(user): Add fields here
