apiVersion: apps.nebula-graph-ng.io/v1alpha1
kind: NebulaMetad
metadata:
  name: ngmeta
spec:
  credentialSecret: "nebula"
  enablePVReclaim: true
  config:
    "license_manager_url": "192.168.8.53:9119"
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  replicas: 3
  image: reg.vesoft-inc.com/vesoft-ng/nebula-metad
  version: nightly
  dataVolumeClaim:
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
  logVolumeClaim:
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
  schedulerName: default-scheduler
  imagePullPolicy: Always
  imagePullSecrets:
  - name: nebula-image
  topologySpreadConstraints:
  - topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway

