# Configuration snippets may be placed in this directory as well
includedir /etc/krb5.conf.d/

[logging]
 default = FILE:/home/zhuang.miao/hadoop/hadoop-3.2.3/logs/krb5libs.log
 kdc = FILE:/home/zhuang.miao/hadoop/hadoop-3.2.3/logs/krb5kdc.log
 admin_server = FILE:/home/zhuang.miao/hadoop/hadoop-3.2.3/logs/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
# renew_lifetime = 90d
 forwardable = true
 rdns = false
 pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
 default_realm = NEBULA
 #default_ccache_name = KEYRING:persistent:%{uid}

[realms]
  NEBULA = {
   kdc = 192.168.8.240
   admin_server = 192.168.8.240
  }

[domain_realm]
# .example.com = EXAMPLE.COM
# exampl:e.com = EXAMPLE.COM