/**
 * Autogenerated by Thrift for common.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_types_h.h>


#include "common/utils/Types.h"
#include "common/datatype/thriftSerialization/ValueOps-inl.h"
#include "common/datatype/thriftSerialization/ListOps-inl.h"
#include "common/datatype/thriftSerialization/MapOps-inl.h"
#include "common/datatype/thriftSerialization/NodeOps-inl.h"
#include "common/datatype/thriftSerialization/EdgeOps-inl.h"
#include "common/datatype/thriftSerialization/RecordOps-inl.h"
#include "common/datatype/thriftSerialization/BindingTableOps-inl.h"

namespace apache {
namespace thrift {
namespace tag {
struct values;
struct nodeID;
struct nodeTypeID;
struct properties;
struct srcID;
struct dstID;
struct edgeTypeID;
struct rank;
struct properties;
struct boolVal;
struct int8Val;
struct int16Val;
struct int32Val;
struct int64Val;
struct floatVal;
struct doubleVal;
struct stringVal;
struct listVal;
struct mapVal;
struct nodeVal;
struct edgeVal;
struct filedName;
struct valueType;
struct fieldType;
struct fieldNameIndexMap;
struct values;
struct columnNames;
struct records;
} // namespace tag
namespace detail {
#ifndef APACHE_THRIFT_ACCESSOR_values
#define APACHE_THRIFT_ACCESSOR_values
APACHE_THRIFT_DEFINE_ACCESSOR(values);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_nodeID
#define APACHE_THRIFT_ACCESSOR_nodeID
APACHE_THRIFT_DEFINE_ACCESSOR(nodeID);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_nodeTypeID
#define APACHE_THRIFT_ACCESSOR_nodeTypeID
APACHE_THRIFT_DEFINE_ACCESSOR(nodeTypeID);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_properties
#define APACHE_THRIFT_ACCESSOR_properties
APACHE_THRIFT_DEFINE_ACCESSOR(properties);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_srcID
#define APACHE_THRIFT_ACCESSOR_srcID
APACHE_THRIFT_DEFINE_ACCESSOR(srcID);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_dstID
#define APACHE_THRIFT_ACCESSOR_dstID
APACHE_THRIFT_DEFINE_ACCESSOR(dstID);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_edgeTypeID
#define APACHE_THRIFT_ACCESSOR_edgeTypeID
APACHE_THRIFT_DEFINE_ACCESSOR(edgeTypeID);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_rank
#define APACHE_THRIFT_ACCESSOR_rank
APACHE_THRIFT_DEFINE_ACCESSOR(rank);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_properties
#define APACHE_THRIFT_ACCESSOR_properties
APACHE_THRIFT_DEFINE_ACCESSOR(properties);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_boolVal
#define APACHE_THRIFT_ACCESSOR_boolVal
APACHE_THRIFT_DEFINE_ACCESSOR(boolVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_int8Val
#define APACHE_THRIFT_ACCESSOR_int8Val
APACHE_THRIFT_DEFINE_ACCESSOR(int8Val);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_int16Val
#define APACHE_THRIFT_ACCESSOR_int16Val
APACHE_THRIFT_DEFINE_ACCESSOR(int16Val);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_int32Val
#define APACHE_THRIFT_ACCESSOR_int32Val
APACHE_THRIFT_DEFINE_ACCESSOR(int32Val);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_int64Val
#define APACHE_THRIFT_ACCESSOR_int64Val
APACHE_THRIFT_DEFINE_ACCESSOR(int64Val);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_floatVal
#define APACHE_THRIFT_ACCESSOR_floatVal
APACHE_THRIFT_DEFINE_ACCESSOR(floatVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_doubleVal
#define APACHE_THRIFT_ACCESSOR_doubleVal
APACHE_THRIFT_DEFINE_ACCESSOR(doubleVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_stringVal
#define APACHE_THRIFT_ACCESSOR_stringVal
APACHE_THRIFT_DEFINE_ACCESSOR(stringVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_listVal
#define APACHE_THRIFT_ACCESSOR_listVal
APACHE_THRIFT_DEFINE_ACCESSOR(listVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_mapVal
#define APACHE_THRIFT_ACCESSOR_mapVal
APACHE_THRIFT_DEFINE_ACCESSOR(mapVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_nodeVal
#define APACHE_THRIFT_ACCESSOR_nodeVal
APACHE_THRIFT_DEFINE_ACCESSOR(nodeVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_edgeVal
#define APACHE_THRIFT_ACCESSOR_edgeVal
APACHE_THRIFT_DEFINE_ACCESSOR(edgeVal);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_filedName
#define APACHE_THRIFT_ACCESSOR_filedName
APACHE_THRIFT_DEFINE_ACCESSOR(filedName);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_valueType
#define APACHE_THRIFT_ACCESSOR_valueType
APACHE_THRIFT_DEFINE_ACCESSOR(valueType);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_fieldType
#define APACHE_THRIFT_ACCESSOR_fieldType
APACHE_THRIFT_DEFINE_ACCESSOR(fieldType);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_fieldNameIndexMap
#define APACHE_THRIFT_ACCESSOR_fieldNameIndexMap
APACHE_THRIFT_DEFINE_ACCESSOR(fieldNameIndexMap);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_values
#define APACHE_THRIFT_ACCESSOR_values
APACHE_THRIFT_DEFINE_ACCESSOR(values);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_columnNames
#define APACHE_THRIFT_ACCESSOR_columnNames
APACHE_THRIFT_DEFINE_ACCESSOR(columnNames);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_records
#define APACHE_THRIFT_ACCESSOR_records
APACHE_THRIFT_DEFINE_ACCESSOR(records);
#endif
} // namespace detail
} // namespace thrift
} // namespace apache

// BEGIN declare_enums
namespace nebula { namespace cpp2 {

enum class ValueType {
  kNull = 0,
  kBool = 1,
  kInt8 = 2,
  kInt16 = 3,
  kInt32 = 4,
  kInt64 = 5,
  kFloat = 6,
  kDouble = 7,
  kString = 8,
  kList = 9,
  kMap = 10,
  kNode = 11,
  kEdge = 12,
};




enum class ErrorCode {
  SUCCEEDED = 0,
  E_DISCONNECTED = -1,
  E_FAIL_TO_CONNECT = -2,
  E_RPC_FAILURE = -3,
  E_LEADER_CHANGED = -4,
  E_SPACE_NOT_FOUND = -5,
  E_TAG_NOT_FOUND = -6,
  E_EDGE_NOT_FOUND = -7,
  E_INDEX_NOT_FOUND = -8,
  E_EDGE_PROP_NOT_FOUND = -9,
  E_TAG_PROP_NOT_FOUND = -10,
  E_ROLE_NOT_FOUND = -11,
  E_CONFIG_NOT_FOUND = -12,
  E_MACHINE_NOT_FOUND = -13,
  E_ZONE_NOT_FOUND = -14,
  E_LISTENER_NOT_FOUND = -15,
  E_PART_NOT_FOUND = -16,
  E_KEY_NOT_FOUND = -17,
  E_USER_NOT_FOUND = -18,
  E_STATS_NOT_FOUND = -19,
  E_SERVICE_NOT_FOUND = -20,
  E_DRAINER_NOT_FOUND = -21,
  E_DRAINER_CLIENT_NOT_FOUND = -22,
  E_BACKUP_FAILED = -24,
  E_BACKUP_EMPTY_TABLE = -25,
  E_BACKUP_TABLE_FAILED = -26,
  E_PARTIAL_RESULT = -27,
  E_REBUILD_INDEX_FAILED = -28,
  E_INVALID_PASSWORD = -29,
  E_FAILED_GET_ABS_PATH = -30,
  E_BAD_USERNAME_PASSWORD = -1001,
  E_SESSION_INVALID = -1002,
  E_SESSION_TIMEOUT = -1003,
  E_SYNTAX_ERROR = -1004,
  E_EXECUTION_ERROR = -1005,
  E_STATEMENT_EMPTY = -1006,
  E_BAD_PERMISSION = -1008,
  E_SEMANTIC_ERROR = -1009,
  E_TOO_MANY_CONNECTIONS = -1010,
  E_PARTIAL_SUCCEEDED = -1011,
  E_NO_HOSTS = -2001,
  E_EXISTED = -2002,
  E_INVALID_HOST = -2003,
  E_UNSUPPORTED = -2004,
  E_NOT_DROP = -2005,
  E_BALANCER_RUNNING = -2006,
  E_CONFIG_IMMUTABLE = -2007,
  E_CONFLICT = -2008,
  E_INVALID_PARM = -2009,
  E_WRONGCLUSTER = -2010,
  E_LISTENER_CONFLICT = -2011,
  E_ZONE_NOT_ENOUGH = -2012,
  E_ZONE_IS_EMPTY = -2013,
  E_STORE_FAILURE = -2021,
  E_STORE_SEGMENT_ILLEGAL = -2022,
  E_BAD_BALANCE_PLAN = -2023,
  E_BALANCED = -2024,
  E_NO_RUNNING_BALANCE_PLAN = -2025,
  E_NO_VALID_HOST = -2026,
  E_CORRUPTED_BALANCE_PLAN = -2027,
  E_NO_INVALID_BALANCE_PLAN = -2028,
  E_NO_VALID_DRAINER = -2029,
  E_IMPROPER_ROLE = -2030,
  E_INVALID_PARTITION_NUM = -2031,
  E_INVALID_REPLICA_FACTOR = -2032,
  E_INVALID_CHARSET = -2033,
  E_INVALID_COLLATE = -2034,
  E_CHARSET_COLLATE_NOT_MATCH = -2035,
  E_SNAPSHOT_FAILURE = -2040,
  E_BLOCK_WRITE_FAILURE = -2041,
  E_REBUILD_INDEX_FAILURE = -2042,
  E_INDEX_WITH_TTL = -2043,
  E_ADD_JOB_FAILURE = -2044,
  E_STOP_JOB_FAILURE = -2045,
  E_SAVE_JOB_FAILURE = -2046,
  E_BALANCER_FAILURE = -2047,
  E_JOB_NOT_FINISHED = -2048,
  E_TASK_REPORT_OUT_DATE = -2049,
  E_JOB_NOT_IN_SPACE = -2050,
  E_JOB_NEED_RECOVER = -2051,
  E_INVALID_JOB = -2065,
  E_BACKUP_BUILDING_INDEX = -2066,
  E_BACKUP_SPACE_NOT_FOUND = -2067,
  E_RESTORE_FAILURE = -2068,
  E_SESSION_NOT_FOUND = -2069,
  E_LIST_CLUSTER_FAILURE = -2070,
  E_LIST_CLUSTER_GET_ABS_PATH_FAILURE = -2071,
  E_LIST_CLUSTER_NO_AGENT_FAILURE = -2072,
  E_QUERY_NOT_FOUND = -2073,
  E_AGENT_HB_FAILUE = -2074,
  E_INVALID_VARIABLE = -2080,
  E_VARIABLE_TYPE_VALUE_MISMATCH = -2081,
  E_CONSENSUS_ERROR = -3001,
  E_KEY_HAS_EXISTS = -3002,
  E_DATA_TYPE_MISMATCH = -3003,
  E_INVALID_FIELD_VALUE = -3004,
  E_INVALID_OPERATION = -3005,
  E_NOT_NULLABLE = -3006,
  E_FIELD_UNSET = -3007,
  E_OUT_OF_RANGE = -3008,
  E_DATA_CONFLICT_ERROR = -3010,
  E_WRITE_STALLED = -3011,
  E_IMPROPER_DATA_TYPE = -3021,
  E_INVALID_SPACEVIDLEN = -3022,
  E_INVALID_FILTER = -3031,
  E_INVALID_UPDATER = -3032,
  E_INVALID_STORE = -3033,
  E_INVALID_PEER = -3034,
  E_RETRY_EXHAUSTED = -3035,
  E_TRANSFER_LEADER_FAILED = -3036,
  E_INVALID_STAT_TYPE = -3037,
  E_INVALID_VID = -3038,
  E_NO_TRANSFORMED = -3039,
  E_LOAD_META_FAILED = -3040,
  E_FAILED_TO_CHECKPOINT = -3041,
  E_CHECKPOINT_BLOCKED = -3042,
  E_FILTER_OUT = -3043,
  E_INVALID_DATA = -3044,
  E_MUTATE_EDGE_CONFLICT = -3045,
  E_MUTATE_TAG_CONFLICT = -3046,
  E_OUTDATED_LOCK = -3047,
  E_INVALID_TASK_PARA = -3051,
  E_USER_CANCEL = -3052,
  E_TASK_EXECUTION_FAILED = -3053,
  E_PLAN_IS_KILLED = -3060,
  E_NO_TERM = -3070,
  E_OUTDATED_TERM = -3071,
  E_OUTDATED_EDGE = -3072,
  E_WRITE_WRITE_CONFLICT = -3073,
  E_CLIENT_SERVER_INCOMPATIBLE = -3061,
  E_ID_FAILED = -3062,
  E_RAFT_UNKNOWN_PART = -3500,
  E_RAFT_LOG_GAP = -3501,
  E_RAFT_LOG_STALE = -3502,
  E_RAFT_TERM_OUT_OF_DATE = -3503,
  E_RAFT_UNKNOWN_APPEND_LOG = -3504,
  E_RAFT_WAITING_SNAPSHOT = -3511,
  E_RAFT_SENDING_SNAPSHOT = -3512,
  E_RAFT_INVALID_PEER = -3513,
  E_RAFT_NOT_READY = -3514,
  E_RAFT_STOPPED = -3515,
  E_RAFT_BAD_ROLE = -3516,
  E_RAFT_WAL_FAIL = -3521,
  E_RAFT_HOST_STOPPED = -3522,
  E_RAFT_TOO_MANY_REQUESTS = -3523,
  E_RAFT_PERSIST_SNAPSHOT_FAILED = -3524,
  E_RAFT_RPC_EXCEPTION = -3525,
  E_RAFT_NO_WAL_FOUND = -3526,
  E_RAFT_HOST_PAUSED = -3527,
  E_RAFT_WRITE_BLOCKED = -3528,
  E_RAFT_BUFFER_OVERFLOW = -3529,
  E_RAFT_ATOMIC_OP_FAILED = -3530,
  E_LEADER_LEASE_FAILED = -3531,
  E_RAFT_CAUGHT_UP = -3532,
  E_LOG_GAP = -4001,
  E_LOG_STALE = -4002,
  E_INVALID_DRAINER_STORE = -4003,
  E_SPACE_MISMATCH = -4004,
  E_PART_MISMATCH = -4005,
  E_DATA_CONFLICT = -4006,
  E_REQ_CONFLICT = -4007,
  E_DATA_ILLEGAL = -4008,
  E_CACHE_CONFIG_ERROR = -5001,
  E_NOT_ENOUGH_SPACE = -5002,
  E_CACHE_MISS = -5003,
  E_POOL_NOT_FOUND = -5004,
  E_CACHE_WRITE_FAILURE = -5005,
  E_NODE_NUMBER_EXCEED_LIMIT = -7001,
  E_PARSING_LICENSE_FAILURE = -7002,
  E_UNKNOWN = -8000,
};




}} // nebula::cpp2

namespace std {
template<> struct hash<::nebula::cpp2::ValueType> :
  ::apache::thrift::detail::enum_hash<::nebula::cpp2::ValueType> {};
template<> struct hash<::nebula::cpp2::ErrorCode> :
  ::apache::thrift::detail::enum_hash<::nebula::cpp2::ErrorCode> {};
} // std

namespace apache { namespace thrift {


template <> struct TEnumDataStorage<::nebula::cpp2::ValueType>;

template <> struct TEnumTraits<::nebula::cpp2::ValueType> {
  using type = ::nebula::cpp2::ValueType;

  static constexpr std::size_t const size = 13;
  static folly::Range<type const*> const values;
  static folly::Range<folly::StringPiece const*> const names;

  static char const* findName(type value);
  static bool findValue(char const* name, type* out);

  static constexpr type min() { return type::kNull; }
  static constexpr type max() { return type::kEdge; }
};


template <> struct TEnumDataStorage<::nebula::cpp2::ErrorCode>;

template <> struct TEnumTraits<::nebula::cpp2::ErrorCode> {
  using type = ::nebula::cpp2::ErrorCode;

  static constexpr std::size_t const size = 170;
  static folly::Range<type const*> const values;
  static folly::Range<folly::StringPiece const*> const names;

  static char const* findName(type value);
  static bool findValue(char const* name, type* out);

  static constexpr type min() { return type::E_UNKNOWN; }
  static constexpr type max() { return type::SUCCEEDED; }
};


}} // apache::thrift

namespace nebula { namespace cpp2 {

using _ValueType_EnumMapFactory = apache::thrift::detail::TEnumMapFactory<ValueType>;
[[deprecated("use apache::thrift::util::enumNameSafe, apache::thrift::util::enumName, or apache::thrift::TEnumTraits")]]
extern const _ValueType_EnumMapFactory::ValuesToNamesMapType _ValueType_VALUES_TO_NAMES;
[[deprecated("use apache::thrift::TEnumTraits")]]
extern const _ValueType_EnumMapFactory::NamesToValuesMapType _ValueType_NAMES_TO_VALUES;

using _ErrorCode_EnumMapFactory = apache::thrift::detail::TEnumMapFactory<ErrorCode>;
[[deprecated("use apache::thrift::util::enumNameSafe, apache::thrift::util::enumName, or apache::thrift::TEnumTraits")]]
extern const _ErrorCode_EnumMapFactory::ValuesToNamesMapType _ErrorCode_VALUES_TO_NAMES;
[[deprecated("use apache::thrift::TEnumTraits")]]
extern const _ErrorCode_EnumMapFactory::NamesToValuesMapType _ErrorCode_NAMES_TO_VALUES;

}} // nebula::cpp2

// END declare_enums
// BEGIN forward_declare
namespace nebula { namespace cpp2 {
class NList;
class NMap;
class Node;
class Edge;
class Value;
class FieldType;
class RecordType;
class RawRecord;
class BindingTable;
}} // nebula::cpp2
// END forward_declare
// BEGIN typedefs
namespace nebula { namespace cpp2 {
typedef nebula::client::NodeTypeID NodeTypeID;
typedef nebula::client::EdgeTypeID EdgeTypeID;
typedef nebula::client::InternalID InternalID;
typedef nebula::client::EdgeRank EdgeRank;

}} // nebula::cpp2
// END typedefs
// BEGIN hash_and_equal_to
// END hash_and_equal_to
namespace nebula { namespace cpp2 {
using ::apache::thrift::detail::operator!=;
using ::apache::thrift::detail::operator>;
using ::apache::thrift::detail::operator<=;
using ::apache::thrift::detail::operator>=;
}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class NList final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = NList;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  NList() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  NList(apache::thrift::FragileConstructor, std::pmr::vector<nebula::client::Value> values__arg);

  NList(NList&&) noexcept;

  NList(const NList& src);


  NList& operator=(NList&&) noexcept;
  NList& operator=(const NList& src);
  void __clear();
 private:
  std::pmr::vector<nebula::client::Value> __fbthrift_field_values;
 private:
  apache::thrift::detail::isset_bitset<1, false> __isset;

 public:

  bool operator==(const NList&) const;
  bool operator<(const NList&) const;

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> values_ref() const& {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> values_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> values_ref() & {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> values_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> values() const& {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> values() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> values() & {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> values() && {
    return {static_cast<T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }
  const std::pmr::vector<nebula::client::Value>& get_values() const&;
  std::pmr::vector<nebula::client::Value> get_values() &&;

  template <typename T_NList_values_struct_setter = std::pmr::vector<nebula::client::Value>>
  [[deprecated("Use `FOO.values_ref() = BAR;` instead of `FOO.set_values(BAR);`")]]
  std::pmr::vector<nebula::client::Value>& set_values(T_NList_values_struct_setter&& values_) {
    values_ref() = std::forward<T_NList_values_struct_setter>(values_);
    return __fbthrift_field_values;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<NList>;
  friend void swap(NList& a, NList& b);
};

template <class Protocol_>
uint32_t NList::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class NMap final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = NMap;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  NMap() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  NMap(apache::thrift::FragileConstructor);

  NMap(NMap&&) = default;

  NMap(const NMap&) = default;


  NMap& operator=(NMap&&) = default;

  NMap& operator=(const NMap&) = default;
  void __clear();

 public:

  bool operator==(const NMap&) const;
  bool operator<(const NMap&) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<NMap>;
  friend void swap(NMap& a, NMap& b);
};

template <class Protocol_>
uint32_t NMap::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class Node final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = Node;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  Node() :
      __fbthrift_field_nodeID(),
      __fbthrift_field_nodeTypeID() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  Node(apache::thrift::FragileConstructor, ::nebula::cpp2::InternalID nodeID__arg, ::nebula::cpp2::NodeTypeID nodeTypeID__arg, std::pmr::unordered_map<::std::string, nebula::client::Value> properties__arg);

  Node(Node&&) noexcept;

  Node(const Node& src);


  Node& operator=(Node&&) noexcept;
  Node& operator=(const Node& src);
  void __clear();
 private:
  ::nebula::cpp2::InternalID __fbthrift_field_nodeID;
 private:
  ::nebula::cpp2::NodeTypeID __fbthrift_field_nodeTypeID;
 private:
  std::pmr::unordered_map<::std::string, nebula::client::Value> __fbthrift_field_properties;
 private:
  apache::thrift::detail::isset_bitset<3, false> __isset;

 public:

  bool operator==(const Node&) const;
  bool operator<(const Node&) const;

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> nodeID_ref() const& {
    return {this->__fbthrift_field_nodeID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> nodeID_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_nodeID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> nodeID_ref() & {
    return {this->__fbthrift_field_nodeID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> nodeID_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_nodeID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> nodeID() const& {
    return {this->__fbthrift_field_nodeID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> nodeID() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_nodeID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> nodeID() & {
    return {this->__fbthrift_field_nodeID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> nodeID() && {
    return {static_cast<T&&>(this->__fbthrift_field_nodeID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> nodeTypeID_ref() const& {
    return {this->__fbthrift_field_nodeTypeID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> nodeTypeID_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_nodeTypeID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> nodeTypeID_ref() & {
    return {this->__fbthrift_field_nodeTypeID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> nodeTypeID_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_nodeTypeID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> nodeTypeID() const& {
    return {this->__fbthrift_field_nodeTypeID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> nodeTypeID() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_nodeTypeID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> nodeTypeID() & {
    return {this->__fbthrift_field_nodeTypeID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::NodeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> nodeTypeID() && {
    return {static_cast<T&&>(this->__fbthrift_field_nodeTypeID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> properties_ref() const& {
    return {this->__fbthrift_field_properties, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> properties_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_properties), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> properties_ref() & {
    return {this->__fbthrift_field_properties, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> properties_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_properties), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> properties() const& {
    return {this->__fbthrift_field_properties, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> properties() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_properties), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> properties() & {
    return {this->__fbthrift_field_properties, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> properties() && {
    return {static_cast<T&&>(this->__fbthrift_field_properties), __isset.at(2), __isset.bit(2)};
  }

  ::nebula::cpp2::InternalID get_nodeID() const {
    return __fbthrift_field_nodeID;
  }

  [[deprecated("Use `FOO.nodeID_ref() = BAR;` instead of `FOO.set_nodeID(BAR);`")]]
  ::nebula::cpp2::InternalID& set_nodeID(::nebula::cpp2::InternalID nodeID_) {
    nodeID_ref() = nodeID_;
    return __fbthrift_field_nodeID;
  }

  ::nebula::cpp2::NodeTypeID get_nodeTypeID() const {
    return __fbthrift_field_nodeTypeID;
  }

  [[deprecated("Use `FOO.nodeTypeID_ref() = BAR;` instead of `FOO.set_nodeTypeID(BAR);`")]]
  ::nebula::cpp2::NodeTypeID& set_nodeTypeID(::nebula::cpp2::NodeTypeID nodeTypeID_) {
    nodeTypeID_ref() = nodeTypeID_;
    return __fbthrift_field_nodeTypeID;
  }
  const std::pmr::unordered_map<::std::string, nebula::client::Value>& get_properties() const&;
  std::pmr::unordered_map<::std::string, nebula::client::Value> get_properties() &&;

  template <typename T_Node_properties_struct_setter = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  [[deprecated("Use `FOO.properties_ref() = BAR;` instead of `FOO.set_properties(BAR);`")]]
  std::pmr::unordered_map<::std::string, nebula::client::Value>& set_properties(T_Node_properties_struct_setter&& properties_) {
    properties_ref() = std::forward<T_Node_properties_struct_setter>(properties_);
    return __fbthrift_field_properties;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<Node>;
  friend void swap(Node& a, Node& b);
};

template <class Protocol_>
uint32_t Node::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class Edge final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = Edge;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  Edge();

  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  Edge(apache::thrift::FragileConstructor, ::nebula::cpp2::InternalID srcID__arg, ::nebula::cpp2::InternalID dstID__arg, ::nebula::cpp2::EdgeTypeID edgeTypeID__arg, ::nebula::cpp2::EdgeRank rank__arg, std::pmr::unordered_map<::std::string, nebula::client::Value> properties__arg);

  Edge(Edge&&) noexcept;

  Edge(const Edge& src);


  Edge& operator=(Edge&&) noexcept;
  Edge& operator=(const Edge& src);
  void __clear();

  ~Edge();

 private:
  ::nebula::cpp2::InternalID __fbthrift_field_srcID;
 private:
  ::nebula::cpp2::InternalID __fbthrift_field_dstID;
 private:
  ::nebula::cpp2::EdgeTypeID __fbthrift_field_edgeTypeID;
 private:
  ::nebula::cpp2::EdgeRank __fbthrift_field_rank;
 private:
  std::pmr::unordered_map<::std::string, nebula::client::Value> __fbthrift_field_properties;
 private:
  apache::thrift::detail::isset_bitset<5, false> __isset;

 public:

  bool operator==(const Edge&) const;
  bool operator<(const Edge&) const;

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> srcID_ref() const& {
    return {this->__fbthrift_field_srcID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> srcID_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_srcID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> srcID_ref() & {
    return {this->__fbthrift_field_srcID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> srcID_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_srcID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> srcID() const& {
    return {this->__fbthrift_field_srcID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> srcID() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_srcID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> srcID() & {
    return {this->__fbthrift_field_srcID, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> srcID() && {
    return {static_cast<T&&>(this->__fbthrift_field_srcID), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> dstID_ref() const& {
    return {this->__fbthrift_field_dstID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> dstID_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_dstID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> dstID_ref() & {
    return {this->__fbthrift_field_dstID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> dstID_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_dstID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> dstID() const& {
    return {this->__fbthrift_field_dstID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> dstID() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_dstID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> dstID() & {
    return {this->__fbthrift_field_dstID, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::InternalID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> dstID() && {
    return {static_cast<T&&>(this->__fbthrift_field_dstID), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> edgeTypeID_ref() const& {
    return {this->__fbthrift_field_edgeTypeID, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> edgeTypeID_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_edgeTypeID), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> edgeTypeID_ref() & {
    return {this->__fbthrift_field_edgeTypeID, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> edgeTypeID_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_edgeTypeID), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> edgeTypeID() const& {
    return {this->__fbthrift_field_edgeTypeID, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> edgeTypeID() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_edgeTypeID), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> edgeTypeID() & {
    return {this->__fbthrift_field_edgeTypeID, __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeTypeID>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> edgeTypeID() && {
    return {static_cast<T&&>(this->__fbthrift_field_edgeTypeID), __isset.at(2), __isset.bit(2)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> rank_ref() const& {
    return {this->__fbthrift_field_rank, __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> rank_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_rank), __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> rank_ref() & {
    return {this->__fbthrift_field_rank, __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> rank_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_rank), __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> rank() const& {
    return {this->__fbthrift_field_rank, __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> rank() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_rank), __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> rank() & {
    return {this->__fbthrift_field_rank, __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = ::nebula::cpp2::EdgeRank>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> rank() && {
    return {static_cast<T&&>(this->__fbthrift_field_rank), __isset.at(3), __isset.bit(3)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> properties_ref() const& {
    return {this->__fbthrift_field_properties, __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> properties_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_properties), __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> properties_ref() & {
    return {this->__fbthrift_field_properties, __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> properties_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_properties), __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> properties() const& {
    return {this->__fbthrift_field_properties, __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> properties() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_properties), __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> properties() & {
    return {this->__fbthrift_field_properties, __isset.at(4), __isset.bit(4)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> properties() && {
    return {static_cast<T&&>(this->__fbthrift_field_properties), __isset.at(4), __isset.bit(4)};
  }

  ::nebula::cpp2::InternalID get_srcID() const {
    return __fbthrift_field_srcID;
  }

  [[deprecated("Use `FOO.srcID_ref() = BAR;` instead of `FOO.set_srcID(BAR);`")]]
  ::nebula::cpp2::InternalID& set_srcID(::nebula::cpp2::InternalID srcID_) {
    srcID_ref() = srcID_;
    return __fbthrift_field_srcID;
  }

  ::nebula::cpp2::InternalID get_dstID() const {
    return __fbthrift_field_dstID;
  }

  [[deprecated("Use `FOO.dstID_ref() = BAR;` instead of `FOO.set_dstID(BAR);`")]]
  ::nebula::cpp2::InternalID& set_dstID(::nebula::cpp2::InternalID dstID_) {
    dstID_ref() = dstID_;
    return __fbthrift_field_dstID;
  }

  ::nebula::cpp2::EdgeTypeID get_edgeTypeID() const {
    return __fbthrift_field_edgeTypeID;
  }

  [[deprecated("Use `FOO.edgeTypeID_ref() = BAR;` instead of `FOO.set_edgeTypeID(BAR);`")]]
  ::nebula::cpp2::EdgeTypeID& set_edgeTypeID(::nebula::cpp2::EdgeTypeID edgeTypeID_) {
    edgeTypeID_ref() = edgeTypeID_;
    return __fbthrift_field_edgeTypeID;
  }

  ::nebula::cpp2::EdgeRank get_rank() const {
    return __fbthrift_field_rank;
  }

  [[deprecated("Use `FOO.rank_ref() = BAR;` instead of `FOO.set_rank(BAR);`")]]
  ::nebula::cpp2::EdgeRank& set_rank(::nebula::cpp2::EdgeRank rank_) {
    rank_ref() = rank_;
    return __fbthrift_field_rank;
  }
  const std::pmr::unordered_map<::std::string, nebula::client::Value>& get_properties() const&;
  std::pmr::unordered_map<::std::string, nebula::client::Value> get_properties() &&;

  template <typename T_Edge_properties_struct_setter = std::pmr::unordered_map<::std::string, nebula::client::Value>>
  [[deprecated("Use `FOO.properties_ref() = BAR;` instead of `FOO.set_properties(BAR);`")]]
  std::pmr::unordered_map<::std::string, nebula::client::Value>& set_properties(T_Edge_properties_struct_setter&& properties_) {
    properties_ref() = std::forward<T_Edge_properties_struct_setter>(properties_);
    return __fbthrift_field_properties;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<Edge>;
  friend void swap(Edge& a, Edge& b);
};

template <class Protocol_>
uint32_t Edge::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class Value final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = Value;
  static constexpr bool __fbthrift_cpp2_is_union =
    true;


 public:
  enum Type : int {
    __EMPTY__ = 0,
    boolVal = 1,
    int8Val = 2,
    int16Val = 3,
    int32Val = 4,
    int64Val = 5,
    floatVal = 6,
    doubleVal = 7,
    stringVal = 8,
    listVal = 9,
    mapVal = 10,
    nodeVal = 11,
    edgeVal = 12,
  } ;

  Value()
      : type_(Type::__EMPTY__) {}

  Value(Value&& rhs) noexcept
      : type_(Type::__EMPTY__) {
    if (this == &rhs) { return; }
    if (rhs.type_ == Type::__EMPTY__) { return; }
    switch (rhs.type_) {
      case Type::boolVal:
      {
        set_boolVal(std::move(rhs.value_.boolVal));
        break;
      }
      case Type::int8Val:
      {
        set_int8Val(std::move(rhs.value_.int8Val));
        break;
      }
      case Type::int16Val:
      {
        set_int16Val(std::move(rhs.value_.int16Val));
        break;
      }
      case Type::int32Val:
      {
        set_int32Val(std::move(rhs.value_.int32Val));
        break;
      }
      case Type::int64Val:
      {
        set_int64Val(std::move(rhs.value_.int64Val));
        break;
      }
      case Type::floatVal:
      {
        set_floatVal(std::move(rhs.value_.floatVal));
        break;
      }
      case Type::doubleVal:
      {
        set_doubleVal(std::move(rhs.value_.doubleVal));
        break;
      }
      case Type::stringVal:
      {
        set_stringVal(std::move(rhs.value_.stringVal));
        break;
      }
      case Type::listVal:
      {
        set_listVal(std::move(rhs.value_.listVal));
        break;
      }
      case Type::mapVal:
      {
        set_mapVal(std::move(rhs.value_.mapVal));
        break;
      }
      case Type::nodeVal:
      {
        set_nodeVal(std::move(rhs.value_.nodeVal));
        break;
      }
      case Type::edgeVal:
      {
        set_edgeVal(std::move(rhs.value_.edgeVal));
        break;
      }
      default:
      {
        assert(false);
        break;
      }
    }
    rhs.__clear();
  }

  Value(const Value& rhs)
      : type_(Type::__EMPTY__) {
    if (this == &rhs) { return; }
    if (rhs.type_ == Type::__EMPTY__) { return; }
    switch (rhs.type_) {
      case Type::boolVal:
      {
        set_boolVal(rhs.value_.boolVal);
        break;
      }
      case Type::int8Val:
      {
        set_int8Val(rhs.value_.int8Val);
        break;
      }
      case Type::int16Val:
      {
        set_int16Val(rhs.value_.int16Val);
        break;
      }
      case Type::int32Val:
      {
        set_int32Val(rhs.value_.int32Val);
        break;
      }
      case Type::int64Val:
      {
        set_int64Val(rhs.value_.int64Val);
        break;
      }
      case Type::floatVal:
      {
        set_floatVal(rhs.value_.floatVal);
        break;
      }
      case Type::doubleVal:
      {
        set_doubleVal(rhs.value_.doubleVal);
        break;
      }
      case Type::stringVal:
      {
        set_stringVal(rhs.value_.stringVal);
        break;
      }
      case Type::listVal:
      {
        set_listVal(rhs.value_.listVal);
        break;
      }
      case Type::mapVal:
      {
        set_mapVal(rhs.value_.mapVal);
        break;
      }
      case Type::nodeVal:
      {
        set_nodeVal(rhs.value_.nodeVal);
        break;
      }
      case Type::edgeVal:
      {
        set_edgeVal(rhs.value_.edgeVal);
        break;
      }
      default:
      {
        assert(false);
        break;
      }
    }
  }

  Value& operator=(Value&& rhs) noexcept {
    if (this == &rhs) { return *this; }
    __clear();
    if (rhs.type_ == Type::__EMPTY__) { return *this; }
    switch (rhs.type_) {
      case Type::boolVal:
      {
        set_boolVal(std::move(rhs.value_.boolVal));
        break;
      }
      case Type::int8Val:
      {
        set_int8Val(std::move(rhs.value_.int8Val));
        break;
      }
      case Type::int16Val:
      {
        set_int16Val(std::move(rhs.value_.int16Val));
        break;
      }
      case Type::int32Val:
      {
        set_int32Val(std::move(rhs.value_.int32Val));
        break;
      }
      case Type::int64Val:
      {
        set_int64Val(std::move(rhs.value_.int64Val));
        break;
      }
      case Type::floatVal:
      {
        set_floatVal(std::move(rhs.value_.floatVal));
        break;
      }
      case Type::doubleVal:
      {
        set_doubleVal(std::move(rhs.value_.doubleVal));
        break;
      }
      case Type::stringVal:
      {
        set_stringVal(std::move(rhs.value_.stringVal));
        break;
      }
      case Type::listVal:
      {
        set_listVal(std::move(rhs.value_.listVal));
        break;
      }
      case Type::mapVal:
      {
        set_mapVal(std::move(rhs.value_.mapVal));
        break;
      }
      case Type::nodeVal:
      {
        set_nodeVal(std::move(rhs.value_.nodeVal));
        break;
      }
      case Type::edgeVal:
      {
        set_edgeVal(std::move(rhs.value_.edgeVal));
        break;
      }
      default:
      {
        assert(false);
        break;
      }
    }
    rhs.__clear();
    return *this;
  }

  Value& operator=(const Value& rhs) {
    if (this == &rhs) { return *this; }
    __clear();
    if (rhs.type_ == Type::__EMPTY__) { return *this; }
    switch (rhs.type_) {
      case Type::boolVal:
      {
        set_boolVal(rhs.value_.boolVal);
        break;
      }
      case Type::int8Val:
      {
        set_int8Val(rhs.value_.int8Val);
        break;
      }
      case Type::int16Val:
      {
        set_int16Val(rhs.value_.int16Val);
        break;
      }
      case Type::int32Val:
      {
        set_int32Val(rhs.value_.int32Val);
        break;
      }
      case Type::int64Val:
      {
        set_int64Val(rhs.value_.int64Val);
        break;
      }
      case Type::floatVal:
      {
        set_floatVal(rhs.value_.floatVal);
        break;
      }
      case Type::doubleVal:
      {
        set_doubleVal(rhs.value_.doubleVal);
        break;
      }
      case Type::stringVal:
      {
        set_stringVal(rhs.value_.stringVal);
        break;
      }
      case Type::listVal:
      {
        set_listVal(rhs.value_.listVal);
        break;
      }
      case Type::mapVal:
      {
        set_mapVal(rhs.value_.mapVal);
        break;
      }
      case Type::nodeVal:
      {
        set_nodeVal(rhs.value_.nodeVal);
        break;
      }
      case Type::edgeVal:
      {
        set_edgeVal(rhs.value_.edgeVal);
        break;
      }
      default:
      {
        assert(false);
        break;
      }
    }
    return *this;
  }
  void __clear();

  ~Value() {
    __clear();
  }
  union storage_type {
    bool boolVal;
    ::std::int8_t int8Val;
    ::std::int16_t int16Val;
    ::std::int32_t int32Val;
    ::std::int64_t int64Val;
    double floatVal;
    double doubleVal;
    ::std::string stringVal;
    ::nebula::cpp2::NList listVal;
    ::nebula::cpp2::NMap mapVal;
    ::nebula::cpp2::Node nodeVal;
    ::nebula::cpp2::Edge edgeVal;

    storage_type() {}
    ~storage_type() {}
  } ;

  bool operator==(const Value&) const;
  bool operator<(const Value&) const;

  bool& set_boolVal(bool t = bool()) {
    __clear();
    type_ = Type::boolVal;
    ::new (std::addressof(value_.boolVal)) bool(t);
    return value_.boolVal;
  }

  ::std::int8_t& set_int8Val(::std::int8_t t = ::std::int8_t()) {
    __clear();
    type_ = Type::int8Val;
    ::new (std::addressof(value_.int8Val)) ::std::int8_t(t);
    return value_.int8Val;
  }

  ::std::int16_t& set_int16Val(::std::int16_t t = ::std::int16_t()) {
    __clear();
    type_ = Type::int16Val;
    ::new (std::addressof(value_.int16Val)) ::std::int16_t(t);
    return value_.int16Val;
  }

  ::std::int32_t& set_int32Val(::std::int32_t t = ::std::int32_t()) {
    __clear();
    type_ = Type::int32Val;
    ::new (std::addressof(value_.int32Val)) ::std::int32_t(t);
    return value_.int32Val;
  }

  ::std::int64_t& set_int64Val(::std::int64_t t = ::std::int64_t()) {
    __clear();
    type_ = Type::int64Val;
    ::new (std::addressof(value_.int64Val)) ::std::int64_t(t);
    return value_.int64Val;
  }

  double& set_floatVal(double t = double()) {
    __clear();
    type_ = Type::floatVal;
    ::new (std::addressof(value_.floatVal)) double(t);
    return value_.floatVal;
  }

  double& set_doubleVal(double t = double()) {
    __clear();
    type_ = Type::doubleVal;
    ::new (std::addressof(value_.doubleVal)) double(t);
    return value_.doubleVal;
  }

  ::std::string& set_stringVal(::std::string const &t) {
    __clear();
    type_ = Type::stringVal;
    ::new (std::addressof(value_.stringVal)) ::std::string(t);
    return value_.stringVal;
  }

  ::std::string& set_stringVal(::std::string&& t) {
    __clear();
    type_ = Type::stringVal;
    ::new (std::addressof(value_.stringVal)) ::std::string(std::move(t));
    return value_.stringVal;
  }

  template<typename... T, typename = ::apache::thrift::safe_overload_t<::std::string, T...>> ::std::string& set_stringVal(T&&... t) {
    __clear();
    type_ = Type::stringVal;
    ::new (std::addressof(value_.stringVal)) ::std::string(std::forward<T>(t)...);
    return value_.stringVal;
  }

  ::nebula::cpp2::NList& set_listVal(::nebula::cpp2::NList const &t) {
    __clear();
    type_ = Type::listVal;
    ::new (std::addressof(value_.listVal)) ::nebula::cpp2::NList(t);
    return value_.listVal;
  }

  ::nebula::cpp2::NList& set_listVal(::nebula::cpp2::NList&& t) {
    __clear();
    type_ = Type::listVal;
    ::new (std::addressof(value_.listVal)) ::nebula::cpp2::NList(std::move(t));
    return value_.listVal;
  }

  template<typename... T, typename = ::apache::thrift::safe_overload_t<::nebula::cpp2::NList, T...>> ::nebula::cpp2::NList& set_listVal(T&&... t) {
    __clear();
    type_ = Type::listVal;
    ::new (std::addressof(value_.listVal)) ::nebula::cpp2::NList(std::forward<T>(t)...);
    return value_.listVal;
  }

  ::nebula::cpp2::NMap& set_mapVal(::nebula::cpp2::NMap const &t) {
    __clear();
    type_ = Type::mapVal;
    ::new (std::addressof(value_.mapVal)) ::nebula::cpp2::NMap(t);
    return value_.mapVal;
  }

  ::nebula::cpp2::NMap& set_mapVal(::nebula::cpp2::NMap&& t) {
    __clear();
    type_ = Type::mapVal;
    ::new (std::addressof(value_.mapVal)) ::nebula::cpp2::NMap(std::move(t));
    return value_.mapVal;
  }

  template<typename... T, typename = ::apache::thrift::safe_overload_t<::nebula::cpp2::NMap, T...>> ::nebula::cpp2::NMap& set_mapVal(T&&... t) {
    __clear();
    type_ = Type::mapVal;
    ::new (std::addressof(value_.mapVal)) ::nebula::cpp2::NMap(std::forward<T>(t)...);
    return value_.mapVal;
  }

  ::nebula::cpp2::Node& set_nodeVal(::nebula::cpp2::Node const &t) {
    __clear();
    type_ = Type::nodeVal;
    ::new (std::addressof(value_.nodeVal)) ::nebula::cpp2::Node(t);
    return value_.nodeVal;
  }

  ::nebula::cpp2::Node& set_nodeVal(::nebula::cpp2::Node&& t) {
    __clear();
    type_ = Type::nodeVal;
    ::new (std::addressof(value_.nodeVal)) ::nebula::cpp2::Node(std::move(t));
    return value_.nodeVal;
  }

  template<typename... T, typename = ::apache::thrift::safe_overload_t<::nebula::cpp2::Node, T...>> ::nebula::cpp2::Node& set_nodeVal(T&&... t) {
    __clear();
    type_ = Type::nodeVal;
    ::new (std::addressof(value_.nodeVal)) ::nebula::cpp2::Node(std::forward<T>(t)...);
    return value_.nodeVal;
  }

  ::nebula::cpp2::Edge& set_edgeVal(::nebula::cpp2::Edge const &t) {
    __clear();
    type_ = Type::edgeVal;
    ::new (std::addressof(value_.edgeVal)) ::nebula::cpp2::Edge(t);
    return value_.edgeVal;
  }

  ::nebula::cpp2::Edge& set_edgeVal(::nebula::cpp2::Edge&& t) {
    __clear();
    type_ = Type::edgeVal;
    ::new (std::addressof(value_.edgeVal)) ::nebula::cpp2::Edge(std::move(t));
    return value_.edgeVal;
  }

  template<typename... T, typename = ::apache::thrift::safe_overload_t<::nebula::cpp2::Edge, T...>> ::nebula::cpp2::Edge& set_edgeVal(T&&... t) {
    __clear();
    type_ = Type::edgeVal;
    ::new (std::addressof(value_.edgeVal)) ::nebula::cpp2::Edge(std::forward<T>(t)...);
    return value_.edgeVal;
  }

  bool const& get_boolVal() const {
    if (type_ != Type::boolVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.boolVal;
  }

  ::std::int8_t const& get_int8Val() const {
    if (type_ != Type::int8Val) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.int8Val;
  }

  ::std::int16_t const& get_int16Val() const {
    if (type_ != Type::int16Val) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.int16Val;
  }

  ::std::int32_t const& get_int32Val() const {
    if (type_ != Type::int32Val) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.int32Val;
  }

  ::std::int64_t const& get_int64Val() const {
    if (type_ != Type::int64Val) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.int64Val;
  }

  double const& get_floatVal() const {
    if (type_ != Type::floatVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.floatVal;
  }

  double const& get_doubleVal() const {
    if (type_ != Type::doubleVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.doubleVal;
  }

  ::std::string const& get_stringVal() const {
    if (type_ != Type::stringVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.stringVal;
  }

  ::nebula::cpp2::NList const& get_listVal() const {
    if (type_ != Type::listVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.listVal;
  }

  ::nebula::cpp2::NMap const& get_mapVal() const {
    if (type_ != Type::mapVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.mapVal;
  }

  ::nebula::cpp2::Node const& get_nodeVal() const {
    if (type_ != Type::nodeVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.nodeVal;
  }

  ::nebula::cpp2::Edge const& get_edgeVal() const {
    if (type_ != Type::edgeVal) {
      ::apache::thrift::detail::throw_on_bad_field_access();
    }
    return value_.edgeVal;
  }

  bool& mutable_boolVal() {
    assert(type_ == Type::boolVal);
    return value_.boolVal;
  }

  ::std::int8_t& mutable_int8Val() {
    assert(type_ == Type::int8Val);
    return value_.int8Val;
  }

  ::std::int16_t& mutable_int16Val() {
    assert(type_ == Type::int16Val);
    return value_.int16Val;
  }

  ::std::int32_t& mutable_int32Val() {
    assert(type_ == Type::int32Val);
    return value_.int32Val;
  }

  ::std::int64_t& mutable_int64Val() {
    assert(type_ == Type::int64Val);
    return value_.int64Val;
  }

  double& mutable_floatVal() {
    assert(type_ == Type::floatVal);
    return value_.floatVal;
  }

  double& mutable_doubleVal() {
    assert(type_ == Type::doubleVal);
    return value_.doubleVal;
  }

  ::std::string& mutable_stringVal() {
    assert(type_ == Type::stringVal);
    return value_.stringVal;
  }

  ::nebula::cpp2::NList& mutable_listVal() {
    assert(type_ == Type::listVal);
    return value_.listVal;
  }

  ::nebula::cpp2::NMap& mutable_mapVal() {
    assert(type_ == Type::mapVal);
    return value_.mapVal;
  }

  ::nebula::cpp2::Node& mutable_nodeVal() {
    assert(type_ == Type::nodeVal);
    return value_.nodeVal;
  }

  ::nebula::cpp2::Edge& mutable_edgeVal() {
    assert(type_ == Type::edgeVal);
    return value_.edgeVal;
  }

  bool move_boolVal() {
    assert(type_ == Type::boolVal);
    return std::move(value_.boolVal);
  }

  ::std::int8_t move_int8Val() {
    assert(type_ == Type::int8Val);
    return std::move(value_.int8Val);
  }

  ::std::int16_t move_int16Val() {
    assert(type_ == Type::int16Val);
    return std::move(value_.int16Val);
  }

  ::std::int32_t move_int32Val() {
    assert(type_ == Type::int32Val);
    return std::move(value_.int32Val);
  }

  ::std::int64_t move_int64Val() {
    assert(type_ == Type::int64Val);
    return std::move(value_.int64Val);
  }

  double move_floatVal() {
    assert(type_ == Type::floatVal);
    return std::move(value_.floatVal);
  }

  double move_doubleVal() {
    assert(type_ == Type::doubleVal);
    return std::move(value_.doubleVal);
  }

  ::std::string move_stringVal() {
    assert(type_ == Type::stringVal);
    return std::move(value_.stringVal);
  }

  ::nebula::cpp2::NList move_listVal() {
    assert(type_ == Type::listVal);
    return std::move(value_.listVal);
  }

  ::nebula::cpp2::NMap move_mapVal() {
    assert(type_ == Type::mapVal);
    return std::move(value_.mapVal);
  }

  ::nebula::cpp2::Node move_nodeVal() {
    assert(type_ == Type::nodeVal);
    return std::move(value_.nodeVal);
  }

  ::nebula::cpp2::Edge move_edgeVal() {
    assert(type_ == Type::edgeVal);
    return std::move(value_.edgeVal);
  }

  template <typename..., typename T = bool>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> boolVal_ref() const& {
    return {value_.boolVal, type_, boolVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = bool>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> boolVal_ref() const&& {
    return {std::move(value_.boolVal), type_, boolVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = bool>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> boolVal_ref() & {
    return {value_.boolVal, type_, boolVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = bool>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> boolVal_ref() && {
    return {std::move(value_.boolVal), type_, boolVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::std::int8_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> int8Val_ref() const& {
    return {value_.int8Val, type_, int8Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int8_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> int8Val_ref() const&& {
    return {std::move(value_.int8Val), type_, int8Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int8_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> int8Val_ref() & {
    return {value_.int8Val, type_, int8Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int8_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> int8Val_ref() && {
    return {std::move(value_.int8Val), type_, int8Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::std::int16_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> int16Val_ref() const& {
    return {value_.int16Val, type_, int16Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int16_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> int16Val_ref() const&& {
    return {std::move(value_.int16Val), type_, int16Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int16_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> int16Val_ref() & {
    return {value_.int16Val, type_, int16Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int16_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> int16Val_ref() && {
    return {std::move(value_.int16Val), type_, int16Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::std::int32_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> int32Val_ref() const& {
    return {value_.int32Val, type_, int32Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int32_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> int32Val_ref() const&& {
    return {std::move(value_.int32Val), type_, int32Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int32_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> int32Val_ref() & {
    return {value_.int32Val, type_, int32Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int32_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> int32Val_ref() && {
    return {std::move(value_.int32Val), type_, int32Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> int64Val_ref() const& {
    return {value_.int64Val, type_, int64Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> int64Val_ref() const&& {
    return {std::move(value_.int64Val), type_, int64Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> int64Val_ref() & {
    return {value_.int64Val, type_, int64Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> int64Val_ref() && {
    return {std::move(value_.int64Val), type_, int64Val, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> floatVal_ref() const& {
    return {value_.floatVal, type_, floatVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> floatVal_ref() const&& {
    return {std::move(value_.floatVal), type_, floatVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> floatVal_ref() & {
    return {value_.floatVal, type_, floatVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> floatVal_ref() && {
    return {std::move(value_.floatVal), type_, floatVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> doubleVal_ref() const& {
    return {value_.doubleVal, type_, doubleVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> doubleVal_ref() const&& {
    return {std::move(value_.doubleVal), type_, doubleVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> doubleVal_ref() & {
    return {value_.doubleVal, type_, doubleVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = double>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> doubleVal_ref() && {
    return {std::move(value_.doubleVal), type_, doubleVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> stringVal_ref() const& {
    return {value_.stringVal, type_, stringVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> stringVal_ref() const&& {
    return {std::move(value_.stringVal), type_, stringVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> stringVal_ref() & {
    return {value_.stringVal, type_, stringVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> stringVal_ref() && {
    return {std::move(value_.stringVal), type_, stringVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::nebula::cpp2::NList>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> listVal_ref() const& {
    return {value_.listVal, type_, listVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::NList>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> listVal_ref() const&& {
    return {std::move(value_.listVal), type_, listVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::NList>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> listVal_ref() & {
    return {value_.listVal, type_, listVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::NList>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> listVal_ref() && {
    return {std::move(value_.listVal), type_, listVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::nebula::cpp2::NMap>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> mapVal_ref() const& {
    return {value_.mapVal, type_, mapVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::NMap>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> mapVal_ref() const&& {
    return {std::move(value_.mapVal), type_, mapVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::NMap>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> mapVal_ref() & {
    return {value_.mapVal, type_, mapVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::NMap>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> mapVal_ref() && {
    return {std::move(value_.mapVal), type_, mapVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::nebula::cpp2::Node>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> nodeVal_ref() const& {
    return {value_.nodeVal, type_, nodeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::Node>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> nodeVal_ref() const&& {
    return {std::move(value_.nodeVal), type_, nodeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::Node>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> nodeVal_ref() & {
    return {value_.nodeVal, type_, nodeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::Node>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> nodeVal_ref() && {
    return {std::move(value_.nodeVal), type_, nodeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  template <typename..., typename T = ::nebula::cpp2::Edge>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&> edgeVal_ref() const& {
    return {value_.edgeVal, type_, edgeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::Edge>
  FOLLY_ERASE ::apache::thrift::union_field_ref<const T&&> edgeVal_ref() const&& {
    return {std::move(value_.edgeVal), type_, edgeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::Edge>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&> edgeVal_ref() & {
    return {value_.edgeVal, type_, edgeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }

  template <typename..., typename T = ::nebula::cpp2::Edge>
  FOLLY_ERASE ::apache::thrift::union_field_ref<T&&> edgeVal_ref() && {
    return {std::move(value_.edgeVal), type_, edgeVal, this, ::apache::thrift::detail::union_field_ref_owner_vtable_for<decltype(*this)>};
  }
  Type getType() const { return static_cast<Type>(type_); }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;
 protected:
  template <class T>
  void destruct(T &val) {
    (&val)->~T();
  }

  storage_type value_;
  std::underlying_type_t<Type> type_;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<Value>;
  friend void swap(Value& a, Value& b);
};

template <class Protocol_>
uint32_t Value::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class FieldType final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = FieldType;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  FieldType() :
      __fbthrift_field_valueType() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  FieldType(apache::thrift::FragileConstructor, ::std::string filedName__arg, nebula::client::ValueType valueType__arg);

  FieldType(FieldType&&) noexcept;

  FieldType(const FieldType& src);


  FieldType& operator=(FieldType&&) noexcept;
  FieldType& operator=(const FieldType& src);
  void __clear();
 private:
  ::std::string __fbthrift_field_filedName;
 private:
  nebula::client::ValueType __fbthrift_field_valueType;
 private:
  apache::thrift::detail::isset_bitset<2, false> __isset;

 public:

  bool operator==(const FieldType&) const;
  bool operator<(const FieldType&) const;

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> filedName_ref() const& {
    return {this->__fbthrift_field_filedName, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> filedName_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_filedName), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> filedName_ref() & {
    return {this->__fbthrift_field_filedName, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> filedName_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_filedName), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> filedName() const& {
    return {this->__fbthrift_field_filedName, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> filedName() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_filedName), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> filedName() & {
    return {this->__fbthrift_field_filedName, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = ::std::string>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> filedName() && {
    return {static_cast<T&&>(this->__fbthrift_field_filedName), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> valueType_ref() const& {
    return {this->__fbthrift_field_valueType, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> valueType_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_valueType), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> valueType_ref() & {
    return {this->__fbthrift_field_valueType, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> valueType_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_valueType), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> valueType() const& {
    return {this->__fbthrift_field_valueType, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> valueType() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_valueType), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> valueType() & {
    return {this->__fbthrift_field_valueType, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = nebula::client::ValueType>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> valueType() && {
    return {static_cast<T&&>(this->__fbthrift_field_valueType), __isset.at(1), __isset.bit(1)};
  }

  const ::std::string& get_filedName() const& {
    return __fbthrift_field_filedName;
  }

  ::std::string get_filedName() && {
    return std::move(__fbthrift_field_filedName);
  }

  template <typename T_FieldType_filedName_struct_setter = ::std::string>
  [[deprecated("Use `FOO.filedName_ref() = BAR;` instead of `FOO.set_filedName(BAR);`")]]
  ::std::string& set_filedName(T_FieldType_filedName_struct_setter&& filedName_) {
    filedName_ref() = std::forward<T_FieldType_filedName_struct_setter>(filedName_);
    return __fbthrift_field_filedName;
  }

  nebula::client::ValueType get_valueType() const {
    return __fbthrift_field_valueType;
  }

  [[deprecated("Use `FOO.valueType_ref() = BAR;` instead of `FOO.set_valueType(BAR);`")]]
  nebula::client::ValueType& set_valueType(nebula::client::ValueType valueType_) {
    valueType_ref() = valueType_;
    return __fbthrift_field_valueType;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<FieldType>;
  friend void swap(FieldType& a, FieldType& b);
};

template <class Protocol_>
uint32_t FieldType::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class RecordType final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = RecordType;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  RecordType() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  RecordType(apache::thrift::FragileConstructor, std::pmr::vector<nebula::client::FieldType> fieldType__arg, std::pmr::unordered_map<::std::string, ::std::int32_t> fieldNameIndexMap__arg);

  RecordType(RecordType&&) noexcept;

  RecordType(const RecordType& src);


  RecordType& operator=(RecordType&&) noexcept;
  RecordType& operator=(const RecordType& src);
  void __clear();
 private:
  std::pmr::vector<nebula::client::FieldType> __fbthrift_field_fieldType;
 private:
  std::pmr::unordered_map<::std::string, ::std::int32_t> __fbthrift_field_fieldNameIndexMap;
 private:
  apache::thrift::detail::isset_bitset<2, false> __isset;

 public:

  bool operator==(const RecordType&) const;
  bool operator<(const RecordType&) const;

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> fieldType_ref() const& {
    return {this->__fbthrift_field_fieldType, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> fieldType_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_fieldType), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> fieldType_ref() & {
    return {this->__fbthrift_field_fieldType, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> fieldType_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_fieldType), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> fieldType() const& {
    return {this->__fbthrift_field_fieldType, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> fieldType() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_fieldType), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> fieldType() & {
    return {this->__fbthrift_field_fieldType, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::FieldType>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> fieldType() && {
    return {static_cast<T&&>(this->__fbthrift_field_fieldType), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> fieldNameIndexMap_ref() const& {
    return {this->__fbthrift_field_fieldNameIndexMap, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> fieldNameIndexMap_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_fieldNameIndexMap), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> fieldNameIndexMap_ref() & {
    return {this->__fbthrift_field_fieldNameIndexMap, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> fieldNameIndexMap_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_fieldNameIndexMap), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> fieldNameIndexMap() const& {
    return {this->__fbthrift_field_fieldNameIndexMap, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> fieldNameIndexMap() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_fieldNameIndexMap), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> fieldNameIndexMap() & {
    return {this->__fbthrift_field_fieldNameIndexMap, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> fieldNameIndexMap() && {
    return {static_cast<T&&>(this->__fbthrift_field_fieldNameIndexMap), __isset.at(1), __isset.bit(1)};
  }
  const std::pmr::vector<nebula::client::FieldType>& get_fieldType() const&;
  std::pmr::vector<nebula::client::FieldType> get_fieldType() &&;

  template <typename T_RecordType_fieldType_struct_setter = std::pmr::vector<nebula::client::FieldType>>
  [[deprecated("Use `FOO.fieldType_ref() = BAR;` instead of `FOO.set_fieldType(BAR);`")]]
  std::pmr::vector<nebula::client::FieldType>& set_fieldType(T_RecordType_fieldType_struct_setter&& fieldType_) {
    fieldType_ref() = std::forward<T_RecordType_fieldType_struct_setter>(fieldType_);
    return __fbthrift_field_fieldType;
  }
  const std::pmr::unordered_map<::std::string, ::std::int32_t>& get_fieldNameIndexMap() const&;
  std::pmr::unordered_map<::std::string, ::std::int32_t> get_fieldNameIndexMap() &&;

  template <typename T_RecordType_fieldNameIndexMap_struct_setter = std::pmr::unordered_map<::std::string, ::std::int32_t>>
  [[deprecated("Use `FOO.fieldNameIndexMap_ref() = BAR;` instead of `FOO.set_fieldNameIndexMap(BAR);`")]]
  std::pmr::unordered_map<::std::string, ::std::int32_t>& set_fieldNameIndexMap(T_RecordType_fieldNameIndexMap_struct_setter&& fieldNameIndexMap_) {
    fieldNameIndexMap_ref() = std::forward<T_RecordType_fieldNameIndexMap_struct_setter>(fieldNameIndexMap_);
    return __fbthrift_field_fieldNameIndexMap;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<RecordType>;
  friend void swap(RecordType& a, RecordType& b);
};

template <class Protocol_>
uint32_t RecordType::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class RawRecord final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = RawRecord;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  RawRecord() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  RawRecord(apache::thrift::FragileConstructor, std::pmr::vector<nebula::client::Value> values__arg);

  RawRecord(RawRecord&&) noexcept;

  RawRecord(const RawRecord& src);


  RawRecord& operator=(RawRecord&&) noexcept;
  RawRecord& operator=(const RawRecord& src);
  void __clear();
 private:
  std::pmr::vector<nebula::client::Value> __fbthrift_field_values;
 private:
  apache::thrift::detail::isset_bitset<1, false> __isset;

 public:

  bool operator==(const RawRecord&) const;
  bool operator<(const RawRecord&) const;

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> values_ref() const& {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> values_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> values_ref() & {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> values_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> values() const& {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> values() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> values() & {
    return {this->__fbthrift_field_values, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<nebula::client::Value>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> values() && {
    return {static_cast<T&&>(this->__fbthrift_field_values), __isset.at(0), __isset.bit(0)};
  }
  const std::pmr::vector<nebula::client::Value>& get_values() const&;
  std::pmr::vector<nebula::client::Value> get_values() &&;

  template <typename T_RawRecord_values_struct_setter = std::pmr::vector<nebula::client::Value>>
  [[deprecated("Use `FOO.values_ref() = BAR;` instead of `FOO.set_values(BAR);`")]]
  std::pmr::vector<nebula::client::Value>& set_values(T_RawRecord_values_struct_setter&& values_) {
    values_ref() = std::forward<T_RawRecord_values_struct_setter>(values_);
    return __fbthrift_field_values;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<RawRecord>;
  friend void swap(RawRecord& a, RawRecord& b);
};

template <class Protocol_>
uint32_t RawRecord::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2
namespace nebula { namespace cpp2 {
class BindingTable final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_gen_nimble = false;
  static constexpr bool __fbthrift_cpp2_gen_has_thrift_uri = false;

 public:
  using __fbthrift_cpp2_type = BindingTable;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  BindingTable() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  BindingTable(apache::thrift::FragileConstructor, std::pmr::vector<::std::string> columnNames__arg, std::pmr::deque<nebula::client::RawRecord> records__arg);

  BindingTable(BindingTable&&) noexcept;

  BindingTable(const BindingTable& src);


  BindingTable& operator=(BindingTable&&) noexcept;
  BindingTable& operator=(const BindingTable& src);
  void __clear();
 private:
  std::pmr::vector<::std::string> __fbthrift_field_columnNames;
 private:
  std::pmr::deque<nebula::client::RawRecord> __fbthrift_field_records;
 private:
  apache::thrift::detail::isset_bitset<2, false> __isset;

 public:

  bool operator==(const BindingTable&) const;
  bool operator<(const BindingTable&) const;

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> columnNames_ref() const& {
    return {this->__fbthrift_field_columnNames, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> columnNames_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_columnNames), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> columnNames_ref() & {
    return {this->__fbthrift_field_columnNames, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> columnNames_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_columnNames), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> columnNames() const& {
    return {this->__fbthrift_field_columnNames, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> columnNames() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_columnNames), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> columnNames() & {
    return {this->__fbthrift_field_columnNames, __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::vector<::std::string>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> columnNames() && {
    return {static_cast<T&&>(this->__fbthrift_field_columnNames), __isset.at(0), __isset.bit(0)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> records_ref() const& {
    return {this->__fbthrift_field_records, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> records_ref() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_records), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> records_ref() & {
    return {this->__fbthrift_field_records, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> records_ref() && {
    return {static_cast<T&&>(this->__fbthrift_field_records), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&> records() const& {
    return {this->__fbthrift_field_records, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<const T&&> records() const&& {
    return {static_cast<const T&&>(this->__fbthrift_field_records), __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&> records() & {
    return {this->__fbthrift_field_records, __isset.at(1), __isset.bit(1)};
  }

  template <typename..., typename T = std::pmr::deque<nebula::client::RawRecord>>
  FOLLY_ERASE ::apache::thrift::field_ref<T&&> records() && {
    return {static_cast<T&&>(this->__fbthrift_field_records), __isset.at(1), __isset.bit(1)};
  }
  const std::pmr::vector<::std::string>& get_columnNames() const&;
  std::pmr::vector<::std::string> get_columnNames() &&;

  template <typename T_BindingTable_columnNames_struct_setter = std::pmr::vector<::std::string>>
  [[deprecated("Use `FOO.columnNames_ref() = BAR;` instead of `FOO.set_columnNames(BAR);`")]]
  std::pmr::vector<::std::string>& set_columnNames(T_BindingTable_columnNames_struct_setter&& columnNames_) {
    columnNames_ref() = std::forward<T_BindingTable_columnNames_struct_setter>(columnNames_);
    return __fbthrift_field_columnNames;
  }
  const std::pmr::deque<nebula::client::RawRecord>& get_records() const&;
  std::pmr::deque<nebula::client::RawRecord> get_records() &&;

  template <typename T_BindingTable_records_struct_setter = std::pmr::deque<nebula::client::RawRecord>>
  [[deprecated("Use `FOO.records_ref() = BAR;` instead of `FOO.set_records(BAR);`")]]
  std::pmr::deque<nebula::client::RawRecord>& set_records(T_BindingTable_records_struct_setter&& records_) {
    records_ref() = std::forward<T_BindingTable_records_struct_setter>(records_);
    return __fbthrift_field_records;
  }

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<BindingTable>;
  friend void swap(BindingTable& a, BindingTable& b);
};

template <class Protocol_>
uint32_t BindingTable::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}

}} // nebula::cpp2

namespace apache { namespace thrift {

template <> struct TEnumDataStorage<::nebula::cpp2::Value::Type>;

template <> struct TEnumTraits<::nebula::cpp2::Value::Type> {
  using type = ::nebula::cpp2::Value::Type;

  static constexpr std::size_t const size = 12;
  static folly::Range<type const*> const values;
  static folly::Range<folly::StringPiece const*> const names;

  static char const* findName(type value);
  static bool findValue(char const* name, type* out);

};
}} // apache::thrift
