/**
 * Autogenerated by Thrift for graph.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "graph_types.h"

namespace nebula {
namespace graph {
namespace cpp2 {

struct graph_constants {};

}  // namespace cpp2
}  // namespace graph
}  // namespace nebula
