# This is temporary action for clients test.

name: build-ngadmin
on:
  push:
    branches: [master, mizy-test, "release-**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build package
    runs-on:
      - self-hosted
      - ${{ matrix.os[0] }}
    strategy:
      matrix:
        os:
          - [nebula-arm, arm64]
          - [nebula-fast, amd64]
    container:
      image: vesoft/nebula-dev:ubuntu2004
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: false
      - name: ngadmin build
        run: |
          make build
          mkdir build
          cp -r examples build/
          cp bin/ngadmin build/
        working-directory: ngadmin
      - name: ngadmin build
        run: |
          make build
          mkdir build
          cp -r ./api/agent/etc build/
          cp ./api/agent/bin/agent build/
          cp ../ngadmin/build/ngadmin build/
          cp ../ngadmin/examples/ build/
        working-directory: agent
      - uses: actions/upload-artifact@v2
        with:
          path: ./ngadmin/build/*
          name: ngadmin-linux-${{ matrix.os[1] }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./agent/build/*
          name: ngadmin-agent-linux-${{ matrix.os[1] }}
