name: Generate API reference via Doxygen and push to GitHub Pages
env:
  # Specify the doc version to which the API reference belongs
  doc_version: 5.0_base
  ENSITE_PASSWORD: ${{ secrets.ENSITE_PASSWORD }}
  ZHSITE_PASSWORD: ${{ secrets.ZHSITE_PASSWORD }}
on:
  push:
    branches:
        # Remember to update the branch name
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch all commits/branches for gitversion

    - name: Extract branch name
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
       
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Generate Java API reference 
    - name: Generate Documentation for Java
      run: |
        echo "PROJECT_NUMBER=$BRANCH_NAME" >> doxygen/java-config
        mkdir -p $BRANCH_NAME/api_reference/java
        echo "OUTPUT_DIRECTORY=$BRANCH_NAME/api_reference/java" >> doxygen/java-config
        doxygen doxygen/java-config
    
    # Generate Python API reference
#    - name: Generate Documentation for Python
#      run: |
#        echo "PROJECT_NUMBER=$BRANCH_NAME" >> doxygen/python-config
#        mkdir -p $BRANCH_NAME/api_reference/python
#        echo "OUTPUT_DIRECTORY=$BRANCH_NAME/api_reference/python" >> doxygen/python-config
#        doxygen doxygen/python-config   

    # Generate C++ API reference
#    - name: Generate Documentation for CPP
#      run: |
#        echo "PROJECT_NUMBER=$BRANCH_NAME" >> doxygen/cpp-config
#        mkdir -p $BRANCH_NAME/api_reference/cpp
#        echo "OUTPUT_DIRECTORY=$BRANCH_NAME/api_reference/cpp" >> doxygen/cpp-config
#        doxygen doxygen/cpp-config              
   
     # Compresses HTML files into a tar.gz file
    - name: compress all API reference
      run: |
        tar -zcvf api_doc.tar.gz $BRANCH_NAME
        ls -ll  

    - name: check if file exists
      run: |
        if [ -f api_doc.tar.gz ]; then
          echo "File exists"
        else
          echo "File does not exist"
          exit 1
        fi

    - name: transfer api reference to nebula server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 20.163.77.63
        username: azureuser
        password: ${{ env.ENSITE_PASSWORD }}
        port: 404
        source: api_doc.tar.gz   
        target: /var/www/ent-docs/${{ env.doc_version }}/
        
    - name: uncompress api reference in nebula server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 20.163.77.63
        username: azureuser
        password: ${{ env.ENSITE_PASSWORD }}
        port: 404
        script: |
          tar -zxf /var/www/ent-docs/${{ env.doc_version}}/api_doc.tar.gz -C /var/www/ent-docs/${{ env.doc_version}}/

    - name: transfer api reference to yueshu server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 121.40.218.31
        username: root
        password: ${{ env.ZHSITE_PASSWORD }}
        port: 404
        source: api_doc.tar.gz   
        target: /var/www/ent-docs/${{ env.doc_version }}/      

    - name: uncompress api reference in yueshu server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 121.40.218.31
        username: root
        password: ${{ env.ZHSITE_PASSWORD }}
        port: 404
        script: |
          tar -zxf /var/www/ent-docs/${{ env.doc_version}}/api_doc.tar.gz -C /var/www/ent-docs/${{ env.doc_version}}/
          