name: nightly

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
env:
  OSS_DIR: minio/nightly-build/nebula-ng-tools

jobs:
  build:
    name: build source code and binary
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: false
      - name: setup java 
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: package source code
        run: |
          cd package
          ./package.sh --product=java --release-name=nightly --package-name=nebula-java
          ./package.sh --product=golang --release-name=nightly --package-name=nebula-golang
          ./package.sh --product=ngql --release-name=nightly --package-name=nebula-ngql
          ./package.sh --product=ngctl --release-name=nightly --package-name=nebula-ngctl
          ./package.sh --product=operator --release-name=nightly --package-name=nebula-operator
      - name: build ngctl
        run: |
          cd ngctl
          make 
      - name: build ngql
        run: |
          cd ngql
          make
      - uses: vesoft-inc/.github/actions/setup-minio@master
        with:
          minio_url: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET }}
        
      - name: upload asserts
        run: |
          today=$(date "+%Y.%m.%d")
          mc cp ngql/ngql $OSS_DIR/$today/
          mc cp ngctl/ngctl $OSS_DIR/$today/
          mc cp -r package/packages/ $OSS_DIR/$today/packages/

  docker:
    name: build docker image
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push Docker images - ngctl
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: reg.vesoft-inc.com/vesoft-ng/ngctl:nightly
          push: true
          context: .
          file: ./ngctl/Dockerfile
          target: ngctl
      - name: Build and push Docker images - ngql
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: reg.vesoft-inc.com/vesoft-ng/ngql:nightly
          push: true
          context: .
          file: ./ngql/Dockerfile
          target: ngql
