name: nightly

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  docker:
    name: build docker image
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push Docker images - ngctl
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: reg.vesoft-inc.com/vesoft-ng/ngctl:nightly
          push: true
          context: .
          file: ./ngctl/Dockerfile
          target: ngctl
      - name: Build and push Docker images - ngql
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: reg.vesoft-inc.com/vesoft-ng/ngql:nightly
          push: true
          context: .
          file: ./ngql/Dockerfile
          target: ngql
