# This is temporary action for clients test.

name: release
on:
  release:
    types:
      - published


jobs:
  deploy-kafka-connector-snapshot:
    runs-on: [ self-hosted, linux ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: |
          mvn -B package -Dmaven.javadoc.skip=true -Dmaven.test.skip=true

      - name: setup minio
        uses: vesoft-inc/.github/actions/setup-minio@master
        with:
          minio_url: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET }}

      - name: Get the version
        id: get_version
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          tagnum=$(echo $tag | sed 's/^v//')
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "tagnum=$tagnum" >> $GITHUB_OUTPUT
        shell: bash

      - name: Copy kafka connector to release on MinIO
        run: |
          mv target/ nebula-graph-kafkaconnector/
          tar czf ./nebula-graph-kafkaconnector-${{ steps.get_version.outputs.tagnum }}.tgz nebula-graph-kafkaconnector/kafka-connect-nebula-${{ steps.get_version.outputs.tagnum }}.jar
          sha256sum nebula-graph-kafkaconnector-${{ steps.get_version.outputs.tagnum }}.tgz > nebula-graph-kafkaconnector-${{ steps.get_version.outputs.tagnum }}.tgz.sha256sum.txt
          mc cp nebula-graph-kafkaconnector-${{ steps.get_version.outputs.tagnum }}.tgz minio/release-build/nebula-ng-kafka-connector/${{ steps.get_version.outputs.tagnum }}/
          mc cp nebula-graph-kafkaconnector-${{ steps.get_version.outputs.tagnum }}.tgz.sha256sum.txt minio/release-build/nebula-ng-kafka-connector/${{ steps.get_version.outputs.tagnum }}/
        working-directory: connector
        
      - name: Trigger yueshu-release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: vesoft-inc/yueshu-release
          event-type: trigger-nebula-ng-kafka-connector
          client-payload: '{"origin_tag": "${{ steps.get_version.outputs.tag }}"}'
