# Copyright (c) 2024 vesoft inc. All rights reserved.

name: release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  OSS_RELEASE_DIR: "minio/release-build/nebula-ng-tools"

jobs:
  package:
    runs-on: [self-hosted, linux]
    steps:
      - uses: webiny/action-post-run@3.1.0
        with:
          run: find . -mindepth 1 -delete
      - uses: actions/checkout@v4
      - uses: vesoft-inc/.github/actions/tagname@master
        id: tagname
      - uses: vesoft-inc/.github/actions/setup-minio@master
        with:
          minio_url: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET }}
      - name: Upload golang src to Minio
        env:
          TAG: ${{ steps.tagname.outputs.tagnum }}
          PROJECT: golang
        run: |
          cd ${PROJECT}
          rm -rf .git .gitignore 
          tar zcvf nebula-${PROJECT}-${TAG}.tar.gz *
          mc cp nebula-${PROJECT}-${TAG}.tar.gz ${OSS_RELEASE_DIR}/${PROJECT}/
      - name: Upload java src to Minio
        env:
          TAG: ${{ steps.tagname.outputs.tagnum }}
          PROJECT: java
        run: |
          cd ${PROJECT}
          rm -rf .git .gitignore 
          tar zcvf nebula-${PROJECT}-${TAG}.tar.gz *
          mc cp nebula-${PROJECT}-${TAG}.tar.gz ${OSS_RELEASE_DIR}/${PROJECT}/
      - name: Upload kafka-connector src to Minio
        env:
          TAG: ${{ steps.tagname.outputs.tagnum }}
          PROJECT: kafka-connector
        run: |
          cd ${PROJECT}
          rm -rf .git .gitignore 
          tar zcvf nebula-${PROJECT}-${TAG}.tar.gz *
          mc cp nebula-${PROJECT}-${TAG}.tar.gz ${OSS_RELEASE_DIR}/${PROJECT}/
      - name: Upload spark-connector src to Minio
        env:
          TAG: ${{ steps.tagname.outputs.tagnum }}
          PROJECT: spark-connector
        run: |
          cd ${PROJECT}
          rm -rf .git .gitignore 
          tar zcvf nebula-${PROJECT}-${TAG}.tar.gz *
          mc cp nebula-${PROJECT}-${TAG}.tar.gz ${OSS_RELEASE_DIR}/${PROJECT}/

  deploy-java:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Deploy Release to Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.JAVA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ""
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          directory: java
          maven_goals_phases: "clean deploy -Dmaven.test.skip=true"

