# This is temporary action for clients test.

name: snapshot
on:
  push:
    branches: [ master]


jobs:
  deploy-kafka-connector-snapshot:
    runs-on: [ self-hosted, nebula-fast ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Deploy nebula-connector_spark2.4  to SNAPSHOT
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.JAVA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ""
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          maven_goals_phases: "clean deploy -Dmaven.javadoc.skip=true"

