# Copyright (c) 2024 vesoft inc. All rights reserved.

name: snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch of master"
        required: true
        default: "master"

defaults:
  run:
    shell: bash


jobs:
  deploy-java-driver-snapshot:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Deploy Release to Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.JAVA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ""
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          directory: java
          maven_goals_phases: "clean deploy -Dmaven.test.skip=true"



  deploy-spark-connector-snapshot:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Deploy Release to Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.JAVA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ""
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          directory: spark-connector
          maven_goals_phases: "clean deploy -Dmaven.test.skip=true"