# This is temporary action for clients test.

name: snapshot
on:
  push:
    branches: [ master]


jobs:
  deploy-kafka-connector-snapshot:
    runs-on: [ self-hosted, nebula-fast ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: |
          mvn -B package -Dmaven.javadoc.skip=true -Dmaven.test.skip=true

      - name: setup minio
        uses: vesoft-inc/.github/actions/setup-minio@master
        with:
          minio_url: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET }}

      - name: Copy kafka connector to release on MinIO
        run: |
          mv target/ nebula-graph-kafkaconnector/
          tar czf ./nebula-graph-kafkaconnector-5.0-SNAPSHOT.tgz nebula-graph-kafkaconnector/kafka-connect-nebula-5.0-SNAPSHOT.jar
          mc cp nebula-graph-kafkaconnector-5.0-SNAPSHOT.tgz minio/nightly-build/nebula-ng-kafka-connector/5.0-SNAPSHOT/
        working-directory: connector


