# This is temporary action for clients test.

name: test client
on:
  push:
    branches: [master, "release-**"]
  pull_request:
    branches: [master, "release-**"]
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-client:
    runs-on: [self-hosted, nebula-fast]
    container:
      image: vesoft/nebula-dev:ubuntu2004
    env:
      GOPROXY: ${{ vars.GOPROXY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: false
      - name: NebulaGo Unit tests
        run: make test
        working-directory: golang
      - name: console build
        run: make build
        working-directory: console
      - name: ngadmin build
        run: make build
        working-directory: ngadmin
      - name: k6-plugin build
        run: make build-dev
        working-directory: k6-plugin

  java-client:
    runs-on: [self-hosted, nebula-fast]
    container:
      image: vesoft/nebula-dev:ubuntu2004
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{"id": "nexus", "name": "nexus-maven-proxy", "mirrorOf": "*", "url": "${{ vars.MAVEN_MIRRORS }}"}]'
      - name: Build with Maven
        run: |
          mvn -B install -pl client -D test=DataTest
          mvn -B package -Dmaven.test.skip=true
        working-directory: java

  ldbc-driver:
    runs-on: [ self-hosted, nebula-fast ]
    container:
      image: vesoft/nebula-dev:ubuntu2004
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          mirrors: '[{"id": "nexus", "name": "nexus-maven-proxy", "mirrorOf": "*", "url": "${{ vars.MAVEN_MIRRORS }}"}]'
      - name: Build with Maven
        run: |
          cd java
          mvn -B install -Dmaven.test.skip=true
          cd ../ldbc_snb_interactive_implementations
          mvn -B package -Pnebula -Dmaven.test.skip=true
